### ISSUE TITLE
Swaps won't populate "to" asset amount

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1031]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Version: b2fac99 (2022-02-22)

Perform a swap

### What did not work?

"To" currency value won't appear. I've tried this with 3 different accounts (QA seed import, personal QA account import, and Ledger)

https://user-images.githubusercontent.com/7005061/155392235-8a4100ae-1e69-497e-bb9f-05f5dda4de0b.mov

**Comment by cairomassimo** [comment]
Duplicate of #1015
