### ISSUE TITLE
Not able to approve assets on uniswap w/ledger

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1032]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Version: b2fac99 (2022-02-22)

Approve tokens from my ledger on to swap on uniswap

### What did not work?

I wasn't able to approve! ledger appears to show up as a read-only account ("Read-only accounts cannot sign")

https://user-images.githubusercontent.com/7005061/155411307-46e8fc5c-cebd-4a8a-bb3a-5e61744b8f28.mov

<img width="386" alt="Screen Shot 2022-02-23 at 4 28 21 PM" src="https://user-images.githubusercontent.com/7005061/155411569-18b680c1-fb5d-4d0c-a6a5-fdb07b561433.png">

imported account works fine on UNI..

https://user-images.githubusercontent.com/7005061/155411347-26beae25-f8f7-4fc8-b7a6-c08d3aa118b5.mov

ledger works fine on balancer...

https://user-images.githubusercontent.com/7005061/155411374-cb991e8a-b25d-439a-a76d-089a5a52d77c.mov

**Comment by cairomassimo** [comment]
This triggers the "sign typed data" flow, which is currently disconnected from the rest of the signing flows, and does not support Ledger. Will fix soon.

**Comment by cairomassimo** [comment]
The fix has to touch a lot of code and will take longer than expected.
(see #823 as reference)

**Comment by fernya** [comment]
On LedgerService side we've got some initial code to do that, I start to add it to SigningService.

**Comment by fernya** [comment]
Hey @mr-michael  

if you're interested, there's a WIP build to try with enabled typed signing on Ledgers!

https://github.com/tallycash/extension/suites/5474430092/artifacts/174493736
