### ISSUE TITLE
Ledger not detected on Brave

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1034]
### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Import Ledger account on Brave

Version: b2fac99 (2022-02-22)

### What did not work?

Ledger was not detected

<img width="1407" alt="Screen Shot 2022-02-23 at 4 41 57 PM" src="https://user-images.githubusercontent.com/7005061/155413570-1d723802-8617-4715-8509-511ac4181964.png">

<img width="654" alt="Screen Shot 2022-02-23 at 4 39 41 PM" src="https://user-images.githubusercontent.com/7005061/155413579-c7cf9274-065b-410e-bb1a-a0aefa7eda19.png">

**Comment by fernya** [comment]
Hey Michael, are you sure that you already had your Ledger in unlocked state with Ethereum app open?

For me the list is populated when all three instructions were carried out.

**Comment by SJQuality** [comment]
Looking at this one. I see the Ledger in the list, but it will not connect. 
https://www.awesomescreenshot.com/video/8833724?key=2f2e937a5726017bf11c521b80e72c5b

Network and Console are missing calls compared to Chrome. Like it's not even trying. 

Chrome gives me this:
![image](https://user-images.githubusercontent.com/103908695/167717350-6939f97b-81ff-4f6e-939d-a4a3d0104799.png)

Brave gives me this:
![image](https://user-images.githubusercontent.com/103908695/167717435-f78e04c3-3adf-4df3-b97f-9ac68a5df9aa.png)
