### ISSUE TITLE
Ledger not detected on Firefox

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1035]
### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

Import Ledger account @ Version: b2fac99 (2022-02-22)

### What did not work?

Device was not recognized

https://user-images.githubusercontent.com/7005061/155414150-dd6c5713-4744-4c96-a1bc-80ce10ad20d9.mov

**Comment by mhluongo** [comment]
This is more of a feature request than a bug report!

**Comment by fernya** [comment]
Thanks @mhluongo it is one indeed.

**Comment by cairomassimo** [comment]
If WebUSB is not supported, we should hide the Connect Ledger altogether.
I'm going to fix this.
