### ISSUE TITLE
Weird scrolling in swap token list

### ISSUE THREAD

**Issue by cairomassimo** [tallycash/extension#1038]
Title and search bar are scrolling along with the list, causing overlap of close button and search bar. I'm assuming this is not the intended behviour, and that only the list should scroll, @VladUXUI?
![Screenshot from 2022-02-24 15-11-48](https://user-images.githubusercontent.com/4115717/155531276-7856aa64-82bb-461f-bcb9-7df11f9510d7.png)

**Comment by VladUXUI** [comment]
That is correct
