### ISSUE TITLE
Ledger inactivity time-out handling

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1051]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/947105148788965386

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Browse through Ledger derivation path addresses

### What did not work?

I was browsing through the first 3 pages of path addresses without issues. Then my ledger 'timed-out' due to inactivity, required me to re-enter my pin. This happened while trying to open page 4, paths 18-24. The addresses on this page were not showing.

I re-entered my pin and continued browsing. Addresses on page 24-30 onwards were displayed again. Going back to addresses 18-24 didn't work, remained blank.

_Error: _Error encountered! ledgerID: LEDGER_NANO_S_0x.... addy accountID: m/44'/60'/0'/0/18 error: TransportStatusError: Ledger device: UNKNOWN_ERROR (0x6b0c)
genericLogger @ background.js:77601__ 

After disabling and enabling the extension it was loading addresses 18-24 without issues.

Was able to reproduce the error with addresses 78-84 by deliberately timing out the ledger.

_Error encountered! ledgerID: LEDGER_NANO_S_0x.... addy accountID: m/44'/60'/0'/0/78 error: TransportStatusError: Ledger device: UNKNOWN_ERROR (0x6b0c)
genericLogger @ background.js:77601
background.js:77600_ 

Would be good if it would retry to load the addresses in case something like this happens. 

<img width="368" alt="Screen Shot 2022-02-27 at 17 24 09" src="https://user-images.githubusercontent.com/71384922/155890587-f9752048-63ef-4802-9d94-5b6f6ee3baf7.png">

Wallet version as linked in: https://discord.com/channels/808358975287722045/944337346684391474/945737169459363880

### Version

Community Edition v0.11.2

**Comment by cairomassimo** [comment]
That's right, we don't handle this case just yet. We'll try and fix it.
Thanks for the report!
