### ISSUE TITLE
Wrong Ledger logo

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1061]
We are using the old Ledger logo for account pages, same in add new account and account selection modal.
<img width="360" alt="image" src="https://user-images.githubusercontent.com/80846886/156310566-380ad98c-6c0a-4d5b-b1fd-ff4e67c1d8c9.png">

The logo is this one:
<img width="32" alt="Ledger_logo" src="https://user-images.githubusercontent.com/80846886/156310791-20713fc9-2124-4f22-9276-dd8b83fccce9.png">

**Comment by VladUXUI** [comment]
![ledger_icon@2x](https://user-images.githubusercontent.com/80846886/156396152-db6f0a26-6b8a-4150-a540-19fce1fad1dd.png)

Adding the correct format for this

**Comment by henryboldi** [comment]
Thank you @VladUXUI! I'll swap this in later today
