### ISSUE TITLE
Remove derivation path

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1063]
Right now we have a couple of things in derivation path that we do not support.

<img width="327" alt="image" src="https://user-images.githubusercontent.com/80846886/156311908-3c32939e-b92b-4838-8a65-becad0dacc3b.png">

As far as i know we only have Ethereum.

**Comment by Shadowfiend** [comment]
I guess the UX question here is… Should we help people who want to import their Trezor accounts directly? <_<

We should probably put RSK behind a feature flag though.

**Comment by VladUXUI** [comment]
Nono, let's not help users import Hardware wallet recovery phrase please.
We even have a warning in the import phrase page about not importing hw phrases

**Comment by mhluongo** [comment]
Note that we need these for Ledger users who have Trezor seed phrases, regardless... otherwise their Ledger won't derive addresses correctly

Changed the Trezor option to "BIP 44 (Trezor and MetaMask)" in #1950. Closing this!
