### ISSUE TITLE
Recovery phrase verification requests same word twice while actual phrase had no duplicates

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1073]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/948509616390688768

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user tried to create a new 24 word recovery phrase through Tally

### What did not work?

This one may be difficult to reproduce. Extension was already removed so no logs available.

The verification process showed requested two times word number 2. The actual recovery phrase had 24 unique words. 

Word #2 was also only displayed once on the bottom in the orange boxes. There were a total of 8 words on the bottom, so  one word that didn't match any of the numbers above. 

The user stopped the verification process and created a new phrase, that worked.

![image](https://user-images.githubusercontent.com/71384922/156569538-d33391fb-2ecd-4976-8074-148d9f295d4a.png)

### Version

Community Edition v0.11.2

**Comment by beemeeupnow** [comment]
Another user encountered this bug: https://discord.com/channels/808358975287722045/808358975287722048/956027779139391510

**Comment by henryboldi** [comment]
Left this straggling. Will pick it ups soon!

**Comment by Shadowfiend** [comment]
We should be able to randomize indices rather than mnemonic words and eliminate a class of bugs here:

https://github.com/tallycash/extension/blob/main/ui/pages/Onboarding/OnboardingVerifySeed.tsx#L73-L78

->

```typescript
  const [randomizedMnemonicIndexes] = useState(
    mnemonicToVerify
      ?.map((_, index) => index)
      .sort(() => Math.random() - 0.5)
      .slice(0, 8)
  )
```

Or so.

**Comment by henryboldi** [comment]
Good idea 🙇

**Comment by SJQuality** [comment]
I haven't seen this happen since the fix. Assuming Done Main Build #2950
