### ISSUE TITLE
WETH and USDC balances not showing up In wallet balances

### ISSUE THREAD

**Issue by Hennessy231** [tallycash/extension#1082]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/949055034665091102

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I have sent ETH to Tally wallet and the ETH balance shows up in Tally fine. I did the same transactions but instead sent USDC and WETH in separate transactions.  Sending from MM to Tally. Now the USDC and WETH balances have not shown up in Tally. All of the transactions have been confirmed in Etherscan. 

Transaction hash for USDC Send:  0xf186272baaad2ba0d7f01f16379268294ddd152135ebac1785fd7419e1065134
Transaction hash for WETH Send:  0xeb29551085fd46f41bcf0be8b79d7dc59a531aae0653a10f421b9d1730bb5c76

### What did not work?

Both the balances for USDC and WETH never appeared in Tally wallet even when they left my account in MM. I have checked Tally wallet on etherscan and the transactions have not appeared yet.

Tally Wallet address:  0x7d7b0a482509e81fe5170410ad1c1f4f418845da

**Comment by greg-nagy** [comment]
Closed with #1746
