### ISSUE TITLE
Ledger derivation path dropdown menu is missing the Legacy m/44'/60'/0' path

### ISSUE THREAD

**Issue by logonaut** [tallycash/extension#1086]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/948817668511780885

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

On the "select Ledger accounts" screen, I was trying to access a Ledger account derived using the Legacy derivation path m/44'/60'/0'

![Screen Shot 2022-03-03 at 6 51 15 PM](https://user-images.githubusercontent.com/19627089/156679154-08b81b51-c4be-4694-bca2-b526230bb404.png)

### What did not work?

The Legacy derivation path m/44'/60'/0' was not available from the derivation path dropdown menu. However, I was able to add it as a custom path and successfully access the desired wallet address in that manner.

![Screen Shot 2022-03-03 at 6 32 56 PM](https://user-images.githubusercontent.com/19627089/156679424-2fb9f02d-e839-4e87-8946-02f80e51a05b.png)

![Screen Shot 2022-03-03 at 6 33 17 PM](https://user-images.githubusercontent.com/19627089/156679453-c094f0b7-5f9b-403d-a209-6a4311012518.png)

### Version

Community Edition v0.12.0

### Relevant log output

```shell
N/A
```

**Comment by VladUXUI** [comment]
Closely related to this https://github.com/tallycash/extension/issues/1063
