### ISSUE TITLE
Swap from button has incorrect hover trigger area

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#1087]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Select swap from asset.

### What did not work?

Hover effect is triggered when mouse is not over the Select token button
![Screenshot 2022-03-04 at 13 23 30](https://user-images.githubusercontent.com/20949277/156763241-496373d2-a2d6-4757-8edd-03fdf90ccd81.png)

**Comment by rootial** [comment]
i can take a look this issue

**Comment by rootial** [comment]
when we hover on the label as below, it will trigger the hover effect of select button and if we click the label row, it also opens the select asset panel just like clicking the "Select token" button.
This kind of weird, but i want to confirm with the ux if it's expected? @VladUXUI 
<img width="380" alt="image" src="https://user-images.githubusercontent.com/3824034/164279720-dcc95f35-e185-4987-80ed-bac7c4961b5b.png">

**Comment by SJQuality** [comment]
Vid of issue @VladUXUI 
https://www.awesomescreenshot.com/video/8833218?key=27eff3596e20d6cd25a076d3daf20c4b

**Comment by VladUXUI** [comment]
Thanks for this, indeed the intended functionality is to have the dropdown hover only on the dropdown and not around it
