### ISSUE TITLE
Copy Wallet Address With One Click

### ISSUE THREAD

**Issue by commstark** [tallycash/extension#1095]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/949452259954147380

### What would you like to be able to do?

**What:** One click to copy address to clipboard

**Where:** Top right hand corner where current wallet address is semi hidden (Near where picture of dog is displayed).

**Why:** It's currently difficult to find where you can see your whole address (must click on "rRceive" and find it under the QR code)

**But actually Why, Why do we care** Copy and pasting a new address is a very common feature in other wallets (see feature compare list). Additionally it has practical applications since users need their address to receive payments or to fill out forms (WLs).

**How** Simply make the address in the top right corner clickable. Click on Address = Crtl+C

**When** ASAP if it's not a heavy lift. Would be the first thing new users complain about during launch. Willing to give this a try if it's super easy and you think a normie like me could handle it.

<img width="386" alt="Screen Shot 2022-03-05 at 10 05 27 AM" src="https://user-images.githubusercontent.com/97203233/156895086-9a4bf90b-4a7a-4f26-a3ec-538e2c388b29.png">

**Comment by Shadowfiend** [comment]
This is covered in #593! Closing this in favor of that issue, which is on our shortlist for the next week or so barring anything unforeseen.
