### ISSUE TITLE
Add "ETH swaps coming soon" label

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1096]
Let's add a label to "from" asset token selector (it's fine to include in "to" selector as well if that's easier) indicating "ETH coming soon"

(We should get this out in next week's release if possible!)

<img width="436" alt="Screen Shot 2022-03-05 at 1 10 26 PM" src="https://user-images.githubusercontent.com/7005061/156895259-3a7e5943-0a6b-4a7b-9370-ffe6d9d7d110.png">

**Comment by VladUXUI** [comment]
I think it's looking good. I would just use our notification system (that i'm aware is not yet fully fleshed out and embedded)

<img width="382" alt="image" src="https://user-images.githubusercontent.com/80846886/156915412-f04251da-9559-4af7-97e5-6e4dc04aa11c.png">

**Comment by VladUXUI** [comment]
Postponing this as there might be a fix here
https://github.com/tallycash/extension/pull/1103
