### ISSUE TITLE
Integrate POKT as a fallback provider on supported networks

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1097]
Alchemy has great uptime and latency, but a single centralized provider doesn't have the same redundancy as a decentralized network. Using both means lowering the likelihood of an outage for users.

We want to integrate POKT network (and likely other providers in the future) as a way to...

* increase redundancy / liveness
* lower costs of running the wallet

I propose we do that initially by making use of the new `SerialFallbackProvider`. Once it's deployed and we have some confidence, we should...

- [ ] Build fallback mechanisms for specialized Alchemy endpoints. We'll need those for other chains, regardless.
- [ ] Include an additional mechanism that allows the wallet to "mix" multiple providers, likely defined as an environment variable. This would allow us to set an initial split of, say, 90/10 Alchemy to POKT, then slowly optimize the levels for uptime and cost.

**Comment by 0xDaedalus** [comment]
> Include an additional mechanism that allows the wallet to "mix" multiple providers, likely defined as an environment variable. This would allow us to set an initial split of, say, 90/10 Alchemy to POKT, then slowly optimize the levels for uptime and cost

This has been completed via public RPC endpoints

> Build fallback mechanisms for specialized Alchemy endpoints. We'll need those for other chains, regardless.

This has not been completed but will be ticketed in a separate ticket as it has no relevance to POKT
