### ISSUE TITLE
Sign Permit not permitting signing :) - Ledger

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1099]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Trying to approve USDC on Uniswap
Using Ledger.

### What did not work?

Didn't seem to permit
![CleanShot 2022-03-06 at 09 46 29](https://user-images.githubusercontent.com/80846886/156914139-bdc19158-4990-4ee3-9fde-a981f395306e.gif)

Errors in log
<img width="651" alt="image" src="https://user-images.githubusercontent.com/80846886/156914173-960e9e63-c07b-4cb9-a01f-b8da1752c9e5.png">
<img width="660" alt="image" src="https://user-images.githubusercontent.com/80846886/156914187-375c7534-6593-4547-89ee-4fc77d7d28e5.png">

### Relevant log output

```shell
Version: v0.12.0-25-gb11d448a (1 Mar 2022)
```

**Comment by fernya** [comment]
Hi @VladUXUI , I think I found some trigger for this bug, but I need your confirmation:

If you restart the extension with Ethereum app active, can you see the problem again?
vs.
If you restart the extension without Ethereum app active, and start it when the signing dialog ask, does it succeed?

**Comment by VladUXUI** [comment]
Humm, i can't reproduce.
With the latest build, if i try and sign permit, it just keeps the sign button in a loading state. (When Ledger is locked)
But if i unlock my Ledger, i can see the Sign typed data on my ledger.
So extension is sending the information to my ledger (even if locked), but i'm not getting the "sign with ledger page"

**Comment by fernya** [comment]
I think #1068 will resolve this, as the normal transaction flow has more elaborate safeguards in place.

**Comment by VladUXUI** [comment]
Looks to have been fixed
