### ISSUE TITLE
Sign-In with Etherem - only raw data displays

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1104]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Ideally we have decoded data..
<img width="200" alt="Screen Shot 2022-03-06 at 9 47 31 PM" src="https://user-images.githubusercontent.com/7005061/156959228-43671de1-0bf1-4098-9efa-3638d1fd875c.png">

### What did not work?

-

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/157396490-7b590b21-d25f-4d4e-9911-a540629fb621.png)

And [Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=7405%3A178366)
