### ISSUE TITLE
Fix unnecessary scrollbars in Firefox

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#1129]
### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

Testing whole application

### What did not work?

Scrollbars are visible where they shouldn't be, for example:
- during changing tabs animation
https://user-images.githubusercontent.com/20949277/157454143-edcc1244-93f2-4ffe-b7e4-ad727f214806.mov
- opening extension main page
https://user-images.githubusercontent.com/20949277/157454266-c69724cb-cdee-45b2-9235-3404318b6fbd.mov
- in select token assets list
<img width="396" alt="Screenshot 2022-03-09 at 14 48 27" src="https://user-images.githubusercontent.com/20949277/157454452-64ee1dd6-c2ea-413d-a3ff-b267e0bc7453.png">

**Comment by SJQuality** [comment]
Looks like there are no more scroll bars anywhere. Closing.
