### ISSUE TITLE
Change copy from Copy to clipboard to Copy address

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1135]
Greg and Antonio both have a good point that copy to clipboard is not clear enough what you are copying if it's an ENS name and not an Address.

> That's one way to make this decision ... :) 
> 
> Not a blocker for sure, but this behavior is a bit weird. 
> I click on a copy for an eth address and I get the address on the clipboard. 
> But makes sense. 
> 
> Could we make this a clearer @VladUXUI? 
> ![CleanShot 2022-03-10 at 12 43 28](https://user-images.githubusercontent.com/7690112/157655204-adbdabb9-967d-4a87-94b0-16b193be0f36.gif)

_Originally posted by @greg-nagy in https://github.com/tallycash/extension/pull/1118#discussion_r823628299_

**Comment by Shadowfiend** [comment]
> Greg and Antonio both have a good point that copy to clipboard is not clear enough

I'll attribute this to you because I thought this was what I saw in the design in the first place 😂 so I wasn't making a suggestion but a design implementation correction, I thought!
