### ISSUE TITLE
Release 0.12.1 still has 'ETH' coming soon in 'Swap from'

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1144]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Remove the 'ETH' coming soon indicator from the 'swap from' option since it's live.

### What did not work?

<img width="359" alt="Screenshot 2022-03-11 at 09 26 54" src="https://user-images.githubusercontent.com/71384922/157830602-76ce1244-44df-4a8b-953c-ee8b51888b01.png">

### Version

Community Edition v0.12.1

**Comment by kelvin0897** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.
