### ISSUE TITLE
Onboard screen 4 mentions TallHo instead of Tally Ho

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1145]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

On board

### What did not work?

Mixed use of 'Tally Ho' and 'TallyHo'

<img width="377" alt="Screenshot 2022-03-11 at 09 31 08" src="https://user-images.githubusercontent.com/71384922/157831638-984e1640-68ee-45c7-963e-909987a0fb03.png">

### Version

Community Edition v0.12.1

**Comment by rootial** [comment]
what's the expected words should we use ? @henryboldi @VladUXUI 
`Tally Ho`
`TallyHo`
`Tally Ho!`

**Comment by VladUXUI** [comment]
Hey @rootial, thanks for asking. The correct format is Tally Ho!
