### ISSUE TITLE
Text overlap when scrolling in Add wallet menu

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1146]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Add a wallet

### What did not work?

'Tally Ho!' and 'Add Wallet' overlap when scrolling in this menu

![Uploading Screenshot 2022-03-11 at 09.31.30.png…]()

### Version

Community Edition v0.12.1

**Comment by rootial** [comment]
can you add another screenshot, it's broken. @Naxsun

**Comment by henryboldi** [comment]
Resolved by https://github.com/tallycash/extension/pull/1238
