### ISSUE TITLE
Unable to import Ledger Legacy wallet using "Ethereum m/44'/60'/0'/0" derivation Path 

### ISSUE THREAD

**Issue by pirin** [tallycash/extension#1148]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/952240385437081650

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Truing to import Ledger Legacy Wallet

### What did not work?

I have 3 Addresses that are derived from Ledger (below is data from Ledger Live Advanced account settings):

Address 1 is a "legacy"  => "freshAddressPath": "44'/60'/0'/0",
Address 2 is non legacy => "freshAddressPath": "44'/60'/0'/0/0", 
Address 3 also non legacy =>  "freshAddressPath": "44'/60'/1'/0/0"

When trying to import them into Tally:
If I select "Ethereum m/44'/60'/0'/0: => Tally shows a list where I see Account 2  
If I select "Ledger Live" => Tally shows  a list where I see both Account 2 and Account 3

No matter what I try (even manually adding in a derivation path 44/60/0/0) I can't see Account 1

### Version

Community Edition v0.12.1

**Comment by fernya** [comment]
Hey @pirin! 
Thanks for reaching out! Would you kindly make the following test steps to bring us to the same page?

1. Add the following custom derivation path on addresses on the import screen: 
   a) 44'/60'/0'
   b) 44'/60'/0'/x
2. Check if the legacy addresses are properly shown in either case
