### ISSUE TITLE
Swap search text overlap with magnifying glass

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1149]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Search by contract address to swap

### What did not work?

<img width="358" alt="Screenshot 2022-03-12 at 19 18 22" src="https://user-images.githubusercontent.com/71384922/158029902-513edb12-9d2c-433e-abcf-434867ffc6fd.png">

### Version

Community Edition v0.12.1

**Comment by rootial** [comment]
@VladUXUI what is it supposed to look like ?

**Comment by SJQuality** [comment]
We could just remove the 🔎 when there is an input

**Comment by Shadowfiend** [comment]
A right padding that covers the search icon + some additional space should take care of this I expect.

**Comment by VladUXUI** [comment]
Yup, looks like a right padding of 56px does the trick. Leaving 16px on each side of the 24px search icon

<img width="943" alt="image" src="https://user-images.githubusercontent.com/80846886/167562401-e7e5436f-d93d-49f1-8bef-9e5b34468636.png">
