### ISSUE TITLE
Sign in with Ethereum issues

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1153]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/952007012005347418

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Users tried to sign in with Ethereum on Debank.com

https://debank.com/ --> can connect wallet but not verify the signature message

### What did not work?

https://debank.com/ --> can connect wallet but not verify the signature message. It doesn't set-up a verification transaction, there is no pop-up in Tally Ho to sign. It gives below error message directly.

<img width="415" alt="Screenshot 2022-03-13 at 08 40 02" src="https://user-images.githubusercontent.com/71384922/158050186-7ddea9f5-8485-44bb-b3b8-27eab0fe5dac.png">

For reference, here is the sign message when using MM.

<img width="339" alt="Screen Shot 2022-03-14 at 12 00 19" src="https://user-images.githubusercontent.com/71384922/158159351-96143b99-f599-42c3-9d9a-d36aef881bf2.png">

Below are my logs reproducing the error

### Version

Community Edition v0.12.1

### Relevant log output

```shell
logger.tss:60  🐛 Tally debug @ 2022-03-14T10:53:09.681Z
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
logger.tss:60  ❌ Tally error @ 2022-03-14T10:55:10.215Z
logger.tss:65 Error getting block prices from BlockNative Error: timeout (requestBody=null, requestMethod="GET", timeout=120000, url="https://api.blocknative.com/gasprices/blockprices", code=TIMEOUT, version=web/5.5.1)
    at Logger.makeError (index.jss:185:23)
    at index.jss:146:35
genericLogger @ logger.tss:65
error @ logger.tss:106
getBlockPrices @ gas.tss:30
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
api.blocknative.com/gasprices/blockprices:1          Failed to load resource: the server responded with a status of 429 ()
```

**Comment by Shadowfiend** [comment]
Are the logs for the connection problem or the supposed invalid signature? Let's file them separately and make sure the connection problem doesn't already have an issue.

**Comment by Naxsun** [comment]
Removed the connection problem. The logs were for both combined as well, reproduced the situation for debank.com and copied the new logs but seems more generic log data not related to this case.

**Comment by 0xDaedalus** [comment]
Looks like debank is attempting to call `window.ethereum.sendAsync` which as far as I can tell does not exist on the `TallyWindowProvider`.  Do we want to add `sendAsync` to our window provider and just have it call `send`?

**Comment by Shadowfiend** [comment]
Lordy. `sendAsync` works a little different than `send`, and looks a little more like `request`, but with callbacks:

```
interface JsonRpcRequest {
  id: string | undefined;
  jsonrpc: '2.0';
  method: string;
  params?: Array<any>;
}

interface JsonRpcResponse {
  id: string | undefined;
  jsonrpc: '2.0';
  method: string;
  result?: unknown;
  error?: Error;
}

type JsonRpcCallback = (error: Error, response: JsonRpcResponse) => unknown;

sendAsync(payload: JsonRpcRequest, callback: JsonRpcCallback): void;
```

We should implement it, though we should probably also `console?.warn?.(...)` scream into the void that the caller is using deprecated API. We'll also need to set the `id` if it's unset, and probably error the request if the id is a plain integer and <= our internal id counter (to avoid interference with our requests).

We also still need to refactor the data flow in the window provider to handle a map of handlers for the various request id responses, and this might be the right opportunity to do that.

@greg-nagy was this something that was on your radar for this week, or just the provider injection?

**Comment by Naxsun** [comment]
Wanted to mention that I was just able to connect and verify my wallet on debank with version 0.13.13
