### ISSUE TITLE
Approve limit UX - Allow changing back to infinity

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#1157]

**Comment by Shadowfiend** [comment]
I believe there was an open question here as to whether we *wanted* to allow changing it to infinite, and we were leaning towards “no” (beyond canceling an edit) ([ref discussion in flowdock](https://www.flowdock.com/app/cardforcoin/tally/threads/Ye5J_Q8_HxJ2mfZ0aYcxh50Fsbk)):

> V: Allowing a contract an infinite ammount is risky and can lead to users loosing funds.
So making if hard to figure out how to input infinite is more than ok.
> M: Ok I see. Are we ok with disallowing Infinite as a limit altogether?
> […]
> V: I’m ok with not allowing them to. If a request came in as infinite approval, and they clicked to change it, it means they want to change it.

**Comment by SJQuality** [comment]
@Shadowfiend Does this issue need to be closed?

**Comment by Shadowfiend** [comment]
I would check with @VladUXUI on whether the current working version is enough.

**Comment by VladUXUI** [comment]
Current working version is good as is
