### ISSUE TITLE
Wallet Balances Not Updating

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1158]
ERC-20 Token and ETH balances are not correctly updating in the application.  It is likely that #1082, #1067, and #1109 are all related to this issue.  This issue is here to coordinate bug-hunting efforts to help us get to the root cause quicker.

# Related issues
- [x] #1067 
- [ ] #1082

**Comment by 0xDaedalus** [comment]
This morning @Shadowfiend proposed a solution where we update the [`periodInMinutes`](https://github.com/tallycash/extension/blob/main/background/services/indexing/index.ts#L85) of account-wide token refresh from `30` to `1` minute - but unfortunately this does not fully address the issue - however I did learn some things while recreating / debugging.

1.  This issue seems to affect both ERC-20 transactions and regular ol' ETH.  The wallet did not pick up ETH sent to my wallet for over 4 hours. (The ETH appeared in the wallet after hitting the Refresh button).

2.  When performing a swap from ETH => USDC, I saw my ETH balance decrease , but my USDC balance stayed the same.  (The USDC did not appear in the wallet even after hitting the Refresh button)

3.  Re-installing the wallet resulted in my USDC balance disappearing completely (although I clearly see it on etherscan). The last calls I see to alchemy over the websocket connection are (in order): `eth_subscribe` `eth_getBalance` `eth_call` and `eth_blockNumber`.  The extension finishes "Diggin Deeper" and all I'm left in my wallet balances is ETH.

This suggests to me that:
a) decreasing the interval at which we call `handleTokenRefresh` will not do much (it seems we're having difficulty even creating a correct list of assets to track in the first place).
b) The "Refresh Button" does not seem to be as effective a fix as we had hoped.

**Comment by VladUXUI** [comment]
Is there any chance that you have "hide balance under $2" activated and your balance was bellow that?

**Comment by kelvindevv** [comment]
Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by 0xDaedalus** [comment]
No, these were all balances above $15

**Comment by 0xDaedalus** [comment]
I think I’ve found a reliable way to recreate the issue of swap transactions not going through:

- install fresh tally wallet
- import a wallet capable of swapping
- open background page console.
- navigate to the network tab
- turn off your laptop’s wifi
- hit cmd + r on the network tab (to simulate a disconnect) <— this part is key for some reason, just waiting for the websocket to disconnect will not consistently reproduce the issue
- turn wifi back on
- attempt a swap (your transaction will be stuck in pending and not make it to etherscan)

Note that it seems that the balance is not being updated is actually because the swap transaction is not properly being sent (at least when reproduced via the above).

**Comment by 0xDaedalus** [comment]
Perhaps another clue - this guy seems to be popping up every once in a while once we're in the `disconnected` state:

<img width="660" alt="image" src="https://user-images.githubusercontent.com/94649004/158641586-f53f0132-9ab0-4c97-9c68-e920dc3ba37d.png">

**Comment by Shadowfiend** [comment]
The latter error is about the UI/background connection. It *is* a bit unusual, but might just be a timing issue (a balance update that dispatches after a UI popover closes but before webext-redux cleans its port listeners up will try to notify the nonexistent UI popover about an action, even though the port is already closed).

**Comment by Shadowfiend** [comment]
> hit cmd + r on the network tab (to simulate a disconnect) <— this part is key for some reason, just waiting for the websocket to disconnect will not consistently reproduce the issue

This doesn't simulate a disconnect—cmd+r reloads the whole background page. What this ends up doing is starting up the extension while it's offline, which apparently behaves similarly enough to the disconnections triggering this that we can get some reproduction juice 💪 

It also means an easier way to do this is *probably* to just have wifi off while you onboard the extension, then turn wifi on to swap. Dev tools optional :)

**Comment by SJQuality** [comment]
Created this video to show repro steps. https://www.awesomescreenshot.com/video/8707784?key=6ebc87ca6500bc5d987bb4439d026ae6

During the break in the video, I reinstalled Tally while offline. Maybe during the setup of Tally we should do an internet connectivity check? Also, maybe we need a "Not connected to the internet" message?

**Comment by 0xDaedalus** [comment]
I have a consistent way to reproduce the issue on [this branch](https://github.com/tallycash/extension/tree/balance-bug-5/9) which honestly leaves me with more questions than answers.

Here is how to consistently recreate:

- checkout `balance-bug-5/9`
- build it
- remove tally from chrome
- turn off wifi
- add tally to chrome
- import account
- wait ~60 seconds in disconnected state
- turn wifi back on.

You should notice that balances do not initially show up - and then after about a minute - _token_ balances show up - but ETH balance does not.  Furthermore price calculations in the extension do not work- see below (this wallet is supposed to have 0.21 ether) due to .

<img width="384" alt="image" src="https://user-images.githubusercontent.com/94649004/167505693-9ae127a0-ff63-41f1-baeb-d611fb3ddc9f.png">

It seems that whats happening is [`getLatestBaseAccountBalance`](https://github.com/tallycash/extension/blob/main/background/services/chain/index.ts#L495) is throwing with `Error: could not detect network (event="noNetwork", code=NETWORK_ERROR, version=providers/5.5.3)` when called as part of [`addAccountToTrack`](https://github.com/tallycash/extension/blob/main/background/services/chain/index.ts#L517) and never being called again.

Any recommendations on the best way forward here?

**Comment by Shadowfiend** [comment]
Odd that it's not getting called again. Is the indexing service also being affected by this somehow?

**Comment by 0xDaedalus** [comment]
Looks like all three of these guys are failing silently:

https://github.com/tallycash/extension/blob/main/background/services/chain/index.ts#L520-L522

Notice that we do not `await` them.

**Comment by 0xDaedalus** [comment]
Big picture question here - Why do we ever [stop trying to send](https://github.com/tallycash/extension/blob/main/background/services/chain/serial-fallback-provider.ts#L212-L215) a given message?

Seems like we might be able to get some gains here by just continuously looping back through our list of providers until we get to one that is connected - no?  Even if we're offline for minutes or hours attempting to reconnect every maybe ~10 seconds it should not be that CPU intensive right?  I'm just thinking that something like a FIFO message queue could drastically decrease the complexity of the serial-fallback-provider.

**Comment by greg-nagy** [comment]
Closed with #1746
