### ISSUE TITLE
ETH <> WETH Swaps Are Misbehaving

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1168]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Trying to Swap ETH for WETH

### What did not work?

When trying to swap ETH for WETH - Tally asks the user to "Approve" ETH - which makes no sense since ETH is not an ERC-20 token and should not require approval.  If the user tries to confirm the approval the application hangs.

<img width="393" alt="image" src="https://user-images.githubusercontent.com/94649004/158483512-2b1d995e-5d7e-4cc6-8cef-8a25c6bf06b0.png">

Digging into the network request to 0x in the above example the following payload is sent

```
sellToken: ETH
buyToken: 0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2
gasPrice: 91920471125
slippagePercentage: 0.01
sellAmount: 10000000000000000
affiliateAddress: 0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12
feeRecipient: 0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12
buyTokenPercentageFee: 0.005
takerAddress: 0x47C7e1eF28F71dd7B5B56ECE1E6fFfcCB9068415
```

with a response of

```
allowanceTarget: "0x0000000000000000000000000000000000000000"
buyAmount: "10000000000000000"
buyTokenAddress: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
buyTokenToEthRate: "1"
chainId: 1
estimatedGas: "46000"
estimatedPriceImpact: "0"
gas: "46000"
gasPrice: "91920471125"
minimumProtocolFee: "0"
price: "1"
protocolFee: "0"
sellAmount: "10000000000000000"
sellTokenAddress: "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2"
sellTokenToEthRate: "1"
sources: []
value: "10000000000000000"
```

[(click here to see the response in-browser)](https://api.0x.org/swap/v1/price?sellToken=ETH&buyToken=0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2&gasPrice=91920471125&slippagePercentage=0.01&sellAmount=10000000000000000&affiliateAddress=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&feeRecipient=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&buyTokenPercentageFee=0.005&takerAddress=0x47C7e1eF28F71dd7B5B56ECE1E6fFfcCB9068415)

There is one things-of-note about the response that suggest that this may be an underlying issue with 0x.

1. The `sellTokenAddress` is not what we would expect to get back from sending a request with a `sellToken` of ETH (we expect `0xeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee` and instead see that the `sellTokenAddress` is equal to the `buyTokenAddress`

**Comment by Shadowfiend** [comment]
I've flagged the odd API behavior for the 0x folks and they're looking into it… Will update here when I hear more.

**Comment by Shadowfiend** [comment]
I think the right fix on our end here will be to change:

https://github.com/tallycash/extension/blob/c769dd9a6058e7bd7dbf5452f0e9591d5d467126/background/redux-slices/0x-swap.ts#L252

To check for `quote.allowanceTarget !== AddressZero` instead (`AddressZero` from `ethers.constants`).
