### ISSUE TITLE
Slippage Tolerance Dropdown does not work

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1169]
Clicking the Slippage Tolerance dropdown when adjusting settings for a swap transaction does not present any options

https://user-images.githubusercontent.com/94649004/158485158-dc64a169-b0be-403b-829c-3449725ecce6.mov

**Comment by VladUXUI** [comment]
I think this is because 0x doesn't have this setting? at least that's what my vague memory remembers.

Maybe removing the dropdown and just showing the 1% would help it look less like a bug

**Comment by Shadowfiend** [comment]
Memory is probably remembering an incorrect initial observation on my part. We can def set this!

**Comment by VladUXUI** [comment]
In that case, it would probably be good to do that one 👍 if it's in the easy-peasy category
