### ISSUE TITLE
Swap API request blocked by CORS

### ISSUE THREAD

**Issue by beemeeupnow** [tallycash/extension#1176]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/953677611194794014

### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

Perform in-wallet swap - v0.12.1 in Firefox on Linux

### What did not work?

The API request to fetch the swap price is blocked

### Version

Community Edition v0.12.1

### Relevant log output

```shell
https://gated.api.0x.org/swap/v1/price?sellToken=0x85Eee30c52B0b379b046Fb0F85F4f3Dc3009aFEC&buyToken=0xc18360217d8f7ab5e7c516566761ea12ce7f9d72&gasPrice=22886429577&slippagePercentage=0.01&sellAmount=1000000000000000000&affiliateAddress=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&feeRecipient=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&buyTokenPercentageFee=0.005&takerAddress=[REDACTED]
CORS Missing Allow Origin


Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://gated.api.0x.org/swap/v1/price?sellToken=0x85Eee30c52B0b379b046Fb0F85F4f3Dc3009aFEC&buyToken=0xc18360217d8f7ab5e7c516566761ea12ce7f9d72&gasPrice=22886429577&slippagePercentage=0.01&sellAmount=1000000000000000000&affiliateAddress=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&feeRecipient=0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12&buyTokenPercentageFee=0.005&takerAddress=[REDACTED]. (Reason: CORS request did not succeed). Status code: (null).
```

**Comment by Shadowfiend** [comment]
I'm puzzled because I don't see this… But it may have been an issue with the 0x API's CORS responses.

Def feels like a fat-finger on that one, but I'm also not sure why I'm not seeing CORS issues everywhere… Might be that Firefox Developer Edition doesn't have this issue, but regular builds still do. Either way, going to pop that permission up a level.
