### ISSUE TITLE
Derivation Path - fix size and position of dropdown

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1183]
<img width="386" alt="image" src="https://user-images.githubusercontent.com/80846886/159672214-a4e36988-7784-423e-a449-082fbd8f7181.png">

Was thinking something like this, what i'm trying to fix here is that some users said it's not clear enough that there are more options/can add custom derivation path.

So instead of a scroll-bar maybe hiding half of an item is good enough to let users know there is more to be seen.

I've set this to 140px and it seems to work nicely.

We can revisit moving custom path button to the top later on

**Comment by henryboldi** [comment]
@VladUXUI, got those details sir? 🙇

**Comment by VladUXUI** [comment]
Added details :D
Thank you for the reminder 💖
