### ISSUE TITLE
Importing Wallet with newline delimited recovery phrase does not work

### ISSUE THREAD

**Issue by alleycat0001** [tallycash/extension#1203]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was adding back the Tally chrome extension and trying to import my recovery phrase generated from Tally.

### What did not work?

When I copied down my recovery phrase I put each word on a new line in 1Password. Pasting that `\n` delimited phrase in to the recovery phrase box results in a validation error which was unexpected and freaked me out a little bit!

Taking a look at the code it looks like it expects the phrase to be space delimited.

It might be worth making the parser a little smarter to allow pasting in space or newline delimited phrases.

### Version

Community Edition v0.12.2

**Comment by alleycat0001** [comment]
If this is deemed as worth doing, I can take this on.

**Comment by mhluongo** [comment]
Go for it @alleycat0001!
