### ISSUE TITLE
Stop using .png for icons

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#1223]
### Background

See discussion #1159

We have a lot of icons that are saved as `.png`. We created so far the `SharedIcon` component to simplify icons implementation. Next step would be to convert all icons that are currently `.png` to `.svg` and use them with `SharedIcon` component.

### What needs to be done

- [ ] export all icons that are currently used in the app as svgs - this should be done from Figma (ask @VladUXUI)
- [ ] every usage of `png` icon should be replaced with `SharedIcon` component + `svg` version of given icon

**Comment by VladUXUI** [comment]
@jagodarybacka has a decision been made if we use sprite or single icons?

**Comment by jagodarybacka** [comment]
@VladUXUI yes, I believe so, see linked PR's discussion

**Comment by jagodarybacka** [comment]
@VladUXUI I'm not sure if it was discussed. I would prefer single icons because it will be easier to move from single icon png to single icon svg but we should talk about it with the rest of the team.

**Comment by henryboldi** [comment]
Closed by https://github.com/tallycash/extension/pull/1301
