### ISSUE TITLE
General - Colour styles don't match Figma visually

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1254]
I've noticed some subtle but important differences between the colors in Figma and the colors in the app. Figma looks more fresh and alive...

@VladUXUI can we please ticket these out? It seems like it should be fairly quick to implement.

Here's where I noticed it... image on the left is Figma, image on the right is current test build

**Comment by VladUXUI** [comment]
Yeah. i'm sour about this also. It's basically because Figma use a different colour profile.
Hex codes are all the same.

But this is a good ticket and i'll try to get the hex codes closer to Figma one

**Comment by henryboldi** [comment]
Closed by https://github.com/tallycash/extension/pull/1283
