### ISSUE TITLE
The `To` and `From` assets in the swap menu should be mutually exclusive.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1260]
Users should not be able to select swaps that swap an asset for itself.

<img width="376" alt="image" src="https://user-images.githubusercontent.com/94649004/160425639-43275cb8-8a9b-4011-a2e2-6f6c51ad7c59.png">

**Comment by mhluongo** [comment]
It's yours! :trophy:

**Comment by mhluongo** [comment]
Closed by #1277
