### ISSUE TITLE
Can't send assets to ENS addresses

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1267]
Right now the `Send` page only accepts full addresses in the `Send To` field and keeps the `Send` button grey if an ens address is entered.  It would be great if we could also send directly to ens names.

We will probably want to validate that a given ENS name is valid before allowing the user to click `Send`.

<img width="381" alt="image" src="https://user-images.githubusercontent.com/94649004/160624542-82617332-f1f4-4005-a756-19d55bb1b43c.png">

**Comment by 1saf** [comment]
Will pick this up

**Comment by Shadowfiend** [comment]
I... Am already working on this and should have a PR later today 😅
