### ISSUE TITLE
Using 'swap to' to calculate 'swap from' doesn't work

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1287]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/959293401877069825

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

User report: Using 'swap to' to calculate the corresponding 'swap from' amount needed

### What did not work?

Swap to field doesn't populate, swap from numbers are incorrect. In below example I filled in a 'swap to' of 5.

<img width="390" alt="Screen Shot 2022-04-01 at 19 01 52" src="https://user-images.githubusercontent.com/71384922/161309433-181d494f-48ac-4060-b30e-72eb0de223d8.png">

### Version

Community Edition v0.12.3

**Comment by Shadowfiend** [comment]
Yeah just noticed this today as well. Will try to dig here 👀

**Comment by greg-nagy** [comment]
this works now
