### ISSUE TITLE
Menu - Connected websites

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1290]
Connected websites is a page in the main menu that should allow users to disconnect for any dApp they have previously connected too.

UI Requirements:
 - An item in main menu
 - Show a list of current connected websites of the currently selected account
 - Ability to independently disconnect from each website
 - Show a snackbar after a disconnect to confirm website was disconnected
 
[ Figma link](https://www.figma.com/file/EiXpBpNz2HcoeFJftgC5oc/?node-id=634%3A2366)
 
![image](https://user-images.githubusercontent.com/80846886/161548284-da4d447d-4f6d-41e4-b86b-2cb00d5d0b49.png)

**Comment by 1saf** [comment]
Thanks!

**Comment by 1saf** [comment]
@VladUXUI Is there a spacing system or certain design parameters that you guys use?

**Comment by VladUXUI** [comment]
For spacing and sizes we use a 2px grid. So everything is either 2/4/8/16/24/32px...

**Comment by VladUXUI** [comment]
Did you manage to take a look in Figma?

**Comment by 1saf** [comment]
> Did you manage to take a look in Figma?

Yep I did! I plan to start development this week/end

**Comment by mhluongo** [comment]
@1saf did you ever get anywhere here?
