### ISSUE TITLE
Icons : upgrade PNG to SVG

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1298]
Update png icons and use SVG

- We have two sets of sizes. 16px(s) and 24px(m). We might need 40px(l) in the future
- Some icons have both 16px and 24px version, but they are not the same build/stroke
- These icons should not be used in smaller or larger size than intended

[icons.zip](https://github.com/tallycash/extension/files/8424435/icons.zip)

**Comment by 0xDaedalus** [comment]
Closed by #1301
