### ISSUE TITLE
Gas Control update

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1302]
Upgrading gas control a "little bit" 
Adding a bit more transparency on amount brake-down but also adding custom gas control.
This way users can set their own fees and how much they want to pay.

Because of custom gas, users can set gas lower than current base fee. This should not block a transaction but rather warn them that the transaction fee is less than the current base-fee.

Few things that might not be apparent
- [x] Error + tooltip if gas fee is lower than current base
- [x] If user starts to type in a number in custom field, it should automatically select custom

____________________

**Figma Link** - [Link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/?node-id=1470%3A54326)

____________________

![image](https://user-images.githubusercontent.com/80846886/166417120-e8a6a05b-a42f-466e-95b9-9322b2ef622a.png)

**Comment by SJQuality** [comment]
Can we tell the user what the min Gas is before we give the error. That way they don't have to be in a trial/error scenario trying to figure out what the lowest they can go is? 

Something like this:
![image](https://user-images.githubusercontent.com/103908695/166521870-af16d80e-554a-45f7-97c2-992dc02151ee.png)

**Comment by VladUXUI** [comment]
Showing min gas limit is tricky, as we don't really have that value. For example the min for sending ETH is 21000, but for sending erc20 tokens it's between 25,000 and 150,000 depending on contract, and can go up to 500,000 for more complex contracts.

My initial thinking was to show that error if they go bellow 21,000, but that is also no accurate. As they might think it's ok to use 21,000 for swaps or other complex/expensive contracts.

I think the solution here is to show a different error if they go bellow our estimate. Something like "Change at your own risk" or something less threatening 😅

**Comment by greg-nagy** [comment]
@VladUXUI Is this essentially the same ticket as #1359 ?

**Comment by VladUXUI** [comment]
Yeah, they do seem to be similar. But i'm uncertain if ticket also covers the bugs that are in that tracking ticket?

**Comment by SJQuality** [comment]
@VladUXUI Ah, I see. Maybe "Lower gas may prevent the transaction."

**Comment by henryboldi** [comment]
> - [ ] Changing the content for the gas selector inside pages (Estimated network fee to Max network fee with $ and ETH prices)
        Might feel strange to have Max, but then have ~$. But the eth value will be the max value, and it's important for us to show that you won't pay more than this in ETH.
        
Moving this part into another issue. Closing, although the updates are behind a feature flag!

**Comment by SJQuality** [comment]
@henryboldi can you post a link to the ticket for the $$/ETH here for reference please?

**Comment by henryboldi** [comment]
Ah yes! I believe this one https://github.com/tallycash/extension/issues/1632

**Comment by SJQuality** [comment]
🐛 
https://github.com/tallycash/extension/issues/1643
https://github.com/tallycash/extension/issues/1644
https://github.com/tallycash/extension/issues/1645
