### ISSUE TITLE
Image updates to new colours

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1307]
Added the illustrations i found that had old images(except onboarding)
If any stand out as missing, let me know :)

Made sure they are same size as current images, so hopefully just replacing will be enough

[ImageChanges.zip](https://github.com/tallycash/extension/files/8449728/ImageChanges.zip)

**Comment by rootial** [comment]
I can help update these images. @henryboldi

**Comment by rootial** [comment]
It's updated in #1314 , can you close this issue? @VladUXUI

**Comment by henryboldi** [comment]
Closed by https://github.com/tallycash/extension/pull/1314
