### ISSUE TITLE
UI: No option to recover a 24 word Tally Address (in FireFox)

### ISSUE THREAD

**Issue by ramaruro** [tallycash/extension#1310]
### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

I installed Tally Ho in FireFox. I have an existing Tally generated Wallet using 24 words.
There is no option in the UI that says "Import Tally Ho", only "Import MetaMask".
When I try the Import MetaMask option, it asks for a 12 word phrase, not a 24 word phrase

![image](https://user-images.githubusercontent.com/68167410/162591039-4a59ad0d-06c4-43bf-b085-38885556d817.png)
![image](https://user-images.githubusercontent.com/68167410/162591059-7392057f-6421-458e-8e17-f104b25da277.png)

### What did not work?

I expect an option to recover a Tally Ho generated address, and/or an option to recover a 24 word address.
It should be separate from the "Import MetaMask" option, as that would be very popular on its own I assume.

### Version

Community Edition v0.11.0

**Comment by beemeeupnow** [comment]
was added in a later version than is currently available from the store there

releases here on GitHub now have an xpi in the 'Assets' section if you would like to try that: https://github.com/tallycash/extension/releases/tag/v0.13.0

The current version in the Chrome store is much newer as well for a workaround

**Comment by ramaruro** [comment]
Thanks!
I am only trying Tally in Firefox, as I had an incompatibility with MetaMask prior to this and I couldn't resolve it. 
It looks like the latest version of Tally in FireFox is not the latest available (v0.11 vs v0.13 that you indicated)

**Comment by mhluongo** [comment]
Until the Firefox listing is caught up, maybe give the latest release a shot? You can [download and installed the XPI in Firefox](https://github.com/tallycash/extension/releases/tag/v0.13.0)
