### ISSUE TITLE
Double $$ sign in 'hide balance under menu'

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1322]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/964313297191075850

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

na

### What did not work?

There's a double $$ sign here.
<img width="382" alt="Screen Shot 2022-04-15 at 10 11 12" src="https://user-images.githubusercontent.com/71384922/163544366-dbcbec24-576b-4523-aa72-e3bef1317361.png">

### Version

Community Edition v0.13.0

**Comment by SJQuality** [comment]
Can't repro. Closing.

**Comment by Shadowfiend** [comment]
This was fixed in #1311 I believe.
