### ISSUE TITLE
Password strength bar

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1329]
Using a robust pattern-based tool like https://github.com/dropbox/zxcvbn. Combined with #1328, we'll have a strong mitigation for [cracking encrypted wallets](https://twitter.com/MetaMask/status/1515727239391809536).

**Comment by henryboldi** [comment]
Darn it
<img width="322" alt="password" src="https://user-images.githubusercontent.com/1918798/164275598-cf621411-2009-494a-8068-575041849f7d.png">

**Comment by greg-nagy** [comment]
[Discussion thread](https://www.flowdock.com/app/cardforcoin/tally-product-design/threads/QBUzraGOUwsI_XQgdEi2JBJbdD6)

> Show 1 value for “time to crack” with an (i) I guess to state our assumptions
Show “score” 1/4 as WEAK (1-2), GOOD (3), STRONG(4)
If the user tried to move ahead with the WEAK password, just have it waggle or pulse as feedback


Common understanding
- No hard requirements
- Hinting at the strenght of a password (bar and time to crack)
- messaging/tooltip on how to select a strong password


Just for reference, a design idea for a previous state
![CleanShot 2022-06-17 at 10 31 26](https://user-images.githubusercontent.com/7690112/174259859-98e3a784-1201-4767-8217-b03941b7fce2.png)

**Comment by greg-nagy** [comment]
The scope of this issue for `Sprint 9` is to make a product decision about what to implement.
