### ISSUE TITLE
"Insufficient balance" swap error scrolls outside intended component

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1336]
Pretty sure the design intent is for it to stay anchored to the form element

![Screenshot from 2022-04-19 16-27-04](https://user-images.githubusercontent.com/427505/164090148-f46c3029-e910-42e7-a6bd-eed6fa141486.png)

**Comment by rootial** [comment]
i can't reproduce, can you give more detail on how to reproduce ?

**Comment by henryboldi** [comment]
The error probably needs to be inside a parent with relative position

**Comment by rootial** [comment]
oh i can reproduce it. when i scroll down , the error message positioned in wrong place.

**Comment by rootial** [comment]
https://github.com/tallycash/extension/pull/1341
here we go @henryboldi @mhluongo
