### ISSUE TITLE
Investigate high gas cost for Swap fees

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1337]
Specific fact-finding we can run:

- Estimated vs actual gas fees. How much higher are the estimates? How much higher are the actuals? We should probably choose a handful of asset pairs to do this check + a couple of amount bands to see how larger swaps fare (for Metamask, probably something we can figure out via Dune rather than having to run a bunch of test txes).
- Why are estimates higher/why are actuals higher?
- Potential solutions to the above.

**Comment by mr-michael** [comment]
QA recipes to run through:

- do a swap on Tally with on low priority, recording fx rate + gas quote in gwei and $ every step of the way, save etherscan link
- do the same on MM for the same pair
- “” for med priority at another time of day, for another asset
- “” for high priority at another time of day, for another asset
…

- do some MM swaps at different lot sizes to see how it impacts gas fees

**Comment by henryboldi** [comment]
> The below is the difference between the quoted gas cost and actual gas cost for 3 swaps done on Tally and MM:
Tally        MetaMask
$20.33  $4.63
$43.21  $5.27
$18.67  $6.99
