### ISSUE TITLE
Visual jitter on ENS name lookup 

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1356]
Every character entered into an address field, we do an unnecessary round-trip to attempt to validate an ENS or UNS domain. It's disconcerting, and actually feels like it slows down form entry when you have an unreliable network.

Instead, I think we should hold off on domain resolution until an input value looks like a domain. We should maybe also reconsider the error style or its application to prevent the flashing red/green effect.

Screencast

https://user-images.githubusercontent.com/427505/164954090-f297551e-92ab-45d3-aa51-0733277d97df.mp4

**Comment by Shadowfiend** [comment]
> Instead, I think we should hold off on domain resolution until an input value looks like a domain.

This is not a good strategy. The name service can resolve more than just domain names, I can resolve names like those that may be found in an address book. We should just use a debounce instead.
