### ISSUE TITLE
Broken gas prices (?!)

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1357]
After the [latest BlockNative gas price update](https://www.blocknative.com/blog/base-fee-prediction-and-intelligent-max-fee), we don't need to worry anymore about typical rate limiting issues.

Unfortunately, it looks like the changes to their endpoint aren't backward compatible :grimacing: 

Here's what I see locally

![Screenshot from 2022-04-23 23-13-30](https://user-images.githubusercontent.com/427505/164954897-18b89b15-dc58-47ba-848b-33b0a4cac39d.png)
![Screenshot from 2022-04-23 23-14-22](https://user-images.githubusercontent.com/427505/164954902-9ff6a323-f19e-4f44-9359-19e7e2f6c3be.png)

**Comment by Shadowfiend** [comment]
Huh. We should be falling back in this scenario I thought 🤔

**Comment by mhluongo** [comment]
Okay, I now think this was a local issue based off my work on #1355. Leaving it open until I confirm

**Comment by greg-nagy** [comment]
I think this was a local issue, I did not see this happening nor with or without the multi network flag
