### ISSUE TITLE
Can't see my USDT on Tally I sent there.

### ISSUE THREAD

**Issue by alterkahn** [tallycash/extension#1364]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/968847247292891166

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

[logs_v0_13_1__2022-04-27T15_08_28+03_00.txt](https://github.com/tallycash/extension/files/8571922/logs_v0_13_1__2022-04-27T15_08_28%2B03_00.txt)

### What did not work?

no one wallet page showing the balance

### Version

Community Edition v0.13.1

**Comment by alterkahn** [comment]
https://etherscan.io/address/0x145cd25deac0dcbb827fbca39ac3cbd066e4867e#tokentxns

**Comment by alterkahn** [comment]
I just re-installed the wallet extension and re-imported the seed, but this didn't solve the issue.

**Comment by henryboldi** [comment]
Thank you for the report, @alterkahn!

Of note, I'm seeing a bunch of,
```
AssetDataHelper.getTokenBalances
Problem resolving asset balances via Alchemy helper; network may not support it.,Error: Invalid method parameter(s).
```
in the logs

**Comment by alterkahn** [comment]
> Thank you for the report, @alterkahn!
> 
> Of note, I'm seeing a bunch of
> 
> ```
> AssetDataHelper.getTokenBalances
> Problem resolving asset balances via Alchemy helper; network may not support it.,Error: Invalid method parameter(s).
> ```
> 
> in the logs.

So this is an issue on Alchemy side? Or what should I do? I wanna swap-swap-swap on Tally!

**Comment by mhluongo** [comment]
We're still fact-finding @alterkahn! Hoping to have this settled for next week's release.

@henryboldi I've seen odd `NaN` and `bigint` related things with `getTokenBalances` on other branches, and wasn't able to follow up... I wonder if we're sending a malformed asset list, or if the Alchemy endpoint changed subtly? This certainly isn't happening every balance check, and locally I'm getting good checks for anything in our token list :thinking:

**Comment by alterkahn** [comment]
[logs_v0_13_3__2022-05-07T01_23_52+03_00.txt](https://github.com/tallycash/extension/files/8643855/logs_v0_13_3__2022-05-07T01_23_52%2B03_00.txt)

The extension stopped recording my activity, two latest recordings are missed. It is [KEEP/ETH swap](https://etherscan.io/tx/0xf3691f123e613dc42f094806208c6f7354293ea4b643aefe0a23f5b7aa72c377) and [ETH transfer](https://etherscan.io/tx/0x8e4d033318337a24231f8f38bf2c28bd7102d54d8e4685c76fb38d5dd26fec16) txs.

Also, it doesn't show my total account balance. 

And I would like to see some pop-up notification when any of my tx initiated within Tally is either succeeded or failed.

**Comment by mhluongo** [comment]
Hey, are these separate issues or still related to the USDT balance? If they're unrelated, is this issue resolved? If so we can close this and open new issues.

**Comment by alterkahn** [comment]
> Hey, are these separate issues or still related to the USDT balance? If they're unrelated, is this issue resolved? If so we can close this and open new issues.

these are separate. USDT can be seen and interacted in the latest -v
