### ISSUE TITLE
Swap- Gas Limit should be preset when user edits Gas Limit

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1367]
### **Build Info:**
Build #2881

### **Reproduction Steps:**

1. Perform a Swap action
2. Click "Transaction Settings"
3. Change Gas Limit

### **Expected Result**
Gas limit should have a predefined value. Users should not need to add gas limit
The minimum Gas limit is 21000 and that is reserved for ETH transfers, anything else has higher gas limit

### **Actual Result:**
Gas limit doesn't have a predefined value

Video: https://www.awesomescreenshot.com/video/8607384?key=42958d40417323c90eb355955e27ed21

**Comment by henryboldi** [comment]
Closed by #1428
