### ISSUE TITLE
Swap- Gas: Arrows should change value in increments of 1000

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1369]
**### Build Info:**
Build #2881

**### Reproduction Steps:**

1. Perform a Swap action
2. Click "Transaction Settings"
3. Change Gas Limit

**### Expected Result**
Arrows should change value in increments of 1000

**### Actual Result:**
Arrows change value in increments of 1

Video:
https://www.awesomescreenshot.com/video/8607384?key=42958d40417323c90eb355955e27ed21

**Comment by henryboldi** [comment]
Closed by https://github.com/tallycash/extension/pull/1427
