### ISSUE TITLE
Test Ticket- Failed QA- Has Associated Bug

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1386]
Blah blah blah

**Comment by SJQuality** [comment]
Bug: https://github.com/tallycash/extension/issues/1387#issue-1221487774

**Comment by greg-nagy** [comment]
@SJQuality do you still need this ticket, or can it be closed?

**Comment by SJQuality** [comment]
@greg-nagy This ticket is part of a demo/explanation/proposal that is coming. Not a real ticket.
