### ISSUE TITLE
Ledger-based account unnecessarily require the keyring to be unlocked, even when there's no keyring

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1389]
... even though I've not set a password.

To replicate...

- [ ] Pull from `main`
- [ ] `nvm use && yarn install && yarn start --config-name chrome`
- [ ] Set up an account with a Ledger
- [ ] Wait 30 minutes, then try to sign a message or transaction

The "unlock keyring" page will show up. It can be bypassed by entering an empty string as the password (maybe others as well, unclear).

**Comment by SJQuality** [comment]
I just encountered this. Instead of waiting the 30 min, you can just unplug the Ledger. Keyring unlock comes up, but the user has never entered a PW.
