### ISSUE TITLE
We are making an enormous amount of requests to UNS every ~1 minute

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1430]
It looks like we're trying to look up each character of a given address somewhere.

<img width="1736" alt="image" src="https://user-images.githubusercontent.com/94649004/167907599-e532bd9c-3035-4eda-aa29-7f9719e126fb.png">

**Comment by Shadowfiend** [comment]
I would suspect a "treat a string as an array" type of issue here.
