### ISSUE TITLE
0.13.4- Cannot connect to Ledger

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1434]
### **Build Info:**
Release 0.13.4 - Chrome

### **Related Ticket/PR**

https://github.com/tallycash/extension/pull/1431

### **Reproduction Steps:**

1. Attempt to connect a Ledger

### **Expected Result:**
Connects

### **Actual Result:**
Doesn't connect. No API calls either 

See Video
https://www.awesomescreenshot.com/video/8869914?key=01852620cde9de273ca5bc57553cc520

**Comment by SJQuality** [comment]
So... I just tried on Main.. and Ledger connects fine... So, I went back to the release build.. it now connects fine. So, there must be some other thing going on and this is just a symptom... or worse.. it's intermittent....

**Comment by mhluongo** [comment]
I'm betting it's either...

1. Ledger cable flakiness. This happens surprisingly a lot
2. Multiple Ledgers connected simultaneously... which we might not handle well, though I think we do.
3. Intermittent, which would be my least favorite option

Whenever I hit a Ledger bug, I try in MetaMask in the same browser I'm testing. It's a nice "is this down for everyone or just me?" type test.

**Comment by mhluongo** [comment]
Either way, I think we move this back to triage and unblock the release?

**Comment by SJQuality** [comment]
agreed.

**Comment by greg-nagy** [comment]
Can we reproduce this issue? If not I would like to close this.

**Comment by SJQuality** [comment]
Yeah, we can close

**Comment by SJQuality** [comment]
Yeah, we can close
