### ISSUE TITLE
Full PNL (Profit and Loss) support in wallet

### ISSUE THREAD

**Issue by amitkarpe** [tallycash/extension#1444]
### Discord Discussion Link

NA

### What would you like to be able to do?

Hi,

Can we have a wallet which will calculate and display Profit and Loss in percentage for each blockchain?
e.g. Eth, Polygon, BSC, etc.

**Comment by Shadowfiend** [comment]
Feature requests should start [in Discord](https://discord.gg/hxeQC5wxzf). Please file them as issues only when suggested by a moderator so that issues can be kept organized.
