### ISSUE TITLE
Repeated Websocket connection attempts to blocknative, http requests to alchemy.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1445]
Version: 0.13.3

After opening up and using Tally Ho in a chrome profile that I hadn't used for a couple of weeks (which has the Tally Ho extension installed via chrome store)  - the application felt very sluggish and the following was present in the background page logs:

https://user-images.githubusercontent.com/94649004/168485903-0338c0bb-0548-453d-93ca-7122bdb79a24.mov

https://user-images.githubusercontent.com/94649004/168486090-bf547cdb-3d5b-4294-8665-d99404aebaee.mov

**Comment by greg-nagy** [comment]
@henryboldi I think we might have forgotten to handle the removing of existing bloat from the redux store with a migration. 
I know that we handle this in one place, but the other spots are not cleaned up properly I believe.

What do you think?

**Comment by SJQuality** [comment]
More info:
This was with the extension installed for a couple of days. This build: https://github.com/tallycash/extension/actions/runs/2592048327

https://www.awesomescreenshot.com/video/9833902?key=e683d1d87438a516063b6aac3f9d3667

Also, just from installing the build and doing nothing else (not even opening the extension at all), just waiting, I get this:
![image](https://user-images.githubusercontent.com/103908695/177619208-a4e09733-40a9-4135-8531-6fe284255dd4.png)

**Comment by greg-nagy** [comment]
This is how the issue starts: 

![CleanShot 2022-07-08 at 16 39 32](https://user-images.githubusercontent.com/7690112/178014481-d9035314-2537-4cbe-97ad-9a6f2e03f5e3.png)

Recording: https://www.awesomescreenshot.com/video/9833902?key=e683d1d87438a516063b6aac3f9d3667

**Comment by SJQuality** [comment]
This issue is SEVERLY bogging down the app after about 18 hours or so. I think we underestimate this because we are constantly un/installing the app as we develop and test. Almost everything in the app gets bogged down. Changing accounts, changing chains, clicking on the app on the tool bar,
