### ISSUE TITLE
L2 Spike Week of 5/16/22

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1446]
Broad Goals (Polygon):
- [x] Switching between accounts via header menu correctly changes asset state.
- [x] Swaps working.
- [x] Sends of base asset working.

**Comment by mhluongo** [comment]
> Swaps working.

Ser, ambitious.

Pretty sure swaps need ERC-20 support first, right?

**Comment by 0xDaedalus** [comment]
Displaying ERC-20 - certainly.  But not sending ERC-20.  

Aren't spike tickets supposed to be ambitious? :)
