### ISSUE TITLE
Earn: Move Pool info to accordion

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1452]
Problem
-------
We initially moved pool info to be the first tab as there is important information there.
But Henry brought up a good point that because of the pool info move, the deposit is now hidden a bit. And this is our main CTA.

Solution
-------
Move pool info from Tab to an accordion after pool details. This goes for all the pools

Screenshot
-------
![image](https://user-images.githubusercontent.com/80846886/168549107-28f99738-5e88-4462-abfd-eaae7670ca8a.png)

Figma
-------

**Comment by greg-nagy** [comment]
love the designer touch in this ticker @VladUXUI
