### ISSUE TITLE
We're showing placeholder icons for well-known tokens

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1455]
Related: https://github.com/tallycash/extension/issues/1021

<img width="148" alt="Screen Shot 2022-04-04 at 4 18 08 PM" src="https://user-images.githubusercontent.com/7005061/161660511-b8d8bc79-cb84-45e4-9446-e44f8bdcb3e0.png">

<img width="143" alt="Screen Shot 2022-04-04 at 4 18 44 PM" src="https://user-images.githubusercontent.com/7005061/161660516-97754ff4-6df8-499b-82ed-173fa347cd5a.png">

**Comment by mhluongo** [comment]
We haven't quite closed https://github.com/tallycash/extension/issues/1021, but we've resolved this!
