### ISSUE TITLE
Use Forno instead of Alchemy for Celo support

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#146]
- [ ] Refactor `ChainService` to work with a Celo provider, chainID, and base asset
- [ ] Replace Alchemy-specific transaction calls with less efficient geth event subscriptions
- [ ] Refactor `IndexingService` to work with a Celo provider, replacing token balance shortcuts with manual checks
- [ ] Ensure Celo key derivation works correctly and predictably

**Comment by 0xDaedalus** [comment]
Closing because Celo is not currently on our roadmap.
