### ISSUE TITLE
Custom address field on DAO bonus page

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#1461]
<img width="400" alt="Screen Shot" src="https://user-images.githubusercontent.com/1918798/167690255-0b7654c0-abeb-4178-a130-6937a497a046.png">

**Comment by SJQuality** [comment]
@henryboldi Let me know what feature flag to turn off to see this page.

**Comment by jagodarybacka** [comment]
@SJQuality 
These are all related to claim, earn and referrals, with this setup all these should be working. Let me know if there will be any problems 😄 
```
HIDE_TOKEN_FEATURES=false
HIDE_EARN_PAGE=false
EARN_COMING_SOON=false
USE_MAINNET_FORK=true
```
