### ISSUE TITLE
0.13.4->0.13.5 migration is producing incorrect redux store structure

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1499]
### **Build Info:**
0.13.4 --> 0.13.5

### **Related Ticket/PR**
https://github.com/tallycash/extension/pull/1496

### **Reproduction Steps:**

1. Have 0.13.4 installed
2. Upgrade to 0.13.5 by following these steps - (replacing relevant build versions) https://drive.google.com/file/d/1CnWuFYpcgmpTehbt5f1N1eaoxZyywr5p/view

### **Expected Result:**
0.13.5 works normally

### **Actual Result:**

![image](https://user-images.githubusercontent.com/103908695/169378253-1170e514-9fe7-4eb9-b836-a51dbb5b20c3.png)

https://www.awesomescreenshot.com/video/8995155?key=836c1ffafa780b84c64493e39a782f38
[logs_v0_13_4__2022-05-19T14_52_54-04_00.txt](https://github.com/tallycash/extension/files/8733033/logs_v0_13_4__2022-05-19T14_52_54-04_00.txt)

**Comment by Shadowfiend** [comment]
I flipped the address/chainID association in the accounts slice partway through #1410, but didn't update the migration at that time :untada:

Still thinking about how to prevent this going forward, but in the meantime will fix.

**Comment by SJQuality** [comment]
Verified Fixed
