### ISSUE TITLE
[aggregate] Project setup

### ISSUE THREAD

**Issue by frankiebee** [tallycash/extension#15]
Build system dev: 
- [x] build for chrome 
- [x] live reload

Build system production: 
- [ ] safari
- [ ] chrome 
- [ ] firefox 

Docs:
- [ ] have a loose chart of expected flows and communications
- [ ] doc project layout

Testing:
- [ ] setup testing
- [ ] e2e in browser (work with FED)
- [ ] unit
- [ ] component testing (work with FED)

github actions:
- [ ] prepare prod builds on release branches?

**Comment by mhluongo** [comment]
Closing this out, we've moved from a breadth-first to depth-first production style.
