### ISSUE TITLE
Sending assets sometimes fails and does not prompt for wallet unlock.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1503]
I can only consistently recreate this when MULTI_NETWORK=true but anecdotally I have experienced this from time-to-time when using ethereum and MULTI_NETWORK=false.

To Recreate.

a) Import a wallet
b) Switch to Polygon
c) Click "Update" to update the wallet via chrome://extensions (this locks your keyrings)
d) Attempt to send MATIC (go to page, input amount & address)

The password prompt will not show up and you'll get kicked to the MATIC asset page.

https://user-images.githubusercontent.com/94649004/169531157-1be4cc97-4442-4534-b8ba-4d926f14c323.mov

**Comment by FrankDev34** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.com/) so that your issue can be looked into.

**Comment by 0xDaedalus** [comment]
This is happening because we default to Ethereum as the active network and don't currently persist the user's active network on disk.  This means that on application update - the internal ethereum provider reverts to being connected to the Ethereum network even though the UI indicates being connected to Polygon.  This will be addressed as part of the work involved in #1542

**Comment by 0xDaedalus** [comment]
Closed by https://github.com/tallycash/extension/pull/1609
