### ISSUE TITLE
Use i18next for internationalization

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#1543]
Related issue https://github.com/tallycash/extension/issues/1498
Right now we are using the built-in browser's i18n API but it won't allow us much control over the languages.

### What
Setup and use [i18next](https://www.i18next.com/) instead of built-in i18n module. Currently we have some strings prepared for translation [here](https://github.com/tallycash/extension/tree/main/ui/_locales).
No visual change is expected.

**Comment by gasolin** [comment]
FYI metamask they use built-in i18n module https://github.com/MetaMask/metamask-extension/tree/develop/app/_locales and can still do the lang switch, maybe we can use the similar approach

**Comment by jagodarybacka** [comment]
@gasolin thank you, that's interesting because I was looking for a way to do it as I wrote in the [comment](https://github.com/tallycash/extension/issues/1498#issuecomment-1141061008) without success

**Comment by gasolin** [comment]
seems they roll out their own i18n implementation. Agree to pick i18next might be less effort to maintain the i18n related code
https://github.com/MetaMask/metamask-extension/blob/develop/ui/helpers/utils/i18n-helper.js

**Comment by gasolin** [comment]
will take a look if no one already working on this

**Comment by mhluongo** [comment]
It's all yours!
