### ISSUE TITLE
Add language switcher

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#1544]
Prerequisite: https://github.com/tallycash/extension/issues/1543 is implemented

### What
Add language switcher and allow to switch languages for available translations. Add translations we have created on [weblate](https://hosted.weblate.org/projects/tallycash/extension/).

**Comment by jagodarybacka** [comment]
@VladUXUI this is low prio but at some point we will need some design for the switcher 🎨

**Comment by jagodarybacka** [comment]
@VladUXUI right now we have started working on these
![image](https://user-images.githubusercontent.com/20949277/171129070-fdfa4dbc-8f99-4fbb-8f7d-722eddb09060.png)

**Comment by connerjason** [comment]
Hello team, any way to add a language? I would like to add Spanish and Romanian, if possible. (Probably I could get French as well, but I am weaker there...)

**Comment by connerjason** [comment]
I've added French, Spanish and Romanian

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/172115637-ac2b6c9f-132f-4281-aa01-026bd3a34bdf.png)


Here we go. This uses the same component/design as our Derivation path dropdown from onboarding Ledger.

When we will start adding more (over 10 or so), we will probably need to switch to a pop-over version similar to "select assets" from swap and send

**Comment by VladUXUI** [comment]
If you need me to move these designs to a public figma, just let me know

**Comment by gasolin** [comment]
@VladUXUI how about always put `bug report` as the last item?

**Comment by jagodarybacka** [comment]
Resolved by https://github.com/tallycash/extension/pull/1883
