### ISSUE TITLE
Polygon Popular App Functionality

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1546]
Ensure that we can use polygon to interact with the folllowing applications
- [x] AAVE
  - Connecting ✅ 
  - Supplying ✅ 
  - Approving ✅ 
  - Swapping ✅ 
- [x] Quickswap
  - Connecting ✅ 
  - Approving ✅ 
  - Swapping ✅ 
- [x] Curve
  - Connecting ✅ 
  - Approving ✅ 
  - Swapping ✅ 
- [ ] Meshswap
  - Connecting ✅ 
  - Approving ✅
  - Swapping ✅
- [x] Sushiswap
  - Connecting ✅ 
  - Approving ✅ 
  - Swapping ✅ 
- [ ] Stargate
  - Connecting ❌  (TypeError: n.setSelectedProvider is not a function)
- [x] Uniswap
  - Connecting ✅ 
  - Approving ✅ 
  - Swapping ✅ 
- [x] Qidao
  - Connecting ✅ 
  - Approving ✅ 
  - Depositing ✅ 
- [x] Balancer
  - Connecting ✅ 
  - Approving ✅ 
  - Swapping ✅ 
  - Staking ✅ 
- [x] Beefy Finance
  - Connecting ✅ 
  - Approving ✅ 
  - Depositing ✅ 
- [ ] Opensea

Any Other Suggestions?  What about some popular GameFi Apps?

**Comment by mr-michael** [comment]
We need to add some GameFi and NFT apps to this list and should consult w/Polygon community and our community

**Comment by greg-nagy** [comment]
important dapps on mainnet that are not yet in the list (haven't verified which one of these support polygon yet)

1inch
Maker
Olympus
Liquity
Alchemix
Fei
Convex
Compound
Gnosis
Synthetix
dydx

**Comment by SJQuality** [comment]
Currently verified dApps

https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Supported-dApps-and-Bridges_suavD#_lutnP

**Comment by greg-nagy** [comment]
@0xDaedalus is this good to be closed?

**Comment by 0xDaedalus** [comment]
Stargate works now 👍
