### ISSUE TITLE
Performance improvements

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#1564]

**Comment by henryboldi** [comment]
There's a performance issue is mentioned here: https://github.com/tallycash/extension/issues/1742#issuecomment-1176375994

And discussion in [flowdock](https://www.flowdock.com/app/cardforcoin/tech/threads/tZtrk7Ye89GhvY51NDoXJfpMBUo)

From a cursory look, `getCachedAssets` is merging assets I think twice per call. And `getCachedAssets` is running hundreds of times in unison, particularity noticeable at startup or when adding an address

**Comment by greg-nagy** [comment]
Just a quick notes from my personal list. Not all of these needs to happen though.
The most prominent is floodgate, blocks and json serialization

* try patching BigInt so we don't have to check every property if it's bigint [here](https://github.com/tallycash/extension/blob/831676b8807e61b59a99821f0cc2ba80992b8f3f/background/lib/utils/index.ts#L77)  but use only a simple `JSON.stringify()` (ugly hack, only worth it if the performance gain is significant)
* prune unused data from redux and/or implement paging [flowdock thread] (https://www.flowdock.com/app/cardforcoin/tech/threads/mBOx5TsYPZ6JNqtUg0dJ42cRiJg) (activities, logs, transaction inputs)
* try to mitigate "blocks" event emits firing rapidly in a short period of time 
* finish #1296 to make persisting state reasonable
* check if there is a better way to generate the cachekey for `memoizedMergeAssets`
* rewrite store persistance so it's not persisting data redundantly but grabs what it can from services on startup and only persist the rest

**Comment by greg-nagy** [comment]
Closing in favor of #1350
