### ISSUE TITLE
Handle string message for personal_sign

### ISSUE THREAD

**Issue by beemeeupnow** [tallycash/extension#1573]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/982241852042387517/982257225965928468

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Use `personal_sign` with a human-readable string.

### What did not work?

Different result compared to other wallets.

Other wallets detect when the input is not a hex string and convert to hex (and assume UTF-8 encoding)

One example: https://github.com/cardstack/cardwallet/blob/1c334864dc7fc919cb7bf7a5dc68aaf9c97edb54/cardstack/src/parsers/signing-requests.ts#L216

Another: https://github.com/MetaMask/metamask-extension/blob/43bd885be7e78f24c7edae594d88721b22a02fc9/app/scripts/lib/personal-message-manager.js#L332

web3.js also does the same: https://github.com/ChainSafe/web3.js/blob/63e73bb3f8d4720edcc31441c3b613758ad96cec/packages/web3-core-helpers/src/formatters.js#L227

Personally, I feel that bad input should be rejected as a best practice in programming, but I also didn't see clear 'official' JSON RPC documentation for `personal_sign` indicating this must be hex.
The closest I see is for `eth_sign` which shows hex in examples: https://eth.wiki/json-rpc/API#example-21

Should we give in and perform the same handling, or is there some documentation to enforce the data representation?

### Version

Community Edition v0.13.7

**Comment by beemeeupnow** [comment]
After another issue (#1915) was reported related to this I did some digging and found the problem. We are not behaving properly here.
  
Example page: https://mintkudos.xyz
  
NOTE: You must switch to Polygon on that page. We have some secondary issue where it asks to switch chains, we appear to, but then the signature page shows up blank instead of with the signature approval form!
  
They use [wagmi-dev/wagmi](https://github.com/wagmi-dev/wagmi), specifically the problem scope is the "useSignMessage" function there, which ends up calling signMessage in ethers.
  
ethers then sees that they passed in a string, so encodes it as UTF-8 into a hex string.
  
Then we get this hex string in the wallet side and proceed to eventually pass it on to ethers (again!)
  
ethers sees that it is a string, so then converts the string to a byte array (it literally decodes each individual character, not each byte!)
  
NOTE: This is expected behavior per ethers documentation: https://docs.ethers.io/v5/api/signer/#Signer-signMessage  
See the note there that states: "If message is a string, it is treated as a string and converted to its representation in UTF8 bytes."
  
This means that we need to convert the hex string to bytes (e.g. a number array) before passing it in such cases.
  
I tested with a hacky method (converting inside keyring->personalSign() function) and it worked for this page - I was then able to log in.
  
We need to:

- [ ] Detect that we got a hex string
- [ ] If it is not 64 characters (66 with "0x" prefix), then convert to number array

**Comment by Shadowfiend** [comment]
> will check if it is a hash (e.g. hex string 32-bytes long) and if not a hash will decode the hex as UTF-8 so that the user can see the message the dapp intended for the user to see.

This seems like at best an incomplete heuristic. It feels like the only way to display the message the dapp intended the user to see is to actually display the message the dapp passed. This is why the current code treats the dapp's original input distinctly from the data to be signed--though obviously we missed an additional step with what ethers expected here.

**Comment by beemeeupnow** [comment]
> 
> This seems like at best an incomplete heuristic. It feels like the only way to display the message the dapp intended the user to see is to actually display the message the dapp passed. This is why the current code treats the dapp's original input distinctly from the data to be signed--though obviously we missed an additional step with what ethers expected here.

I agree, but it's infinitely better UX than seeing a long hex string. (especially when other wallets show the text form in this case)

**Comment by Shadowfiend** [comment]
Amazing sleuthing here @beemeupnow. I think with this in mind, the right approach here is to change all of our internal signing plumbing for personal_sign to use byte arrays instead of strings, or hex strings always here:

https://github.com/tallycash/extension/blob/6f28e05527d972842458d7253f00ee50c410a100/background/services/signing/index.ts#L269

https://github.com/tallycash/extension/blob/6f28e05527d972842458d7253f00ee50c410a100/background/utils/signing.ts#L34

Then keyring can use byte arrays for ethers and ledger can do whatever it needs to for the ledger libraries.

**Comment by Shadowfiend** [comment]
Re interpreting as UTF-8, I wonder if it's also worth round tripping the bytes to UTF-8 and back and see if they're the same. I think we can do this without doing extra normalization to the Unicode characters, which should permit us to avoid displaying data that is obviously not meant to be a string. There could still be garbage strings that sneak through, but they'd be less likely. Thoughts?

**Comment by beemeeupnow** [comment]
I like the round-trip check idea.

It would also be possible to validate that the result only contains printable characters (including whitespace as valid, of course)
