### ISSUE TITLE
Spike @ Typeform embed

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1578]
This spike is to see if we feel okay embedding a typeform into our extension (which we can to collect user feedback, etc.). 

Based on this page (https://www.typeform.com/help/a/embed-your-typeform-360029249212/#h_01FKFTT9N3YHW4C6VEWT7R9C48), it looks like we should be able embed it as a 'popover', but I'm not sure how this will work/look in an extension.

This spike is just to add a button that opens up a popover embedded typeform code so we can see how it works out of the box and decide if this is a good way for us to collect feedback from users.

My hope is that this takes well under an hour and we can demo it Friday.

The decision will help determine the scope of this pitch: https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/User-Feedback-Prompts_suuQk#_luI5G

**Comment by greg-nagy** [comment]
Embed SDK vs Custom embed/ iframe: [iframe is not recomended](https://developer.typeform.com/embed/custom-embed/)

Configs: https://developer.typeform.com/embed/configuration/

Conclusion: this will still add an iframe and we will have to work with that limitations. 
It means, that the form can be only customized only as far typeform let's us to do so. 

We might be able to write our custom styles, but I don't think that will work or worth it.

![CleanShot 2022-06-20 at 18 58 17](https://user-images.githubusercontent.com/7690112/174649209-fa4d6d55-fe29-438f-bd0b-6f2022a7981c.png)



# Online demo: 
https://github.com/Typeform/embed-demo - All the demos are opening in codesandbox > it can be tested on the links 
![CleanShot 2022-06-20 at 18 48 47](https://user-images.githubusercontent.com/7690112/174647923-51062d88-50bb-4b86-b977-57f166d98954.gif)


## React widget
https://codesandbox.io/s/github/Typeform/embed-demo/tree/main/demo-nextjs/widget

## React popover
https://codesandbox.io/s/github/Typeform/embed-demo/tree/main/demo-nextjs/popover
![CleanShot 2022-06-20 at 18 48 02](https://user-images.githubusercontent.com/7690112/174647838-2209ad76-1f0c-41ed-9bd7-bde30460dfa7.gif)


## React popup
https://codesandbox.io/s/github/Typeform/embed-demo/tree/main/demo-nextjs/popup
![CleanShot 2022-06-20 at 18 47 29](https://user-images.githubusercontent.com/7690112/174647756-c49e3ea6-cce4-4335-8b1f-402389193a76.gif)


## React sidetab
https://codesandbox.io/s/github/Typeform/embed-demo/tree/main/demo-nextjs/sidetab
![CleanShot 2022-06-20 at 18 46 48](https://user-images.githubusercontent.com/7690112/174647660-0a37b135-eace-4205-bb25-bd85907591e3.gif)


## React slider
https://codesandbox.io/s/github/Typeform/embed-demo/tree/main/demo-nextjs/slider
![CleanShot 2022-06-20 at 18 46 12](https://user-images.githubusercontent.com/7690112/174647570-d4d16d56-6786-4637-bf5b-ea524c15d79b.gif)



# Local demo
![CleanShot 2022-06-20 at 18 41 19](https://user-images.githubusercontent.com/7690112/174647089-a40af5ec-7743-4b76-99d0-b8489a967136.gif)
This needs to be run locally: https://github.com/Typeform/embed
  - yarn remove -W node-sass
  - yarn add -W sass
  - edit webpack.config node-sass > sass
