### ISSUE TITLE
Swaps failing for unknown reason

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1587]
### **Build Info:**
0.13.7 and 0.13.9

### **Reproduction Steps:**

1. Swap
2. add tokens
3. Get quote

I couldn't get this to reproduce. I asked where geographically the user was and they said "China". I tried to connect via VPN to Hong Kong (closet I could get) and I noticed that some of the tokens weren't loading on the "Wallet" page. I deleted/reinstalled Tally and did NOT use my VPN. All of the tokens loaded, but when I tried to Swap, I couldn't get a quote... Maybe something is cached from when the VPN was connected? 

### **Expected Result:**

Quote should be displayed

### **Actual Result:**

Spinner spinning
Discord: https://discord.com/channels/808358975287722045/888500174685614090/983687282768900106

Logs:
[logs_v0_13_7__2022-06-07T13_22_16-04_00.txt](https://github.com/tallycash/extension/files/8855305/logs_v0_13_7__2022-06-07T13_22_16-04_00.txt)

Video: https://www.awesomescreenshot.com/video/9325687?key=1be6bc595b7056043ef79e4ac7838fc4

**Comment by mhluongo** [comment]
Could the 0x API be geo-blocking?

**Comment by greg-nagy** [comment]
> Could the 0x API be geo-blocking?

That was my initial thought, but I don't think that's the case. @SJQuality had the issue without VPN connection and I did not have the issue connecting to Hong Kong VPN. Tried it both with the gated api and the normal. 

Also I saw a proper API response when the bug was present, so my assumption is some weird internal state race condition.

**Comment by greg-nagy** [comment]
So this issue will be related to internal state management in the `Swap.tsx`. We saw a really high CPU usage when it constantly happened, so my 2c is that this created race conditions that we are not handling well. 

The main difference was that for Stephen the code hit [this part](https://github.com/tallycash/extension/blob/71580185b8474e8105ccfcf48ea0d416189875c3/ui/pages/Swap.tsx#L358-369) meanwhile for me it didn't.
