### ISSUE TITLE
PW request on Ledger connected wallet. 

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1593]
### **Build Info:**
Main Build #3357

### **Related Ticket/PR**
https://github.com/tallycash/extension/pull/1562

### **Reproduction Steps:**

1. Have connected Ledger and it be awake
2. Wait enough time that PW request would be initiated if it were needed. I waited about 30 min
3. Attempt a swap

### **Expected Result:**
No PW request

### **Actual Result:**
I received a PW request.

See Video:
https://www.awesomescreenshot.com/video/9349037?key=f9f44eb8f70a15de9d931642c7afe708

**Comment by jagodarybacka** [comment]
Ok, I've waited ~45min without any activity and no password popup on swap attempt 🤔 Restarting browser and reloading the extension work fine too.

**Comment by SJQuality** [comment]
I can't reproduce it on 0.13.10. I must have been looking at the wrong build ( I thought I was sure). Closing this. Will keep an eye out.
