### ISSUE TITLE
0.13.10 Release | MATIC being displayed

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1601]
### **Build Info:**
https://github.com/tallycash/extension/pull/1592

### **Related Ticket/PR/Commit**

https://github.com/tallycash/extension/pull/1592
d8f02039dcecfd57d3e965286d640abb4020cf6b

### **Reproduction Steps:**

1. Login to the app and view the "Wallet page"

### **Expected Result:**
I should not see "MATIC" as it is part of a hidden feature.

### **Actual Result:**

![image](https://user-images.githubusercontent.com/103908695/172891550-7f86bea4-e681-4c53-bc2f-050cb2a05e37.png)

See fFlowdock conversation.
https://www.flowdock.com/app/cardforcoin/temp-tally-qa/threads/SWyu0ChLda7lDJaKwuWlimaugtm

**Comment by greg-nagy** [comment]
this has been fixed in https://github.com/tallycash/extension/pull/1603
