### ISSUE TITLE
Margin disparity between activity and assets tabs

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1612]
![Screenshot from 2022-06-12 18-15-33](https://user-images.githubusercontent.com/427505/173255872-02a4895d-0eee-47b1-859e-dd21c9ea9e23.png)

![Screenshot from 2022-06-12 18-15-43](https://user-images.githubusercontent.com/427505/173255874-6eae8101-92d0-45b0-a6eb-5dfe62e38402.png)

**Comment by mhluongo** [comment]
Here's an example with activity, but not assets

![Screenshot from 2022-06-12 18-33-36](https://user-images.githubusercontent.com/427505/173256293-15cbcf49-500d-484b-893c-c5a46c2e77c8.png)
![Screenshot from 2022-06-12 18-33-29](https://user-images.githubusercontent.com/427505/173256299-557d2908-c024-4f28-9ae9-c510d4596038.png)

**Comment by henryboldi** [comment]
Fixed by https://github.com/tallycash/extension/pull/1620, correct?

**Comment by mhluongo** [comment]
Yep, closed by #1620 :clap:
