### ISSUE TITLE
Switching to Polygon shows activity from Ethereum

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1614]
After flipping on `SUPPORT_POLYGON=true` in `.env`, switching a read-only account from Ethereum to Polygon continues to show Ethereum mainnet activity for Polygon.

![Screenshot from 2022-06-12 18-33-29](https://user-images.githubusercontent.com/427505/173256451-2a4820af-e78e-49c4-9142-c4ecc081d7a3.png)
![Screenshot from 2022-06-12 18-33-36](https://user-images.githubusercontent.com/427505/173256455-8e8f144b-4ec7-4400-8f97-e29dce53a588.png)

It's unclear to me if this is because I flipped the flag on & then refreshed the extension — which is what an upgrade would look like — versus flipping it on before adding the account. Either way, I think this is a bug?

**Comment by Shadowfiend** [comment]
This... Should not be high severity. We aren't shipping this feature yet right? #1534 is tracking bugs that I believe are must-fix before shipping.

**Comment by Shadowfiend** [comment]
Separately--does this not happen no matter what? As far as I can tell, [activities are currently only tracked by address, not network](https://github.com/tallycash/extension/blob/b7e509c1ed22d13d48851c650b78d5963ddae869/background/redux-slices/activities.ts#L42).

**Comment by mhluongo** [comment]
On severity, we've equivocated a bit. My understanding is that "high" currently means a feature or release blocking issue... Clear stakes in the ground would be great.

Regarding reproduction, I just shared how I got there while working on something else. I thought I had seen the proper behavior in demos before, but maybe not.

**Comment by SJQuality** [comment]
@mhluongo want me to put this into the project? I'm not sure it will be seen if it's not. 
![image](https://user-images.githubusercontent.com/103908695/173921579-f4b96d9b-3d91-4ca3-9777-f046c59ff6be.png)

**Comment by mhluongo** [comment]
I've got it, ty ser!
