### ISSUE TITLE
Network switcher not working librewolf and irridium

### ISSUE THREAD

**Issue by waokdalf** [tallycash/extension#1627]
### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

Hello. Thanks for community wallet

v0.13.10

I decided to test it. After all I don't use chrome or firefox browsers. Only their open source forks.
I tried to install tally ho on librewolf browser and irridium browser. Most of extesions work well with these forks.
Network switcher doesn't work in both cases. I have not seen the interface before, but I assume that there may be some other important features missing.

Please pay attention to this. Maybe it's just not the best html layout.
And I see some errors after installation (screenshots attached)
![1](https://user-images.githubusercontent.com/101395860/173847288-f355bb9e-3c49-40d6-b7c6-30ae9715817a.png)
![2](https://user-images.githubusercontent.com/101395860/173847296-8e58c31e-5c88-41bd-892b-fa566c4a56e0.png)
![3](https://user-images.githubusercontent.com/101395860/173847297-f1ec604f-d6e7-459d-afd7-24f600d90a0b.png)

### What did not work?

Network switcher or something else with firefox, chrome forks

### Version

Community Edition v0.13.9

**Comment by mhluongo** [comment]
Hey! There's no network switcher at all unless you flip on the feature flag... only Ethereum mainnet support. Can you try again with `USE_POLYGON=true` in a `.env` file and rebuild?

**Comment by waokdalf** [comment]
Oou, sorry. I understood. I don't build extension from source, I just use ready zip releases.
Waiting for updates. Rays of support for further development

**Comment by mhluongo** [comment]
Should work in the latest release!
