### ISSUE TITLE
yarn start failure due to several type mis assignment issue in various scripts

### ISSUE THREAD

**Issue by dingchaoz** [tallycash/extension#1634]
### What browsers are you seeing the problem on?

Firefox, Chrome, Brave

### What were you trying to do?

Trying to get `yarn start` running to get webpack build running to do a mainnet fork test, my machine is Mac M1, I followed the steps on README on repo https://github.com/tallycash/extension, but getting errors on `yarn start` on various configurations(chrome/ firefox/ brave) 

1. yarn install
2. yarn start

### What did not work?

![image](https://user-images.githubusercontent.com/10751336/173962557-fd0f5953-ee40-4616-9974-abe9262ee375.png)
![image](https://user-images.githubusercontent.com/10751336/173962574-784f6b30-2016-4277-bdd2-2283a64d7774.png)
![image](https://user-images.githubusercontent.com/10751336/173962585-ea8ee0f4-eeec-4ba3-bb68-70599d379d1c.png)
![image](https://user-images.githubusercontent.com/10751336/173962602-6903447b-13e8-4dbd-b29e-377a239b892c.png)

**Comment by mhluongo** [comment]
Hey @dingchaoz, can you confirm whether you ran `nvm use`?

**Comment by dingchaoz** [comment]
Thanks for your quick response, that was the part I missed! after running it , it works fine now.
