### ISSUE TITLE
Jumpstart community contributions

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1650]
There are several relatively simple steps we can take to make it easier for outside developers to get involved in Tally Ho.

I'm listing a few ideas below. Perhaps there are others we can think of suggest as comments?

**GitHub updates**

- [ ] #1674

- https://github.com/tallycash/extension/blob/main/README.md
- https://github.com/tallycash/extension/blob/main/CONTRIBUTING.md

Would it make sense to:

- Add a callout 'good first issue' tag?
- Link to 'shadowy super doggos' in case people have questions?
- Having a project board with ‘good first issues’?
- Open a few other 'nice to have' small features to the community?

**Gitcoin grants**
Reference thread: https://www.flowdock.com/app/cardforcoin/tech/threads/CrdYU2BydZmL_pQONIfQipPAtrS

- [ ] #1675

- NFT portfolio
- WalletConnect
- Sims / txn preview improvements (e.g. https://github.com/tallycash/extension/issues/1234) (needs to be scoped/designed)

- [ ] #1676

Some ideas for making outside contributions more visible:

- Run a 'Bug of the week' process
- Invite outside contributors to speak/share on community calls
- Create processes to regularly solicit outside contributions (and celebrate past contributions!) on Twitter, Discord, blog, newsletter...we've done this a bit, but not consistently

**Comment by gasolin** [comment]
@mr-michael maybe issue a POAP badge for contributors? https://www.gitpoap.io/
