### ISSUE TITLE
Update README and CONTRIBUTING pages for contributors

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#1674]
Add notes for,

- [ ] Check out good first issues  
- [ ] Putting new features behind a feature flag
- [ ]   Focused on layer 2 scaling solutions before other networks
- [ ]   Link to 'shadowy super doggos' in case people have questions
- link to https://tally-ho.upvoty.com/?__force

**Comment by 0xDaedalus** [comment]
Closed By #1706
