### ISSUE TITLE
Update 'Settings' Icon

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1677]
"Main Menu" in page title --> "Settings"

"Menu" in nav --> "Settings"

🍔 icon in nav --> ⚙️  icon

<img width="426" alt="Screen Shot 2022-06-28 at 9 35 28 AM" src="https://user-images.githubusercontent.com/7005061/176192204-9e1d74ee-5122-488b-b805-c61acb62aaa6.png">

**Comment by VladUXUI** [comment]
![menu](https://user-images.githubusercontent.com/80846886/176605009-f917e991-8275-42e1-8fbb-d1ff06db12a7.svg)

New icon for Menu/Settings

**Comment by henryboldi** [comment]
Awesome, thank you @VladUXUI!
