### ISSUE TITLE
Cannot import recovery phrase using new lines

### ISSUE THREAD

**Issue by timjrobinson** [tallycash/extension#1681]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I'm trying to migrate my tally wallet to a new computer using a seed phrase previously generated by Tally Wallet. 

### What did not work?

When I copy and paste the phrase it always says "Must be a 12 or 24 word recovery phrase" even though it is a 24 word phrase. I've tried importing as a list with new lines between each word as well as with spaces between each word.

### Version

Community Edition v0.13.7

**Comment by mhluongo** [comment]
Confirming that all words are in the [BIP-39 English word list](https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt) is also a good idea.

**Comment by timjrobinson** [comment]
Yep exactly 24 words and all words are in that list

**Comment by timjrobinson** [comment]
So it does work if I manually type out each word with a space between each. It's when I copy and paste from my text file (which I think I copy pasted into from tally wallet) that it doesn't work. In the text file every word is on a new line. 

Thinking about it I may have made this text file on a windows machine and importing on linux so maybe it's something to do with `\r\n` vs `\n` newline characters in it.

**Comment by timjrobinson** [comment]
I tried typing out all my words into a new text file with a new line between each and then copy + pasting into tally and that also didn't work. So it seems it's just the new line character in general that's breaking it.

**Comment by henryboldi** [comment]
> I guess it should run a regex to lowercase, convert new lines to spaces, then remove all non a-z or space characters before processing.

Sounds good :)

> So it seems it's just the new line character in general that's breaking it.

Thank you for those details! Updated the title to reflect this is basically about handling new lines.

**Comment by timjrobinson** [comment]
Thanks for the quick fix!
