### ISSUE TITLE
NFT redux slice

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#1691]
## spec 

- let’s start the whole feature by creating a feature flag and putting the redux slice behind it 
- I think we should fetch the NFTs on the user clicking the NFT tab on the overview or accounts tab
  - we shouldn't persist the user being on this screen, so the user will provide us the refetching logic (and we don’t waste resources until needed)
- let’s skip the service part for now  and handle everything in redux + async thunks
- let’s implement a `Cache first, falling back to network` strategy 
  - on the first visit, let’s load the first page from alchemy api and drop it in redux 
  - on the next visit we use the data stored in the redux slice + loading screens until we finish with the refetch
- let’s lazy load the images — this could be a huge resource hog otherwise
  - we can/should use the intersection observer api 
  - we don’t need to worry about image caching because [alchemy is using its own service behind the scenes if it can](https://docs.alchemy.com/alchemy/enhanced-apis/nft-api/nft-api-faq/nft-image-caching) and it’s setting browser caching to 30 days which is neat
    - ipfs also provides caching headers set to 300+ days, so we are probably good in any case
- let’s show only the 1st page (max 100 nfts) in the list (with lazy loading images)
- I wouldn’t implement pagination for the first iteration 
  - but if we want to handle pagination: let’s put a `load more` || `next page` & `pervious page` buttons at the bottom and implement pagination 
    - using generators for this is probably a good idea

- loading states we need 
  - empty state + loading (init request + pagination)
  - prepopulated state + loading 
  - only image is loading 

## Notes
- https://docs.alchemy.com/alchemy/enhanced-apis/nft-api/nft-api-quickstart-guide
  - https://docs.alchemy.com/alchemy/enhanced-apis/nft-api/getnfts + paging

**Comment by SJQuality** [comment]
@henryboldi Lots of ideas here. Can we get a firm list on exactly what this ticket tracks so during testing, we know exactly what is expected to be done?

**Comment by jagodarybacka** [comment]
Redux slice has been implemented, it can be improved later but I think this task has been completed by https://github.com/tallycash/extension/pull/1850
