### ISSUE TITLE
Polygon | Swap/Send - Network fees not estimating. 

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1702]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/pull/1699
https://github.com/tallycash/extension/commit/3fc806af9217480d5025b6b97dfabef4b9a176f8

### **Reproduction Steps:**

1. Be on Polygon Chain
2. Swap or Send

### **Expected Result:**
Network Fees should be displayed and work. 

### **Actual Result:**

![image](https://user-images.githubusercontent.com/103908695/176781042-5a346f66-9957-4c63-9370-8e190683660c.png)

On Eth chain, it works.

**Comment by 0xDaedalus** [comment]
This also affects the new custom gas screen - but only in the fee preview.  The values inside of the fee editor all seem reasonable.

https://user-images.githubusercontent.com/94649004/176974536-8ae64d1b-dfdb-44a1-951c-d103619b13bd.mov

**Comment by henryboldi** [comment]
> This also affects the new custom gas screen - but only in the fee preview.

Fixed in https://github.com/tallycash/extension/pull/1737, correct?

**Comment by SJQuality** [comment]
QA verified fixed
