### ISSUE TITLE
Polygon | Ledger app Polygon- check everything.

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1710]
There are multiple things that aren't working when a Ledger is used and the app on the Ledger being used IS Polygon. We need a developer to use this scenario and work on the following features off the top of my head, as well as anything else that can be thought of.

Ledger using Polygon:
1. Connecting to Tally Ho! with a Polygon Ledger: https://github.com/tallycash/extension/issues/1709
2. While Chain set as Polygon: Send and Swap
3. While Chain set as Ethereum: Send and Swap -> should we send an error? "Please change your Ledger to Ethereum to complete transaction."?

Ledger using Ethereum:
1. While Chain set as Polygon: Send and Swap  -> should we send an error? "Please change your Ledger to Polygon to complete transaction."?

Also, a Ledger user can Switch "Apps" (From Polygon to Ethereum and vice/versa) on the fly. So, these checks need to be made at the time of Ledger confirmation.

**Comment by jagodarybacka** [comment]
Ledger using Polygon
1. ✅  https://github.com/tallycash/extension/pull/1789 - there is no clear way to know which app is opened on Ledger so we can rely on the currently selected network in the wallet
2. ✅  Send and swap work fine
3. ❌ Ledger is silently failing with misleading error (`Please enable Blind signing or Contract data in the Ethereum app Settings` but blind signing is enabled) while signing Ethereum transactions with Polygon app.
Ledger using Ethereum
1. ✅  Swap and send on Polygon network can be signed with Ledger's Ethereum app without any issues

**Comment by VladUXUI** [comment]
@jagodarybacka For the nr. 3, would it be difficult to show the other error that we have?
This one
<img width="978" alt="image" src="https://user-images.githubusercontent.com/80846886/178452212-239b06ad-9c88-4a7f-8d2e-3fa25eb63eb0.png">

**Comment by jagodarybacka** [comment]
There is no way to know if a user has opened Polygon or Ethereum app on the Ledger. I haven't found any documentation on this topic. Most users will use the Ethereum app for signing transactions anyway. Ledger is throwing that error only during signing, on the approval screen everything is working as expected so our current "Connect to Ledger" screen is not helpful. 

Let's follow with https://github.com/tallycash/extension/issues/1798 

I'm closing this task as the rest is working fine.
