### ISSUE TITLE
Adding many addresses causes performance issues

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1711]
### **Build Info/PR/Commit:**
Main
https://github.com/tallycash/extension.git
d219784ff981dfdfc1faf4a785fd8a40d55eb85b

### **Reproduction Steps:**

1. Add multiple addresses. I added about 9

### **Expected Result:**
App should run smoothly. 

### **Actual Result:**
All action in the app are delayed. After click, there is a 1-2 second delay for the response.

**Comment by greg-nagy** [comment]
@SJQuality can you please verify if it's still an issue? I think it should be solved by #1837 and #1838

**Comment by SJQuality** [comment]
@greg-nagy I've checked, and I still see this issue. However, https://github.com/tallycash/extension/issues/1445 is also still an issue... and that may be the cause of this. In other words, this issue may be a symptom of 1445.

**Comment by greg-nagy** [comment]
This should have been fixed by #1875 and #1887 

Our performance is still not the best for many accounts, but the UI is not lagging anymore and I will continue improving it
