### ISSUE TITLE
Not all asset prices are loading

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1712]
On a fresh install & test wallet import

<img width="381" alt="image" src="https://user-images.githubusercontent.com/94649004/176973176-19e6cbb8-8cbd-4dc4-8e9c-50e144031f22.png">

**Comment by SJQuality** [comment]
Still seeing an issue on Ethereum and Polygon
![image](https://user-images.githubusercontent.com/103908695/179295734-57679020-5cf2-43f3-bf10-c63e0484fe6e.png)

![image](https://user-images.githubusercontent.com/103908695/179295773-e5a174f6-e258-4a31-ae8b-f282240e3d80.png)
