### ISSUE TITLE
Some token list fetches are consistently failing

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1714]
URLs may have changed - or schema may have changed.

`logger.ts:165 Error fetching, validating, and saving token list https://gateway.ipfs.io/ipns/tokens.uniswap.org`
`logger.ts:165 Error fetching, validating, and saving token list https://meta.yearn.finance/api/tokens/list`

**Comment by mhluongo** [comment]
Following up with Yearn / Uniswap [here](https://github.com/Uniswap/tokenlists-org/pull/1422)

**Comment by mhluongo** [comment]
Closed by #1777
