### ISSUE TITLE
Duplicate assets in swap asset list

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1715]
<img width="388" alt="image" src="https://user-images.githubusercontent.com/94649004/176974216-572060a3-7f81-4424-9db9-ab123f620a2b.png">

**Comment by 0xDaedalus** [comment]
There's a good chance this was fixed as part of https://github.com/tallycash/extension/pull/1720 but doesn't hurt to double check

**Comment by henryboldi** [comment]
Yes, closed by https://github.com/tallycash/extension/pull/1720
