### ISSUE TITLE
Implement global error screen (to prevent future green screen of death)

### ISSUE THREAD

**Issue by greg0x** [tallycash/extension#1734]
https://github.com/tallycash/extension/pull/1672#issuecomment-1169660695

> Suspecting this is prone to an infinite reload loop

I am using a `setTiimeout()` once, when the UI loads and don't restart it.

Otoh I was thinking about a more robust solution where this check is running continuously. 
With some considerations, eg the restart has been done 2 times then let's show an error screen on 3rd. 

This is something that's called watchdog in electric engineering and is used as a fail-safe in case 
anything goes off.

How would you feel about a solution like this? @henryboldi @Shadowfiend 

This could be the error screen, and the button would reload the whole extension like the refresh button.

![CleanShot 2022-06-29 at 10 00 59](https://user-images.githubusercontent.com/7690112/176384194-861f02c9-060f-49f2-8f66-e0d650757cf3.png)

**Comment by SJQuality** [comment]
Any ideas how to force this screen to appear so it can be tested?
