### ISSUE TITLE
Network fees updating transaction in background late

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#1735]
- changing network fees on transaction approval screen seems to not work correctly
- selecting different option in the selector is not applied after clicking Save button the first time, the second time it seems to work but with different output than expected
- estimated network fee in $ seems to not correlate with the same value we have in ETH 

### Reproduction steps and testing
To illustrate this problem lets work with insufficient funds warning:
1. try to send just a little less ETH than your account balance - we expect that Regular network fee option would fit (spend amount + gas fee < balance) but Instant option won't pass
2. on tx approval screen by default there should be Regular option selected
3. open network fees selector and change to Instant option, save it

**Currently**: No warning, Estimated network fee in $ doesn't change
**Expected**: Insufficient funds warning should appear, Estimated network fee in $ + spend amount > ETH account balance

**Note**: if you change again to Regular option it is now displaying warning and Estimated fee is changed 🤔 

https://user-images.githubusercontent.com/20949277/177354168-0c598bf2-3c35-4ae2-9e50-bf59d8df36e6.mov

**Comment by henryboldi** [comment]
I believe https://github.com/tallycash/extension/pull/1550 wasn't updated for the background side of things

**Comment by henryboldi** [comment]
>  Estimated network fee in $ doesn't change

I'm not seeing this part as an issue
