### ISSUE TITLE
The latest Uniswap token list doesn't validate

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1740]
They've added `extensions` that appear to be causing an issue with our schema.

**Comment by SJQuality** [comment]
Hey @mhluongo is this issue causing these missing tokens in our app?
![image](https://user-images.githubusercontent.com/103908695/177853020-3dbcd1ed-f7f5-4778-8688-170f06644703.png)

**Comment by mhluongo** [comment]
I believe so!
