### ISSUE TITLE
Token icons don't always show up in activity feed

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1742]
<img width="391" alt="image" src="https://user-images.githubusercontent.com/94649004/177548869-17a2f249-94ad-4493-871c-e75c4bb34324.png">

Note USDC and WETH.  These icons do still show up in the asset list / swap page.

**Comment by mhluongo** [comment]
It's worse than this I think — they're also inconsistent across the overview and wallet page, and will resolve for a while and then "unresolve", going from a full image to nothing. It's frustrating as hell.

I think the asset merging code is the culprit. The `tokenReducer` appears to take ~50% of our CPU time in lay performance testing

**Comment by greg-nagy** [comment]
should be fixed with #1837 and #1838
