### ISSUE TITLE
Polygon | Gnosis Safe - Only connect to Ethereum, No way to switch to Polygon

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1747]
### **Build Info/PR/Commit:**

https://github.com/tallycash/extension/tree/polygon-qa-2

### **Reproduction Steps:**

1.  Nav to https://gnosis-safe.io/app/welcome
2. Attempt to connect Tally on Polygon
AND/OR
2. Connect via Ethereum (successfully) 
3. Switch to Polygon

### **Expected Result:**
The user should be able to switch from one chain to another either by switching in Gnosis Safe's UI or by Tally Ho!'s UI. 

### **Actual Result:**
Can only connect to Ethereum

https://www.awesomescreenshot.com/video/9835072?key=423171003c4abfd076087c8f0d3c3b99

**Comment by 0xDaedalus** [comment]
I think the best fix here is to ask gnosis to enable Tally as an option when connecting to Polygon.  They currently only support Metamask and WalletConnect as options

**Comment by SJQuality** [comment]
Gnosis Safe deployed their fix. Verified it works now.
