### ISSUE TITLE
Can't connect to Convex

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1751]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/tree/polygon-qa-2

### **Reproduction Steps:**

1. Nav to https://www.convexfinance.com/
2. Be on Polygon Chain
3. Connect Wallet
4. choose Injected
5. Complete process

### **Expected Result:**
Should be able to connect

### **Actual Result:**
The first time, it seemed that the connect process started. I verified in Tally, then nothing. Then on subsequent attempts, nothing happens at all.

**Comment by 0xDaedalus** [comment]
I think you want to use "Injected Wallets" rather than Metamask.  Everything seems to work fine for me if I do that.  Can you confirm that that path works?

<img width="182" alt="image" src="https://user-images.githubusercontent.com/94649004/177646070-dcc8b472-28ee-4051-ad1a-bc7166f3029e.png">

**Comment by SJQuality** [comment]
... not sure how I missed that..

**Comment by SJQuality** [comment]
Closing because Convex is Eth only.
