### ISSUE TITLE
Monitor token balances on networks that don't have Alchemy assetTransfer support

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#177]
Currently, that includes [Arbitrum](https://docs.alchemy.com/alchemy/documentation/apis/arbitrum), [Optimism](https://docs.alchemy.com/alchemy/documentation/apis/optimism-api), and [Polygon](https://docs.alchemy.com/alchemy/documentation/apis/polygon-api)

**Comment by 0xDaedalus** [comment]
Closed by https://github.com/tallycash/extension/pull/2423
