### ISSUE TITLE
Do we need to indicate fess are in MATIC on Polygon sends?

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1771]
Not sure :)

Maybe we could put a "MATIC" (and later "OP") after "Transaction fee" these places. It feels off to not display it anywhere.

Could be "Estimated Network fee" --> "Est. Network fee (MATIC/ETH)" or "Estimated MATIC/ETH fee"

<img width="375" alt="Screen Shot 2022-07-07 at 9 51 01 PM" src="https://user-images.githubusercontent.com/7005061/177900656-1645d273-0440-4807-9d35-34a460e4f56a.png">

<img width="390" alt="Screen Shot 2022-07-07 at 9 51 09 PM" src="https://user-images.githubusercontent.com/7005061/177900657-9cd87f5c-c81a-48e5-85d5-22791d61e2b6.png">

<img width="369" alt="Screen Shot 2022-07-07 at 9 51 29 PM" src="https://user-images.githubusercontent.com/7005061/177900659-24d915b5-8bde-4286-932f-572b923d82ca.png">

<img width="378" alt="Screen Shot 2022-07-07 at 9 51 36 PM" src="https://user-images.githubusercontent.com/7005061/177900661-3779ac3a-33e7-4896-a407-90a2e9f045b2.png">

<img width="397" alt="Screen Shot 2022-07-07 at 9 51 48 PM" src="https://user-images.githubusercontent.com/7005061/177900664-acae0bf2-5075-4f77-8f33-82451fd3ab2e.png">

<img width="379" alt="Screen Shot 2022-07-07 at 9 52 00 PM" src="https://user-images.githubusercontent.com/7005061/177900692-219fea5a-0a58-4052-be9f-b989b6aa58ce.png">

<img width="413" alt="Screen Shot 2022-07-07 at 9 51 56 PM" src="https://user-images.githubusercontent.com/7005061/177900693-9a0a1501-2ad7-4a83-93b6-2c8d9e80792f.png">

**Comment by mr-michael** [comment]
<img width="421" alt="Screen Shot 2022-07-07 at 10 12 46 PM" src="https://user-images.githubusercontent.com/7005061/177902921-9c5ebbd8-59f0-4a24-939d-be901c5ba078.png">
<img width="441" alt="Screen Shot 2022-07-07 at 10 12 36 PM" src="https://user-images.githubusercontent.com/7005061/177902927-7a4b0517-3824-4de5-8cdd-db3105cdd550.png">
<img width="386" alt="Screen Shot 2022-07-07 at 10 12 33 PM" src="https://user-images.githubusercontent.com/7005061/177902933-654c152f-ddda-490a-ab7d-98e6be144393.png">

**Comment by VladUXUI** [comment]
I don't think it's necessary, we don't show fees in ETH Or Matic anywhere. Users know that if they are on Polygon they are not going to pay fees in ETH.
We have a global selector for network, and this should be enough for users to know that everything is switched to that network.
If we start adding Matic in some places, it might cause more confusion. As user might wonder if for example asset is sent on Polygon or Ethereum. 

I would vote to leave it as is for now, and reconsider on a later date if user feedback says it's confusing

**Comment by mhluongo** [comment]
> I would vote to leave it as is for now, and reconsider on a later date if user feedback says it's confusing

Same, closing as `wontfix`
