### ISSUE TITLE
Connecting to Uniswap with Tally Ho always goes to MetaMask

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#1780]
Building `main` on Chromium `103.0.5060.53` connecting to Uniswap with MM installed and Tally Ho's "set as default wallet" enabled, Uniswap still connects to MetaMask

![Screenshot from 2022-07-10 16-36-21](https://user-images.githubusercontent.com/427505/178161363-46f40e69-b517-460b-9fa8-bdf3ec514cfb.png)

Disabling MetaMask leads to an infinite pulse in the Uniswap UI, without anything indicative of an issue in the console.

**Comment by mhluongo** [comment]
> Disabling MetaMask leads to an infinite pulse in the Uniswap UI, without anything indicative of an issue in the console.

This is no longer true as of my testing today — commit `18ee0d0d362f977cef177349f35ecef1da2fea0b`

**Comment by greg-nagy** [comment]
fixed (mostly) with #1807 

The solution is not 100% as it tends to lack behind when heavy cpu usage is happening in the extension
