### ISSUE TITLE
Is it okay to display "$0.00" in fees on Polygon?

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1781]
Send https://polygonscan.com/tx/0xaa81bb2e13fd670d708f99ab1b19992a30e249fb3370701ba7913ea91b231ae9

Swap https://polygonscan.com/tx/0xc3141d9750158d35b662790567e106ba08b900982446f201c397536a5282483a 

Sends and Swaps on Polygon are less than $.01 ... this is awesome clearly :), however our UI displays that fees are "$0.00" which looks a bit buggy. Wondering how we can fix?

<img width="391" alt="Screen Shot 2022-07-10 at 9 58 02 PM" src="https://user-images.githubusercontent.com/7005061/178176093-828fa0b1-4d39-4cde-bd11-71b038a64242.png">

<img width="385" alt="Screen Shot 2022-07-10 at 9 55 57 PM" src="https://user-images.githubusercontent.com/7005061/178176095-6ede1555-e8c3-4329-8c1d-5b8d020f2356.png">

<img width="390" alt="Screen Shot 2022-07-10 at 9 58 21 PM" src="https://user-images.githubusercontent.com/7005061/178176087-0e9fe853-e334-402c-baa2-8930a12e7eb8.png">

<img width="394" alt="Screen Shot 2022-07-10 at 9 58 13 PM" src="https://user-images.githubusercontent.com/7005061/178176088-e838e4da-224b-400e-ad42-4239ba97d920.png">

<img width="377" alt="Screen Shot 2022-07-10 at 9 56 10 PM" src="https://user-images.githubusercontent.com/7005061/178176089-a28e1421-77a8-409c-a0e4-fd53c2f0eb63.png">

<img width="377" alt="Screen Shot 2022-07-10 at 9 56 16 PM" src="https://user-images.githubusercontent.com/7005061/178176091-84e7e419-958d-4450-a5df-6c6186eb0212.png">

**Comment by VladUXUI** [comment]
First off, we should remove network fees from everywhere except tx screens.
Second, if it's under $0.01 do users really care? But showing a >$0.00 would help make it seem less like a bug.

IMO (and this is bias as f), we don't need network fees or network fee selector for polygon.

**Comment by VladUXUI** [comment]
0 Gwei seems like a bug tho'

**Comment by 0xDaedalus** [comment]
This issue is stale - current visuals look like this:

<img width="375" alt="image" src="https://user-images.githubusercontent.com/94649004/178364792-3d586aff-e9b5-4018-a893-8ca9de6ad01f.png">

**Comment by mhluongo** [comment]
Closing as stale!
