### ISSUE TITLE
Not able to connect to Uniswap

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1782]
I'm no longer able to connect to uniswap (on any network) with either Tally or MetaMask. When I disable Tally as default, 'injected' still shows as top wallet option

<img width="591" alt="Screen Shot 2022-07-10 at 10 19 14 PM" src="https://user-images.githubusercontent.com/7005061/178176657-03d7c898-2fd3-4b4f-866d-da301aa7b95a.png">

<img width="563" alt="Screen Shot 2022-07-10 at 10 19 16 PM" src="https://user-images.githubusercontent.com/7005061/178176655-efb6b87e-84ad-4ed2-8458-2da0d00d43a8.png">

**Comment by SJQuality** [comment]
@mr-michael I am able to use Uniswap with no problem with latest Polygon QA build https://github.com/tallycash/extension/actions/runs/2644867029

Can you try again with that one?

**Comment by 0xDaedalus** [comment]
Closed b/c issue was found on a stale branch
