### ISSUE TITLE
AAVE - "Please switch to Polygon POS."

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1784]
When I attempt to withdraw on AAVE, I get a "Please switch to Polygon POS" and do not appear to be able to connect to Polygon.

https://user-images.githubusercontent.com/7005061/178179194-efacb6fc-8d02-438f-bd0d-c035d078c42e.mov

**Comment by 0xDaedalus** [comment]
Closed because tested against stale branch

https://user-images.githubusercontent.com/94649004/178297213-3ab2ebef-e2e4-4c10-b13f-e108018feec2.mov
