### ISSUE TITLE
Correctly display token decimals on approval activities

### ISSUE THREAD

**Issue by alterkahn** [tallycash/extension#1786]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Approve exact KEEP tokens amount and swap

### What did not work?

I was swapping and approving the exact amount of KEEP tokens, and noticed that the amount is reflected in not convenient manner

<img width="385" alt="Снимок экрана 2022-07-11 в 15 46 12" src="https://user-images.githubusercontent.com/67752860/178268160-ef6a2ad2-ff4e-402d-87dd-abb9d27eab01.png">

Also when I swap I would like the wallet automatically bring me to the "activity" page after I sign the tx, so that I could see what is happening and not to switch to 'activity' manually.

And I would like this suggestion to be implemented, it would be very convenient for executing swaps: https://github.com/tallycash/extension/issues/1407

### Version

Community Edition v0.13.13

**Comment by jagodarybacka** [comment]
> Also when I swap I would like the wallet automatically bring me to the "activity" page after I sign the tx

Great suggestion, we will implement it ➡️  #1765

**Comment by alterkahn** [comment]
> > Also when I swap I would like the wallet automatically bring me to the "activity" page after I sign the tx
> 
> Great suggestion, we will implement it ➡️ #1765

this isn't implemented yet, while the issue was closed as completed

**Comment by jagodarybacka** [comment]
@alterkahn That's because "automatically bring me to the "activity" page after I sign the tx" part will be implemented as a part of https://github.com/tallycash/extension/issues/1765 because it is not directly connected to the overflowing text on activity card 😃 Don't worry the other one is still open, we won't forget about it

**Comment by alterkahn** [comment]
I'm having this again on `Version 0.17.18f2bb7b`

<img width="407" alt="Снимок экрана 2022-10-14 в 15 10 36" src="https://user-images.githubusercontent.com/67752860/195843906-9a4f2cce-e15c-4b77-b7af-29e408790b91.png">

**Comment by jagodarybacka** [comment]
@alterkahn I think it is correct behaviour - nothing is overflowing as it did before, we show as much text as we can so token name is in the second line. If you hover your mouse over the number it will show full text.

**Comment by alterkahn** [comment]
> @alterkahn I think it is correct behaviour - nothing is overflowing as it did before, we show as much text as we can so token name is in the second line. If you hover your mouse over the number it will show full text.

these spaces and absence of coma are confusing a bit

**Comment by jagodarybacka** [comment]
@alterkahn oh you are right, this number is formatted differently than others in the app, will fix
