### ISSUE TITLE
Polygon | Meshswap - Meshswap doesn't know I'm on Polygon Network

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1791]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/actions/runs/2644867029

Commit e92547440157a088570509dd474642c2e1a712f2

### **Reproduction Steps:**

1. Polygon Chain
2. Connect Wallet

### **Expected Result:**
Meshswap should be able to see my tokens and I should be able to swap.

### **Actual Result:**

Wallet now connects. However, Meshswap doesn't think I'm on the correct network. 

![image](https://user-images.githubusercontent.com/103908695/178349018-d8ab6917-5fa4-4591-91b8-05ef65b7eede.png)

**Comment by greg-nagy** [comment]
Just a note, that this behavior is identical to MM. You can click the wrong network and switch to polygon and it fixes the issue. 

Although we are working on something neat, to make this better :)

**Comment by SJQuality** [comment]
fixed
