### ISSUE TITLE
Read-only marked as a Tally Ho account

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#1799]
<img width="330" alt="read-only" src="https://user-images.githubusercontent.com/1918798/178534891-a0771d3d-fc6b-4ca1-8580-5909dd964e77.png">

**Comment by 0xDaedalus** [comment]
Regression introduced in https://github.com/tallycash/extension/commit/669c84561b581d9a3884dd2a09d35a625cb1a098

**Comment by mhluongo** [comment]
Sorry guys, not sure how I missed this 🤦‍♂️

**Comment by 0xDaedalus** [comment]
no blame - only 📈 !
