### ISSUE TITLE
Read Only Mode- Remove links to Swap/Send/Receive 

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#1813]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/actions/runs/2664045824 

### **Reproduction Steps:**

1.  Enter a Read Only Address

### **Expected Result:**
Read Only Addresses should not allow trades or swaps.

### **Actual Result:**

![image](https://user-images.githubusercontent.com/103908695/178788297-0ea405e1-740d-4445-9e82-1245e22ec971.png)

**Comment by henryboldi** [comment]
For context, I think the idea is to let users down a flow where they'll want to import that account. In the sense that, hey, all ya' need to do now to complete this send is to import its phrase. That said, the "upsell" flow here doesn't exist. In other words, there's no convenient way to import the phrase to continue

**Comment by SJQuality** [comment]
Yeah. If we were to leave the buttons there, but when clicked, a pop-up that said "This is a Read-Only account, click HERE to fully import the account." That leads them down the Import path would be a nice flow.

**Comment by mr-michael** [comment]
Suggestion:

- Add 'read only' label to Send and Swaps page
- Display 'Continue' and 'Get final quote' buttons on both pages, but leave disabled

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/181040494-59e5a177-4616-4dcf-93bc-d84f984688bf.png)

Discussed with Jagoda, let's go with this for now. But we need a better long term solution at some point
