### ISSUE TITLE
Update network name on the 'QR code receive' screen to selected network

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1821]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Copy my receive address on Poylgon

### What did not work?

UI indicates that it has to be an Ethereum address

Version: 0.13.13_0dc5dff

<img width="365" alt="Screen Shot 2022-07-14 at 08 59 14" src="https://user-images.githubusercontent.com/71384922/178921428-a7cf4346-bedd-4d18-819c-d7a50e318fc8.png">

### Version

Community Edition v0.13.13

**Comment by henryboldi** [comment]
Great catch!
