### ISSUE TITLE
Browser crashes unexpectedly when extension active

### ISSUE THREAD

**Issue by lennardevertz** [tallycash/extension#1833]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/998867279867551804

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Just surfing.

### What did not work?

When the current version of Tally (0.14.0) is activated, my browser crashes unexpectedly. This continues to happen, until I deactivate the extension on brave://extensions/. It happens randomly, even when I don't touch my laptop and the wallet is not open. Sometimes after a few minutes, sometimes it is stable for around 30 mins. 
It also happened with some of the previous versions.

### Version

Community Edition v0.14.0

### Relevant log output

```shell
Still looking...
```
Any ideas which logs I could post here?

**Comment by greg-nagy** [comment]
fixed with #1838 and #1837
