### ISSUE TITLE
Make `SYMBOL_PRIORITY_LIST` network aware in `prioritizedAssetAlphabeticSorter`

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#1847]
Currently priority assets eg. KEEP is also listed on polygon, even though the token itself is not deployed on that network

https://github.com/tallycash/extension/blob/831676b8807e61b59a99821f0cc2ba80992b8f3f/ui/components/Shared/SharedAssetInput.tsx#L59

This causes issues with 0x quotes.

**Comment by 0xDaedalus** [comment]
This no longer seems to be an issue 👍 

I'm unable to get network-specific assets to display on a network they don't belong to - and the KEEP token is in fact deployed on `Polygon` - https://polygonscan.com/address/0x42f37A1296b2981F7C3cAcEd84c5096b2Eb0C72C
