### ISSUE TITLE
NFT Upgrades

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#1856]
Testing QA build from 28th Jul

- [x] Outside links
Right now we are using the token format (https://etherscan.io/token/0xa7ee407497b2aeb43580cabe2b04026b5419d1dc?a=3200)
Would like to change this to NFT view. Link structure is a bit different
https://etherscan.io/nft/0xa7ee407497b2aeb43580cabe2b04026b5419d1dc/3200
   

- [x] NFTs cut out 
Some NFT get cut out on full screen. Uncertain if we can fix this without scroll? But making the full NFT visible would be nice
     
<img width="354" alt="image" src="https://user-images.githubusercontent.com/80846886/181452680-59e94fc3-d7f2-4c6b-b46f-db7822d8e6f0.png">

- [x] Image padding/margins
Left/right + bottom padding/margin should be the same
<img width="93" alt="image" src="https://user-images.githubusercontent.com/80846886/181453050-1ab49dee-83ed-4ba1-adb1-993a275e25fd.png">

- [x] External link mouse over
Mouse over for eternal link icon should be trophy gold instead of white

**Comment by jagodarybacka** [comment]
@VladUXUI Polygonscan doesn't have that nice NFT view, should we use old link schema for Polygoscan or do we want to use other website 
cc @mr-michael

**Comment by VladUXUI** [comment]
Let's go with old view for Polyscan.
Thank you Jagoda!

**Comment by jagodarybacka** [comment]
Resolved by https://github.com/tallycash/extension/pull/1850
