### ISSUE TITLE
Add price impact & warning for in-wallet swaps

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1863]
### Discord Discussion Link

na

### What would you like to be able to do?

Add a price impact indicator for in-wallet swaps, and a warning in case it's high.

Example from Matcha:

<img width="401" alt="Screen Shot 2022-07-31 at 08 27 28" src="https://user-images.githubusercontent.com/71384922/182013218-8767a61e-532a-40f0-bc63-679b9b8cf343.png">

**Comment by VladUXUI** [comment]
<img width="1791" alt="image" src="https://user-images.githubusercontent.com/80846886/188375135-079659cc-b501-49a8-a27d-e944b990f40c.png">

Voila!
I don't think a warning is necessary now as this is visible enough, we can rethink it during the swap redesign.
