### ISSUE TITLE
Read-only address disappears when switching to Polygon

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1864]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Switch between read-only accounts on mainnet and Polygon

### What did not work?

One read only address is can only be selected as an address when the extension is on mainnet. When switching to Polygon it's no longer on the list. This was also the first read only address that was added. The balance of this address is still included in the overview page though.

The other two read only addresses that were added after that, are in the list both when the extension is on mainnet and on Polygon.

Side note. All of these 3 addresses were added through an ENS or UD. These domain names are loaded when the extension is on mainnet but not when it is on Polygon.

### Version

Community Edition v0.14.1

**Comment by jagodarybacka** [comment]
Fixed by https://github.com/tallycash/extension/pull/2087
