### ISSUE TITLE
NFT viewing - duplicate numbering

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1868]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View NFT's

### What did not work?

Version: https://github.com/tallycash/extension/actions?query=branch%3ANFT-view-QA

Double numbering
<img width="353" alt="Screen Shot 2022-08-01 at 15 20 09" src="https://user-images.githubusercontent.com/71384922/182157734-ec59d363-c838-4f92-848c-9abbc395a653.png">

### Version

Community Edition v0.14.1

**Comment by jagodarybacka** [comment]
addressed in https://github.com/tallycash/extension/pull/1861 will close this if this PR will make it to main
