### ISSUE TITLE
WMATIC balance not displayed after a swap to

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1871]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap MATIC to WMATIC on Polygon

### What did not work?

The swap transactions are completed
Swap transaction 1: https://polygonscan.com/tx/0xba3578d14b6e5141ecdd803fa1e5b325b8e84aeff08fb1bd36ea39a3d52e894b
Swap transaction 2: https://polygonscan.com/tx/0xd8fde558f132a0d4bfc2fc6f4bb45be86ec2684cc1abcee5604326aaee0bef88

The WMATIC balance isn't displayed in the wallet and not on Polygonscan, but is displayed on another explorer and in MM.
6 WMATIC shown on oklink though: https://www.oklink.com/en/polygon/address/0x77f6e4ea32f0b807dcaaddbec9dabe0131614cd5

Logs:
[logs_v0_14_1__2022-08-02T12_38_53+02_00.txt](https://github.com/tallycash/extension/files/9241402/logs_v0_14_1__2022-08-02T12_38_53%2B02_00.txt)

### Version

Community Edition v0.14.1

**Comment by Naxsun** [comment]
This also applies for users that swap ETH to WETH. WETH isn't showing in the wallet.

**Comment by VladUXUI** [comment]
Wrapping doesn't seem to register, swapping from tokens to WMatic does
Related to https://github.com/tallycash/extension/issues/2121
