### ISSUE TITLE
USDC not displayed as a swap to option on Polygon

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1872]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1003735710567764078

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap to USDC on Polygon

### What did not work?

User 1: Could not select USDC in the 'swap to' list
User 1 Logs:
[logs_v0_14_1__2022-08-01T13_01_38-04_00.txt](https://github.com/tallycash/extension/files/9241421/logs_v0_14_1__2022-08-01T13_01_38-04_00.txt)

User 2: Could not select USDC in the 'swap to' list. User 2 does have a USDC balance in this wallet on Polygon, and can select it in the 'swap from' dropdown.

Then using the 'flip' button results in an error that the user does not have sufficient USDC. Although he's trying to swap to USDC.

User 2 Logs: 
[logs_v0_14_1__2022-08-02T12_44_31+02_00.txt](https://github.com/tallycash/extension/files/9241441/logs_v0_14_1__2022-08-02T12_44_31%2B02_00.txt)

<img width="383" alt="Screen Shot 2022-08-02 at 12 42 04" src="https://user-images.githubusercontent.com/71384922/182356203-7359a159-2115-4967-a411-87a16e78f3cd.png">

<img width="386" alt="Screen Shot 2022-08-02 at 12 42 21" src="https://user-images.githubusercontent.com/71384922/182356185-bd4333ea-02e9-4572-8335-880cee2300d4.png">

<img width="390" alt="Screen Shot 2022-08-02 at 12 43 37" src="https://user-images.githubusercontent.com/71384922/182356390-142a7d21-da3e-4674-8c83-2b1209786d36.png">

### Version

Community Edition v0.14.1

**Comment by mhluongo** [comment]
Closed by #2181
