### ISSUE TITLE
DAI balance not updated

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1876]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1004047844468084806

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

See the DAI balance

### What did not work?

User swapped DAI into ETH
Transaction hash: 0xf641405493af11485cd010bdf35d3d5d0114b61e14b80a5eff9e7bb6fd1f0390  

Then send this ETH to his Metamask wallet
Tansaction hash: 0x959fc4923bcc5d096611de71a351d8dd21429ed7c661b1ff30efe12e617183f4 

But the wallet is still displaying the DAI balance (before the succesful swap to ETH).

When the user tries to to swap from DAI and taps 'get final quote' the request is sent and an animated loader is shown but it keeps spinning.

Logs:
[logs_v0_14_1__2022-08-02T22_34_2703_00.txt](https://github.com/tallycash/extension/files/9249629/logs_v0_14_1__2022-08-02T22_34_2703_00.txt)

![image](https://user-images.githubusercontent.com/71384922/182567015-a243635a-ca64-4905-a1e6-b84459959985.png)

![image](https://user-images.githubusercontent.com/71384922/182567059-e25f898c-b51d-45b6-bbf1-b82eb25924e6.png)

### Version

Community Edition v0.14.1

**Comment by mhluongo** [comment]
This should be resolved! Re-open if you see it again :pray:
