### ISSUE TITLE
Refactor activities slice to reduce redux store size

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#1885]
- [x] initialize from indexeddb on startup
- [x]  limit the activities in the redux store to 25/network + prune older activities
  - [x]  update activities reducer to not allow more than 25 activity in redux per address per network
- [x] strip all data from activities that are not needed for the activities list view 
- [x] load details data on demand + prune current detail data
- [x] ActivityItem type fix

**Comment by VladUXUI** [comment]
Uncertain if these goes here, but adding design for prosperity
[Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=12112%3A210508)

<img width="406" alt="image" src="https://user-images.githubusercontent.com/80846886/183026757-71dcde69-6414-4366-92d0-3b1955e9db12.png">

**Comment by mhluongo** [comment]
Can we also get an "infinite scroll" version @VladUXUI?

Paginating in the store is a great performance hack, but limiting *all* activities in the wallet to 50 is a big product change.

**Comment by jagodarybacka** [comment]
Created follow-up tasks. A major refactor has been finished so these minor improvements can be done later.
https://github.com/tallycash/extension/issues/2414
https://github.com/tallycash/extension/issues/2413
