### ISSUE TITLE
Green screen when wanting to SIWE while extension is on Polygon

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1895]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Trying to connect to Zilly.social

### What did not work?

Extension can connect while it was on Polygon but then attempting to SIWE gives a green screen. When switching to Ethereum it then works as in I can sign the message.

The option 'Sign in with Ethereum' remains displayed on the dapp though.

[logs_v0_14_2__2022-08-07T08_42_15+02_00.txt](https://github.com/tallycash/extension/files/9276309/logs_v0_14_2__2022-08-07T08_42_15%2B02_00.txt)

Screen recording & logs:

https://user-images.githubusercontent.com/71384922/183278686-459064e0-f8e2-4011-9635-c18c37420d7a.mov

 

### Version

Community Edition v0.14.2

**Comment by beemeeupnow** [comment]
We also have a similar issue going the other direction.

For example, https://mintkudos.xyz expects Polygon. If you have Ethereum selected in the extension, you will end up with a blank green screen instead of the signature approval page.
