### ISSUE TITLE
Separate tab for Achievements

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#1906]
This ticket is to determine level of effort and best way to accomplish the following:

On the overview tab and wallet tab, add a separate "OATs" tab to the right of "NFTs". This should *always* display on the Overview tab.  On the Wallet tab, it should only display when your network is Polygon.

OATs are basically Polygon NFTs, so this *should* hopefully be as simple as filtering our existing NFT list so that Galaxy NFTs only show up in the "OATs" tab (not the "NFT" tab)

More info on OATS
- docs - https://docs.galaxy.eco/developer/
- Example 1 - https://polygonscan.com/tx/0xd9c8df62870bf93cfd2e71eff8a6a025f347585c9b589664bd484305888b0779
- Example 2 - https://polygonscan.com/tx/0xf0ec507910c6af1c4d9227a4fafee4336841832c0d14c76839aebb8e4708cb98

**Comment by greg-nagy** [comment]
We can simply filter for the contract address https://polygonscan.com/token/0x1871464f087db27823cff66aa88599aa4815ae95?a=0xb360737602ec015072c4cc42314eae13d6ef2642 and display them in a new tab

**Comment by mr-michael** [comment]
This is awesome. We can hang tight for now. Will follow up as soon as things are clear on the biz side.

**Comment by mr-michael** [comment]
@mhluongo this isn't about a separate overview tab for activities! :)

**Comment by jagodarybacka** [comment]
Resolved by https://github.com/tallycash/extension/pull/2286
