### ISSUE TITLE
Add network to the transaction sign screen

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1909]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap on Polygon while the Extension is on Ethereum and also connected to a dapp on Ethereum.

### What did not work?

Swap works, but the transaction sign doesn't show the network I'm signing a transaction for.

Below screenshot on Uniswap - Polygon was when the extension was on Ethereum.

<img width="1791" alt="Screen Shot 2022-08-09 at 10 18 44" src="https://user-images.githubusercontent.com/71384922/183600338-c65bc232-4e3d-410f-86ef-1a39c21be5ba.png">

**Comment by jagodarybacka** [comment]
Figma design:
<img width="431" alt="image" src="https://user-images.githubusercontent.com/20949277/183604385-f3cb8645-6676-45f2-aa72-a4a3d40d7fe4.png">

**Comment by mhluongo** [comment]
Duplicates #1794
