### ISSUE TITLE
SIWE not working

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1915]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Sign in with Ethereum on login.xyz & mintkudos.xyz

### What did not work?

Sign in with Ethereum doesn't work. 

Dev feedback from mintkudos side: _"The 401 error is caused by the fact that the signature verification isn't working for the Tally wallet specifically. We use ethers.utils.verifyMessage to verify the signature against the login message, and the verification is invalid for signatures generated by the Tally wallet it seems.

Essentially we want the user to sign a message to login and then we verify in the backend to make sure that it was signed by the particular account. For some reason the Tally wallet shows the message to be signed in hex? Not sure if this is the reason but it's never been a problem with any other wallet providers that we've tested with!"_

With login.xyz can't connect at all. I've tested an older wallet version, 0.13.13, and there it still works. Screenshot of the sign message there below.

![image](https://user-images.githubusercontent.com/71384922/183853249-450cb325-e3bc-4939-be4f-99c300b9ab6b.png)

### Version

Community Edition v0.14.3

**Comment by beemeeupnow** [comment]
If there is a problem with SIWE, it is different from the problem with mintkudos.xyz (which is not using SIWE)
  
The problem with minukudos.xyz is the problem I reported in issue #1573

**Comment by Shadowfiend** [comment]
I'm somewhat sure the problem is either the same or extremely similar, as SIWE also uses personal_sign and is sending a plain string.
