### ISSUE TITLE
Regression - Adding an address to one network does not add it to all networks

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1940]
Adding an address while having the `Ethereum` network selected does not seem to add it to the `Polygon` list of addresses.

https://user-images.githubusercontent.com/94649004/184449956-1d50a39a-2d70-423e-a6d0-017143ec9881.mov

**Comment by mhluongo** [comment]
Also hate that account name change

**Comment by jagodarybacka** [comment]
> Also hate that account name change
that's second regression 😬

**Comment by 0xDaedalus** [comment]
This is no longer an issue 👍
