### ISSUE TITLE
Using Ledger with Trezor Seed Phrase / Derivation Path does not recognize Accounts 2+

### ISSUE THREAD

**Issue by ramaruro** [tallycash/extension#1943]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I have a Ledger using a Trezor Recovery Seed Phrase (I'm guessing Ledger and Trezor use a different derivation path)

When connecting that Ledger to Tally, it recognizes the first Account, but the second+ are all different to the ones I use with Trezor, or even as they are recognized in the Ledger Live App.

This happens using the Ledger Derivation Path:
![image](https://user-images.githubusercontent.com/68167410/184515522-9317c68e-03a6-4069-a0c0-b4081f0ee831.png)

As I ask to change the derivation path to "Trezor m/44'/61'/0'/0), it sends me back to the "Check your Ledger" screen
![image](https://user-images.githubusercontent.com/68167410/184515531-ddccf3d4-4cee-4988-a3ad-56df675b71f8.png)
![image](https://user-images.githubusercontent.com/68167410/184515547-7a5d48be-dd17-4cbb-bed0-b32bd5ce2cca.png)

I'm stuck in this loop, unable to access the second Trezor generated address

### What did not work?

Accessing the Trezor derivation path using a Ledger

This happens in Version: 0.14.3_72cdb16

### Version

Community Edition v0.14.3

**Comment by mhluongo** [comment]
Giving this a look!

**Comment by mhluongo** [comment]
@ramaruro can you try "Use custom derivation path" with the path `m/44'/60'/0'/0` and see if you get what you're expecting?

**Comment by ramaruro** [comment]
Thanks, let me try later this afternoon and I'll report back!

**Comment by mhluongo** [comment]
Or just click "Ethereum". Pretty sure this is the BIP44 path, and the Trezor option is mislabelled.

**Comment by ramaruro** [comment]
This path worked: m/44'/60'/0'/0 

This path shows up for "Ethereum", I did not have to use custom
