### ISSUE TITLE
Add Optimism and Arbitrum with 'coming soon' to the network dropdown

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1951]
### Discord Discussion Link

na

### What would you like to be able to do?

Add Optimism and Arbitrum as non-clickable options tot he drop down, with a 'coming soon' indicator.  

Discussed this with @mr-michael and he's on-board as well.

<img width="385" alt="Screen Shot 2022-08-15 at 09 06 19" src="https://user-images.githubusercontent.com/71384922/184591209-15fd8187-294a-4e2a-907e-7e666ee51879.png">

**Comment by mr-michael** [comment]
Can use find graphics for OP and Arbi here from https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=10821%3A162568

Order:

Ethereum
**Mainnet**

Polygon
**L2 scaling solution**

Optimism
**Coming soon**

Arbitrum
**Coming soon**
