### ISSUE TITLE
User can not set-up a password & new wallet

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1952]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1008400537760321597

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

User tries to set-up a new wallet

### What did not work?

The user can use the extension in read-only mode. However, when trying to create a new account and setting up a password for the extension, the user gets an 'Unexpected error' screen. 

Logs: [logs_v0_14_3__2022-08-14T18_42_3303_00.txt](https://github.com/tallycash/extension/files/9336363/logs_v0_14_3__2022-08-14T18_42_3303_00.txt)

![image](https://user-images.githubusercontent.com/71384922/184612568-2ef758d8-4df6-48b5-9cb3-b30487c82040.png)

![image](https://user-images.githubusercontent.com/71384922/184612537-0fca87db-e8bb-4e47-b747-cd15fd509712.png)

### Version

Community Edition v0.14.3

**Comment by Shadowfiend** [comment]
Unfortunately the logs here are mostly connection problems (looks like there's an issue connecting to Alchemy for this user) and don't include any errors around the password setup...

I wonder if this points to a different approach to expiring logs, where we expire each log level independently and then reinterpolate them by timing when we export...

**Comment by Naxsun** [comment]
Would it help to set-up a live session / chat with this user?

**Comment by Naxsun** [comment]
@Shadowfiend don't know if there's anything new in there but the user just shared a new set of logs
[logs_v0_14_5__2022-08-24T22_06_3803_00.txt](https://github.com/tallycash/extension/files/9418838/logs_v0_14_5__2022-08-24T22_06_3803_00.txt)
.

**Comment by mhluongo** [comment]
Closing as stale / could not reproduce
