### ISSUE TITLE
Pending transactions

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#1959]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1008245782417264713

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

User 1 - Ortex - was trying to swap assets
User 2 - memeco - was trying to interact with a contract

### What did not work?
User 1 - Ortex:
https://discord.com/channels/808358975287722045/888500174685614090/1008245782417264713
Transactions remained pending, not actually broadcasted.
Logs:
[logs_v0_14_3__2022-08-14T09_59_4104_30.txt](https://github.com/tallycash/extension/files/9348184/logs_v0_14_3__2022-08-14T09_59_4104_30.txt)
![image](https://user-images.githubusercontent.com/71384922/184807412-edcffc3b-8fbe-426a-96e5-a71c70d47d92.png)

User 2 memeco: 
https://discord.com/channels/808358975287722045/888500174685614090/1007992957816811530
![image](https://user-images.githubusercontent.com/71384922/184807671-b28f38cf-537d-4cbc-9962-d7dbba97b681.png)

### Version

Community Edition v0.14.3

**Comment by jagodarybacka** [comment]
Should be fixed by https://github.com/tallycash/extension/pull/2130
