### ISSUE TITLE
Enormous amount of background requests to UNS name resolution

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#1967]
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/94649004/184991411-4be0e2f1-f1c0-4c2e-a232-ec6802b91e40.png">

~200k of these messages in half an hour of monitoring.

I'm guessing we're still looking up names somewhere we shouldn't be - probably when we get a batch of new blocks.

**Comment by Shadowfiend** [comment]
`0x2105dc7…` -> is this abbreviation done by the console or are we getting real weird in what we're sending here?

**Comment by 0xDaedalus** [comment]
just a console abbreviation - full URL is available in the `networks` tab

**Comment by hyphenized** [comment]
I'm looking into this, it seems we're requesting enrichment for accounts related transactions that are coming from our request to get asset transfers through Alchemy's WebSocket connection. So I think @0xDaedalus is correct 👀. I'm working on a fix

**Comment by Shadowfiend** [comment]
That is actually correct behavior--but we should probably queue enrichment for older transactions while fast-pathing signature requests.

**Comment by 0xDaedalus** [comment]
Closed by https://github.com/tallycash/extension/pull/2068
