### ISSUE TITLE
Gwei gas prices are not updating live on Optimism

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2000]
They are initially populated but do not update when price updates

**Comment by 0xDaedalus** [comment]
Blocked by https://github.com/tallycash/extension/pull/1973

**Comment by mhluongo** [comment]
Closed by #1973

**Comment by 0xDaedalus** [comment]
Not quite closed yet - #1973 gives us the $ amount - not the gwei amount
