### ISSUE TITLE
Transaction signing getting stuck after clicking Sign

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2019]
Happening when a user is attempting to swap assets - anecdotally I have seen this a few times while on airplane wifi so may be related to connection or internet speed.

https://discord.com/channels/808358975287722045/888500174685614090/1012333218483159080

![image](https://user-images.githubusercontent.com/94649004/186663607-fc844d67-1864-4b12-a3c7-9369a4a03cef.png)

**Comment by jagodarybacka** [comment]
I believe we already fixed it with nonce and sign button fixes
