### ISSUE TITLE
Connecting TH to Polygon POS not working with Ledger and Polygon Network

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#2037]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/pull/2024

### **Reproduction Steps:**
(See Video)
1.  Have Ledger Connected, Have Polygon set as Network in TH
2. Attempt to Connect TH to Polygon POS

### **Expected Result:**

Connection Success

### **Actual Result:**
TH Closes, kinda thinks it's connected, but not really. Ledger Never gets the Sign.

https://www.awesomescreenshot.com/video/10734953?key=fb3551b6476beddf0159fd66c378bf76

**Comment by beemeeupnow** [comment]
still the same with version 15.0 ?
wondering if this was fixed by #1980

**Comment by kkosiorowska** [comment]
@beemeeupnow 

> still the same with version 15.0 ? wondering if this was fixed by #1980

I tested this and is still not working.
