### ISSUE TITLE
Not able to set-up transactions, sign button pending

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2051]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1012806821704126504

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up a transaction

### What did not work?

User Naresh:
The sign button doesn't appear, keeps loading.
![20220827_010422](https://user-images.githubusercontent.com/71384922/187073262-f4b814d2-6e07-4211-80b4-0f6e796bc0a5.jpg)

Logs:
[logs_tally_users Naresh.txt](https://github.com/tallycash/extension/files/9439598/logs_tally_users.Naresh.txt)

User KiRa - No logs received yet
https://discord.com/channels/808358975287722045/888500174685614090/1013094258615533650
![image](https://user-images.githubusercontent.com/71384922/187073208-627c1e4a-b8da-4ec8-bd8d-a238ac5abefc.png)

### Version

Community Edition v0.14.7

**Comment by Naxsun** [comment]
User Iyonger. Can not set-up a transaction at Across bridge while wanting to bridge Polygon to Ethereum.
https://discord.com/channels/808358975287722045/888500174685614090/1013373332449677392

User reported steps:
1.https://across.to/
2.from polygon 
3.to ethereum 
4.send 
5.tally popup , and I click  sign 
6.stuck at here 
result : transfer unsuccessful(no transactions)

Logs:
[Logs_user_iyonger.txt](https://github.com/tallycash/extension/files/9439613/Logs_user_iyonger.txt)

**Comment by Naxsun** [comment]
User lamina appears to have the same issue: https://discord.com/channels/808358975287722045/888500174685614090/1013405468258996325
![image](https://user-images.githubusercontent.com/71384922/187073733-27301987-eeaa-4f0f-b6b6-30e07942a34a.png)

**Comment by Naxsun** [comment]
User jbsingh001: https://discord.com/channels/808358975287722045/888500174685614090/1015112616005357568
[logs_v0_15_0__2022-09-02T09_43_5405_30.txt](https://github.com/tallycash/extension/files/9487569/logs_v0_15_0__2022-09-02T09_43_5405_30.txt)

**Comment by Naxsun** [comment]
User hodling: https://discord.com/channels/808358975287722045/888500174685614090/1015542581742010459

**Comment by Naxsun** [comment]
User ZTQIFEI: https://discord.com/channels/808358975287722045/888500174685614090/1015817736586264656
[logs_v0_15_0__2022-09-05T01_42_0808_00.txt](https://github.com/tallycash/extension/files/9487591/logs_v0_15_0__2022-09-05T01_42_0808_00.txt)

**Comment by Naxsun** [comment]
User Zero4771: https://discord.com/channels/808358975287722045/888500174685614090/1015860279860543500

**Comment by Naxsun** [comment]
User ezajasjssa: https://discord.com/channels/808358975287722045/888500174685614090/1015878869343023124

**Comment by Naxsun** [comment]
User LLLA: https://discord.com/channels/808358975287722045/888500174685614090/1015878869343023124

**Comment by Naxsun** [comment]
Successfully reproduced, logs:
[logs_v0_15_0__2022-09-04T21_55_51+02_00.txt](https://github.com/tallycash/extension/files/9487696/logs_v0_15_0__2022-09-04T21_55_51%2B02_00.txt)

**Comment by Naxsun** [comment]
User shafjazz: https://discord.com/channels/808358975287722045/888500174685614090/1016210142603264121

**Comment by Naxsun** [comment]
User ILLA: https://discord.com/channels/808358975287722045/888500174685614090/1016086337448857700

**Comment by Naxsun** [comment]
User Mayy: https://discord.com/channels/808358975287722045/888500174685614090/1015091439987855380

**Comment by VladUXUI** [comment]
Spinning wheel seems to show up more frequently when changing gas settings.
