### ISSUE TITLE
Matic balance on Polygon not updating

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2052]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1013412813718437898

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View matic balance

### What did not work?

User Kuya: "I send 2 MATIC to my Tally wallet as transaction gas，the chain shows that it has been received. But I cann't see it in my Tally wallet, and I didn't set “Hide asset balances under $2”"

![image](https://user-images.githubusercontent.com/71384922/187073624-ceba5f5c-4e49-4af6-94fd-4e05161461ca.png)

![image](https://user-images.githubusercontent.com/71384922/187073633-636eca9e-470c-44ad-b3af-f770648beabb.png)

![image](https://user-images.githubusercontent.com/71384922/187073649-96bca7d3-fad8-4166-ba33-0ee5c93651c0.png)
![image](https://user-images.githubusercontent.com/71384922/187073656-25be7898-c8c9-4a51-b6b2-73ec291137d8.png)

### Version

Community Edition v0.14.7

**Comment by Naxsun** [comment]
User Eliakhan11: https://discord.com/channels/808358975287722045/888500174685614090/1016238794623696908
Both MATIC and USDC balance are not displayed. USDC incoming TX: 0x33baa63bf0e6780eaa37ed044fd0347131054403b286f3f1f8e76e0488253ed1

Version 0.15.0
Logs:
[logs_v0_15_0__2022-09-05T11_47_1405_00 (1).txt](https://github.com/tallycash/extension/files/9487774/logs_v0_15_0__2022-09-05T11_47_1405_00.1.txt)

**Comment by 0xDaedalus** [comment]
Searching for error `-32602` in alchemy shows that the extension is getting into a state where its sending `alchemy_getAssetTransfer` requests with a `toAddress` of `0x`:

```
{
  "method": "alchemy_getAssetTransfers",
  "params": [
    {
      "fromBlock": "0x1f2b592",
      "toBlock": "0x1f4a992",
      "maxCount": "0x3e8",
      "order": "desc",
      "toAddress": "0x",
      "category": ["external", "erc20"]
    }
  ],
  "id": 2227,
  "jsonrpc": "2.0"
}

```

Unclear yet how exactly we're getting into this state but based on the above logs it looks like this could be the cause here.

**Comment by 0xDaedalus** [comment]
This seems to have been resolved
