### ISSUE TITLE
Make default accounts names and avatars more random

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#2075]
Let's try to avoid cases where multiple accounts added in a row have the same default account names and avatars as this is not looking UX friendly.
![image](https://user-images.githubusercontent.com/20949277/187451678-e7254364-5ba1-4b8b-8025-7c57bc49fe88.png)

**Comment by Shadowfiend** [comment]
Two in a row is straight up a bug, fwiw—I believe we try to avoid reusing any names until we've used all of them; it's possible something about multi-network is making it a little weird though. We also don't have a *lot* of entropy here.
