### ISSUE TITLE
Unknown network on Sign Permit

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#2076]
### What

The unknown network is showing on Sign Permit message popup. Let's see if we can derive the network.

### Steps to reproduce

- go to Uniswap
- find a ERC20 token that you haven't allowed Uniswap to use
- try to approve token spend

![image](https://user-images.githubusercontent.com/20949277/187452402-921d25e7-c1a7-4694-b894-aee214b3fda9.png)

**Comment by 0xDaedalus** [comment]
Seems to be resolved ✅
