### ISSUE TITLE
MATIC (ERC-20) is showing up before ETH on the Ethereum wallet page

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#2084]
![Screenshot from 2022-08-30 12-34-12](https://user-images.githubusercontent.com/427505/187491654-afee4e11-2785-4867-ab2e-90a99e92dd16.png)

Seems like we're considering the MATIC ERC-20 a base asset when we shouldn't be.

**Comment by hyphenized** [comment]
Should MATIC be considered a base asset when using the polygon network?
https://github.com/hyphenized/tally-cash/blob/0ff853e4c31031fe766863b6664539e5fa147b14/background/constants/currencies.ts#L66

**Comment by jagodarybacka** [comment]
@hyphenized It should, why do you think it shouldn't be?

**Comment by hyphenized** [comment]
@jagodarybacka I don't, I'm just trying to understand what's the expected behaviour. So I guess we have to take into account the current network when sorting assets, is that correct? 👀

**Comment by jagodarybacka** [comment]
@hyphenized yes, you are correct 😄
