### ISSUE TITLE
Consider a prompt for users to set Tally Ho as the default wallet

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#2085]
> Been thinking about this a bit more, and i think we run the risk of going to hard on the other side, if people don't know how to disable Tally as default, they won't know how to enable it as default. So i propose we add this bar for when Tally is disabled.
> It's safe to assume that if it's disabled people don't actively use it for transactions or maybe don't even do too much in it. So it shouldn't be too much of a user friction to have the bar there.
> 
> If enabled, the bar should disappear in 10 seconds or so. Giving user a bit of time to disable back
>
> <img width="2108" alt="image" src="https://user-images.githubusercontent.com/80846886/187387635-d8897302-cebc-4bca-ac0d-17a6e29db25c.png">
>
> What do you all think?

_Originally posted by @VladUXUI in https://github.com/tallycash/extension/issues/2026#issuecomment-1231330412_

### Figma link 
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=12524%3A214935

### Requirements

- [ ] Add banner with Toggle button
- [ ] Change content of banner on enable
- [ ] Hide banner after 5 seconds of enabling
- [ ] If disable toggle is clicked back off in those 5 seconds, leave banner there
- [ ] Banner should be always visible if TallyHo is not set as default

**Comment by VladUXUI** [comment]
Given this feature, and the fact that is off by default, i wonder if we should remove the toggle from onboarding entirely?
Would give users less cognitive load and make it cleaner

**Comment by VladUXUI** [comment]
Adding a gif to this flow for clarity
![CleanShot 2022-09-30 at 10 52 07](https://user-images.githubusercontent.com/80846886/193220514-ee4b925d-45eb-46f9-8859-59c2121df129.gif)

**Comment by mr-michael** [comment]
@jagodarybacka quick note that we just updated figma to include a toast
