### ISSUE TITLE
Activity List Broken for Users that have approved a token prior to `0.15.0`

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2091]
### To Recreate
- Load a new wallet on version `0.14.7`
- Approve a token you have not previously approved before
- Upgrade to version `0.15.0`
- Open the Activity Page.

### Why is this happening
[`spenderAddress` and `spenderName` were replaced with `sender` ](https://github.com/tallycash/extension/commit/ad5519d25841546d977d8c1c197c8ff3b73fe870#diff-0effdeeeba712d998d5baa16729996bd8cc9cc6815a2cb278994a6a76ffac716L270)without a redux migration.

Writing a truly compatible migration would need to rely on ENS name resolution inside the migration which seems a bit 📉 .  Wondering what the 80/20 is here.  Perhaps mark spender as an optional property in the types and update dependent code until we can come up with a more robust solution?

**Comment by mhluongo** [comment]
I... feel obligated to fix this if no one else has snagged it.

WDYT about migrated `spenderAddress` and `spenderName` with an `AddressOnNetwork` for `sender`? We could also maybe use `spenderName` to build `sender.nameOnNetwork`...

Meta: I'd very much like to add a testing harness around Redux migrations and start adding test data from all of our old versions. Getting to a test for this particular migration would be a good start.

**Comment by 0xDaedalus** [comment]
I think we'll need all of the `spender.annotation` fields or at least an as-best-as-we-can-fill annotation or we're just kicking the can down the road where we are further removed from `0.15.0`.

**Comment by Naxsun** [comment]
Another user with the same issue, but on Polygon.
https://discord.com/channels/808358975287722045/888500174685614090/1014800185383194676
![image](https://user-images.githubusercontent.com/71384922/187881137-42710321-4b0c-4f32-b302-90c738cc51ca.png)

[tally.txt](https://github.com/tallycash/extension/files/9468650/tally.txt)

**Comment by Naxsun** [comment]
I have this issue myself as well. 

With a Ledger account that I imported yesterday when the extension was on 0.14.7. The extension itself for this case was already installed for ~3-4 weeks. Some of the earlier imported accounts have the same issue.
