### ISSUE TITLE
Can not set-up transactions on Polygon

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2106]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1015282104562626623

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up transactions

### What did not work?

Transactions remain pending, don't show up on Polygonscan. The user disabled the extension and re-enabled it, re-started the browser in between, but the pending transactions remained.

_"ChainService.retrieveTransaction
Error retrieving transaction [REDACTED]
    at ChainService.retrieveTransaction (chrome-extension://eajafomhmkipbjmfmhebemolkcicgfmd/background.js:59334:24) "_

Logs: [logs_v0_15_0__2022-09-02T18_36_2403_00.txt](https://github.com/tallycash/extension/files/9479454/logs_v0_15_0__2022-09-02T18_36_2403_00.txt)

![image](https://user-images.githubusercontent.com/71384922/188193136-a40d4d6d-4570-4582-a9f6-0ebb83fd01d9.png)

### Version

v0.15.0

**Comment by Naxsun** [comment]
Same issue:
https://discord.com/channels/808358975287722045/888500174685614090/1015375728067494028

**Comment by Naxsun** [comment]
User LLLA: https://discord.com/channels/808358975287722045/888500174685614090/1016096095497097307

**Comment by Naxsun** [comment]
User YoZero: https://discord.com/channels/808358975287722045/888500174685614090/1016248533650780170

**Comment by Naxsun** [comment]
Successfully reproduced, logs:
[logs_v0_15_0__2022-09-04T21_55_51+02_00.txt](https://github.com/tallycash/extension/files/9487688/logs_v0_15_0__2022-09-04T21_55_51%2B02_00.txt)

**Comment by VladUXUI** [comment]
Issue seems to be from Gas being set too low

**Comment by Naxsun** [comment]
Was able to reproduce this. The pending transactions can be a result of a skipped nonce. A skipped nonce can be created by a dropped transaction.

To reproduce:
- Make an in-wallet swap on Polygon, set the custom gas low. E.g. Miner 1 and Max Base: 1
--> Dropped transaction
- Set-up another transaction, send or swap, but with ok / suggested gas settings
- The new transaction will be pending, because the dropped transaction did update the nonce

<img width="368" alt="Screen Shot 2022-09-05 at 11 46 52" src="https://user-images.githubusercontent.com/71384922/188420598-911a263a-3556-493f-96a7-cc11446660ee.png">

<img width="375" alt="Screen Shot 2022-09-05 at 11 47 00" src="https://user-images.githubusercontent.com/71384922/188420614-84446692-70fb-4fa9-9341-2a50148a6067.png">

<img width="375" alt="Screen Shot 2022-09-05 at 11 47 08" src="https://user-images.githubusercontent.com/71384922/188420624-2d4af340-7491-4749-be9d-fe6d9aae6569.png">

**Comment by jagodarybacka** [comment]
Should be fixed by nonce fix https://github.com/tallycash/extension/pull/2130
