### ISSUE TITLE
Estimated network fee on Polygon always displayed as 30 gwei

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2112]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send / swap assets on Polygon

### What did not work?

Regardless of what the gas fee is / a user selects it's always displayed as 30 gwei

<img width="364" alt="Screen Shot 2022-09-03 at 09 28 41" src="https://user-images.githubusercontent.com/71384922/188260790-b8c48dfa-8a2f-415d-82ff-7645fe273922.png">

<img width="369" alt="Screen Shot 2022-09-03 at 09 28 46" src="https://user-images.githubusercontent.com/71384922/188260793-f18d635f-5694-4383-904f-e1f5e504f173.png">

<img width="365" alt="Screen Shot 2022-09-03 at 09 28 52" src="https://user-images.githubusercontent.com/71384922/188260794-97b0691e-b7fe-48db-b2b4-8d71a30737d1.png">

<img width="356" alt="Screen Shot 2022-09-03 at 09 28 57" src="https://user-images.githubusercontent.com/71384922/188260796-ad39cd63-bc05-4bfe-94cc-8259744b8ad1.png">

### Version

v0.15.0

**Comment by yang57689** [comment]
This happens with Google Chrome too
