### ISSUE TITLE
Optimism: Update gas page

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#2119]
Let's update the gas settings page for Optimism.
Changed the language a bit, to be a bit more international friendly.

## Preview
<img width="913" alt="image" src="https://user-images.githubusercontent.com/80846886/188392471-54c6b0e3-8e44-453e-a6d1-138cdc8cf9cd.png">

## Content
Gas fees on Optimism, work differently from Ethereum.
The estimated gas cost for Optimism transactions includes Optimism fee + Ethereum roll-up fee (fee to register transaction on Ethereum chain)
Tally stays in sync with the current Optimism and Ethereum network fees to estimate the fee for a given transaction.  Only in rare cases will the actual fee you pay change by more than 25% from the estimate.

## Figma 
[ Figma Link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=12632%3A271687)

**Comment by mhluongo** [comment]
It's unclear to me from the screen on the right that the entire fee is still denominated in ETH — anyone else?

**Comment by VladUXUI** [comment]
True, if you just look at this screen, it's not mentioned. I figured that people come here by clicking on the gas estimation, so they already should know.

I can change icons so they are not round(like assets) and add a "fees are paid in ETH"
