### ISSUE TITLE
Swapping (Wrapping) ETH to WETH does not update WETH balance

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2121]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1015508125803098172

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap ETH to WETH

### What did not work?

Swapping ETH to WETH is actually a wrapping. The ETH balance is updated, but the WETH balance is not. 

User report: https://discord.com/channels/808358975287722045/888500174685614090/1015508125803098172

**Reproduced:** 
https://etherscan.io/tx/0xd3d82b75ee8215fe085ff8192e39f7941cfc3c6be0c1ae4f0b5d333f064a6b17
ETH balance displayed in wallet: 0.0821  - Etherscan: 0.0821
WETH balance displayed in wallet: 0 - Etherscan: 0.01
<img width="369" alt="Screen Shot 2022-09-05 at 09 43 46" src="https://user-images.githubusercontent.com/71384922/188395757-dabc528f-c55b-4838-a6c0-b84f4d405882.png">

### Version

v0.15.0

**Comment by VladUXUI** [comment]
Swapping from Keep to WETH is updating the WETH balance.
Maybe we don't read wraps?

Related to https://github.com/tallycash/extension/issues/2052
