### ISSUE TITLE
Exclude Goerli from overview tab

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#2125]
Test nets shouldn't be included in the overview tab data.
Let's remove them from:
- total balance
- accounts balances
- networks chart
- assets balance

![image](https://user-images.githubusercontent.com/20949277/188445562-024e4964-33c4-42d4-bd06-3ef85c753fc9.png)

**Comment by jagodarybacka** [comment]
hmmmm, good point. We can exclude test networks from the overview 🤔 Then - we should exclude them from accounts' balance in the overview, from assets and charts. I'm ok with that but then it is no longer a "good first issue" 😄

**Comment by kkosiorowska** [comment]
> hmmmm, good point. We can exclude test networks from the overview 🤔 Then - we should exclude them from accounts' balance in the overview, from assets and charts. I'm ok with that but then it is no longer a "good first issue" 😄

I will try to do it 😄
