### ISSUE TITLE
Optimism: "Unexpected Error" under activity after buying NFT

### ISSUE THREAD

**Issue by alsoknownaslj** [tallycash/extension#2149]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Bought an NFT on quix -> clicked to Activity after signing contract -> received "Unexpected Error"

### What did not work?

<img width="591" alt="Screen Shot 2022-09-07 at 3 53 58 PM" src="https://user-images.githubusercontent.com/104520552/188965730-9a731d89-a7d7-4c78-a4b3-d7f96064a151.png">

**Comment by 0xDaedalus** [comment]
Unfortunately I'm not able to recreate this behavior.

I've bought an NFT from the same collection as the one used above https://qx.app/collection/motorheadz and do not have any issues.  If you see this again would you mind exporting your logs and uploading them here?  There might be something in there that gives us a clue.

**Comment by 0xDaedalus** [comment]
This no longer seems to be an issue.
