### ISSUE TITLE
Can't donate on Gitcoin - error 'the user rejected the request'

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2152]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1017337752389435492

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Donate on Gitcoin, on mainnet

https://gitcoin.co/grants/5288/tally-ho-open-source-and-community-owned-wallet

### What did not work?

Transaction set-up fails. Gitcoin reports 'the user rejected the request', after opening the extension the 'transaction failed to broadcast' message comes up.
<img width="1791" alt="Screen Shot 2022-09-08 at 09 56 11" src="https://user-images.githubusercontent.com/71384922/189090281-36056007-b171-4a8c-94c4-ff13d5ca3568.png">

User reported and shared his console logs:
[gitcoin.co-1662623837283.log](https://github.com/tallycash/extension/files/9525726/gitcoin.co-1662623837283.log)

I'm able to reproduce as well. Attaching my logs as well:

[logs_v0_15_1__2022-09-08T11_54_10+02_00.txt](https://github.com/tallycash/extension/files/9525796/logs_v0_15_1__2022-09-08T11_54_10%2B02_00.txt)

I've just tested with an older dev build, 0.14.1 --> there it still works.

Could be related to #2116  --> also tried with 0.14.1 here, also works.

### Version

v0.15.1

**Comment by hosaka** [comment]
The gitcoin.co log was captured using Brave by the way.

**Comment by hosaka** [comment]
Built on main/ and installed the extension. Gitcoin transaction went through with no problem and no errors in the log.

**Comment by jagodarybacka** [comment]
Yup, current main is working with gitcoin
![image](https://user-images.githubusercontent.com/20949277/189321863-4689132a-6b94-4c1d-848f-7c80879a1c81.png)
