### ISSUE TITLE
Remove Account does not remove activities from storage

### ISSUE THREAD

**Issue by beemeeupnow** [tallycash/extension#2194]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Simple reproduction:
* Add read-only account
* View the Activities section for the account and make sure they load
* Remove the read-only account

### What did not work?

The activities remain as orphaned data in redux

### Version

v0.16.0

**Comment by jagodarybacka** [comment]
Should be fixed now https://github.com/tallycash/extension/pull/2311
