### ISSUE TITLE
Optimism: Unknown gas price

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#2196]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Anything and everything. From Send to contract interaction to standard in-wallet swap

### What did not work?

For everything i do, i get gas price unknown
![image](https://user-images.githubusercontent.com/80846886/190341620-2c05bad3-4a34-49be-b1c0-f0f0ed1d0331.png)

### Version

v0.16.0

**Comment by 0xDaedalus** [comment]
No longer an issue.
