### ISSUE TITLE
Optimism - Unexpected error and spinning sign button

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2199]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1019769109040341022

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up a transaction on Optimism

### What did not work?

Requesed more info. So far:

"after click sign button, keep spinning and nothing happen."

![image](https://user-images.githubusercontent.com/71384922/190349329-7bfb9868-9150-44de-9571-cd67634afb49.png)

### Version

v0.16.0

**Comment by jagodarybacka** [comment]
Spinning sign button should be solved on current `main` and included in next release soon. Not sure where user got this unexpected error - was this on Swaps page?

**Comment by 0xDaedalus** [comment]
Issue has been resolved.
