### ISSUE TITLE
Optimism/Curve: Approve Asset Spend not popping up

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#2201]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Anything on Curve/Optimism.
Wallet connection works.

### What did not work?

I could connect my wallet, but it's not popping up the extension when trying to interact with contracts.
Approve asset spend is not showing.

This works on Ethereum and Polygon

### Version

v0.16.0

**Comment by VladUXUI** [comment]
This is not a release blocker imo

**Comment by jagodarybacka** [comment]
For me it shows approve token spend window but tx is failing
