### ISSUE TITLE
Transaction screen sign and reject is not working as expected

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2202]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1019155670085410876

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

Send & swap.

### What did not work?

1) Transaction signing message appearing again and again --> also if you reject it
2) Unable to send matic, swapping, and not able confirm transaction on  DAPPS, almost everything connected to signing the message(it only buffers the transaction)

The user did do a new install for 0.16.0, but is still experiencing the issue.

Logs: 
[tallyho1.txt](https://github.com/tallycash/extension/files/9573278/tallyho1.txt)

![image](https://user-images.githubusercontent.com/71384922/190351808-b8adb564-2b67-48a9-a659-0e94f5cef97f.png)

### Version

v0.16.0

**Comment by jagodarybacka** [comment]
Spinning sign button solved on current `main`
Signing screen showing after reject => #2164
