### ISSUE TITLE
Create Community Pledge signature feed for Project GALXE

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2203]
Data can be fed into GALXE in 4 ways. Options are listed below with the relevant info I could find, where the target is to feed the data real-time.

In case of specific questions we can reach out to the GALXE team.

**Real-time**
- Updated through an API
https://docs.galxe.com/developer/graphql-api/overview
https://docs.galxe.com/developer/guide/api-cred-items-update
https://graphigo.prd.galaxy.eco/

- Subgraph
https://docs.galxe.com/developer/guide/subgraph-cred

**Snapshots - manual upload**
- Snapshot - CSV

- Google sheet (pulled from by Galaxy every 12 hours)

**Comment by mr-michael** [comment]
cc @greg-nagy GTM team needs to have a working version of this Friday or next Monday at the latest

**Comment by greg-nagy** [comment]
https://github.com/tallycash/tally.cash/commit/1417d177f6766d31c3608b7f668f33e31cc893fc
https://github.com/tallycash/tally.cash/commit/096b027f1770369d5436f3c537c7136b0ed3071c

Done
