### ISSUE TITLE
Can't connect with Gnosis Safe

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#2205]
On [Gnosis Safe](https://gnosis-safe.io/app/welcome)
I don't have MM installed, this popup is appearing with and without Tally Ho as default options turned on
![image](https://user-images.githubusercontent.com/20949277/190396591-1085a506-2711-4c33-a5ea-2f030baa3101.png)

**Comment by Naxsun** [comment]
@jagodarybacka is this when you select MetaMask? 

If so, Gnosis Safe enables network by network: I need to inform them to enable Tally Ho as an option.

**Comment by jagodarybacka** [comment]
yup, fixed
