### ISSUE TITLE
Optimism: sBTC balance not displayed after an in-wallet swap

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2236]
### Discord Discussion Link

https://discord.com/channels/667044843901681675/1019997761497743430/1020665795853946990

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap to sBTC, in-wallet swap

Nax: I've reproduced this users issue. Below details are not from the user

### What did not work?

sBTC balance is not diplayed.

tx: https://optimistic.etherscan.io/tx/0x85ba75e11a78f45759ae2c6ca4aad732dcd9767b854841eb3c6261b0742963b3
<img width="368" alt="Screen Shot 2022-09-18 at 13 36 53" src="https://user-images.githubusercontent.com/71384922/190900107-00fe41ee-7cdf-4325-a95d-e1b044bc4de8.png">

<img width="628" alt="Screen Shot 2022-09-18 at 13 37 14" src="https://user-images.githubusercontent.com/71384922/190900122-5f4a8989-cbab-45ac-ada5-8e3b580da9dd.png">

<img width="290" alt="Screen Shot 2022-09-18 at 13 37 35" src="https://user-images.githubusercontent.com/71384922/190900133-efa43073-5ef0-4ef4-a314-83bdd907f698.png">

[logs_v0_16_0__2022-09-18T13_39_11+02_00.txt](https://github.com/tallycash/extension/files/9593865/logs_v0_16_0__2022-09-18T13_39_11%2B02_00.txt)

### Version

v0.16.0

**Comment by mhluongo** [comment]
I suspect this is a combo of...

- [ ] Not having sBTC and other synths well-represented in our token lists, and...
- [ ] ... not having the Optimism-variants in the lists, and...
- [ ] ... not having [asset auto-discovery turned on](https://github.com/tallycash/extension/pull/1840)

**Comment by kkosiorowska** [comment]
I have analyzed this issue. In our list of assets, sBTC does not have a `recentPrices` value. As a result, `unitPrice` is `undefined`. For this case, the `heuristicDesiredDecimalsForUnitPrice` returns the number 2 because `desiredDecimals` is hardcode.  I'm talking about this part of the [code](https://github.com/tallycash/extension/blob/d5935f60b090f7b99cf99025ad8369ad0ab3c48e/background/redux-slices/utils/asset-utils.ts#L228). This means that the sBTC value is truncated and is 0. So it will not be displayed.

I'm not sure how we want to solve this issue. I see several possible options. I would like to set our expectations for this task. Please correct me if I'm wrong.  

1. We can try to fetch `recentPrices` for such cases.  And calculate the correct `unitPrice`. A similar problem was for price impact.
2. We can check which place the first number appears and assume such precision. However, the limit of places should be determined. Now for this address, we would display a value of 0.00005 sBTC. I don't think we want that.

**Comment by jagodarybacka** [comment]
I think we need to look at the price of the asset in $ too. This is the case only for BTC (and derivatives) as its price is >10x higher than the ETH. I think we can:
- make an exception for BTC/sBTC/WBTC and allow is to display more decimal places
OR
- lookup the price if it is not available and decide based on that

**Comment by 0xDaedalus** [comment]
There's a fundamental problem here that with our current system of price fetching we simply won't be able to get prices for some assets that are bridges of L1 assets living on an l2.  e.g. sBTC has a completely different contract address on L1 than it does on L2 - and unfortunately our tokenlists are not nearly detailed enough to associate the two assets (nor should we expect them to be).

I think we have a few options here going forward listed below in ascending complexity:
- Make an exception for BTC/sBTC/WBTC (this might be good enough to close out this ticket - but we will need to make similar patches whenever a given asset's price gets over $10,000;
- Introduce "fallback" logic where if a given asset's price is not found on a network - try querying that asset's price on another network if we have a token with the same symbol on that network. (a bit dangerous - and also will become more complex the more L1's we introduce (BNB, AVAX, etc..)
- Introduce an additional path for looking up prices that uses on chain DEX and/or oracle data to determine prices between a set of given assets and a stablecoin like USDC.

Inconsistent price population results in a number of issues (missing prices on wallet activity list, price slippage calculations, misrepresentation of portfolio) so I think that maybe the way forward here is to do #1 - close this ticket - and open a new ticket for #3 if we have agreement that it is a good way forward.

**Comment by greg-nagy** [comment]
Agree with @0xDaedalus that the fundamental problem is that we rely on a single data provider for prices which makes our system error-prone. Having multiple providers and being able to define fallback lookups is what we probably need here.  My preference is to start with implementing data providers before DEXes, but I am good either way. My focus in this is that we focus on delivering the best wallet. So I think 3 as a follow-up issue is an excellent idea.

As for this concrete problem:
We could use `buyTokenToEthRate` if we don't get price data from coingecko, pull up the eth<>usd price, do some math and fire a `newPricePoint`. This is a cheat, but probably an acceptable one, and we would be sure to always have price data for tokens that the user just swapped to.

**Comment by kkosiorowska** [comment]
Thank you all for your thoughts. I will complete this task according to the suggested option 1 and then create a new task for option 3.
