### ISSUE TITLE
Ability to re-name account sections

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2239]
### Discord Discussion Link

n/a

### What would you like to be able to do?

Be able to re-name the sections of accounts. 

<img width="153" alt="Screen Shot 2022-09-19 at 09 49 12" src="https://user-images.githubusercontent.com/71384922/190972319-3050635b-3d23-4621-b1a7-7f53d5a87058.png">

**Comment by VladUXUI** [comment]
Adding designs:
[Figma link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=14274%3A282852)
![image](https://user-images.githubusercontent.com/80846886/198314812-9b32caf5-580d-4616-9fec-ef2e323b1a5f.png)
