### ISSUE TITLE
Warning when depositing funds into OP bridge

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2250]
Currently we display the following warning when users attempt to use the official OP bridge https://app.optimism.io/bridge (because the bridge is custodial).

We need to fix this issue this week. Here are two options to do that:

1. Name the OP teleportr contract: "🔴 Optimism Teleportr" so this warning doesn't display
2. Add this contract to an allowlist  so this warning doesn't display

Option #1 is preferable (because later on we can add Kraken, Coinbase, and other ~trusted CEX deposit addresses), but if we need to (aka we can't have this complete this week otherwise), option #2 is okay for now.

<img width="374" alt="Screen Shot 2022-09-19 at 4 34 21 PM" src="https://user-images.githubusercontent.com/7005061/191111454-ab5a08e9-2a91-458c-98ba-9da944e61dab.png">

Related: https://github.com/tallycash/extension/issues/2117

**Comment by 0xDaedalus** [comment]
I believe that naming the contract won't dismiss the error - but is a good idea nonetheless.

I think what we want here is both options 1 and 2.

Also want to call out that this adds another whack-a-mole game for us to play - on top of the metamask domain whitelisting one we already play.  Very happy to commit to this but a more robust solution would be great to have down the line.

**Comment by 0xDaedalus** [comment]
Went ahead and knocked out 1 [here](https://github.com/tallycash/extension/pull/2251)

**Comment by Shadowfiend** [comment]
The warning is wrong, fwiw. Sending assets doesn't necessarily result in loss of funds, it depends on where you're sending it—case in point, the Optimism bridge doesn't lose your funds, it locks them up with ways to get them back. When we originally discussed the design, @mhluongo spoke confidently to the idea that having a legitimate such transfer would be a rare situation and therefore worth additional work, but I think with L2s that's… Not really the case?
