### ISSUE TITLE
Can't connect Tally wallet to Etherscan

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2290]
### To Recreate
- ensure Metamask impersonation is enabled in settings
- https://etherscan.io/address/0x1f9840a85d5af5bf1d1762f925bdaddc4201f984#writeContract
- click the "Connect to web3" button
- click metamask 
- connection silently fails.

**Comment by Shadowfiend** [comment]
Closed by #2313, I marked the closing wrong 🙉
