### ISSUE TITLE
Choose a component testing library.

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2310]
I'd like for us to choose a component testing library and start standardizing around it so we can start building out our frontend test suite.

Ideally the deliverable here is a PR that
- Adds the chosen library to our project dependencies,
- Has rationale for choosing the said library.
- Implements a minimal test or two that serve examples of how to implement future tests,

I myself am partial to react-testing-library b/c of its focus on testing overall component function rather than implementation details, but I'd like to avoid this being a unilateral decision.

cc @greg-nagy @jagodarybacka @hyphenized @gasolin would love your thoughts here.

**Comment by gasolin** [comment]
in my experience, using `Jest snapshot tests + unit tests for critical part logic` is a low effort and a good enough combination

**Comment by 0xDaedalus** [comment]
Agreed re: snapshot tests - my experience working with them mirrors the sentiment in the linked article - once there are enough of them they tend to become a burden to iteration rather than a boon (in my experience).

I'm a big proponent of react-testing-library especially with its implicit nudge towards more "holistic" tests (as you mentioned in point 2).  Lets wait for some more comment but if there are no objections I think the next step here is probably a PR implementing a minimal component test via react-testing-library

**Comment by hyphenized** [comment]
I agree with choosing react-testing-library, I also believe is the go-to option these days because the tests result more focused around UI and user interaction rather than internal component logic

**Comment by kkosiorowska** [comment]
Thank you for your thoughts <3 I will start working on the implementation of the first component tests.
