### ISSUE TITLE
Mix-up miner & max base fee when setting custom gas prices on Ethereum

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2328]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/1024798385825398874

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send ETH

### What did not work?

Nax: I've reproduced this users issue. Below is my data.

tx: https://etherscan.io/tx/0xd7905fca852e8949a11ca9ee74c0d7c493e25897ff60528b60d06be2c09e3e04

<img width="382" alt="Screen Shot 2022-09-29 at 09 03 54" src="https://user-images.githubusercontent.com/71384922/192963008-23012d56-a3ba-44c1-ad90-7c36534bc1b2.png">
<img width="922" alt="Screen Shot 2022-09-29 at 09 05 49" src="https://user-images.githubusercontent.com/71384922/192963076-375181f2-e838-478b-ae0f-ebf81a69da26.png">

### Version

v0.16.3

**Comment by jagodarybacka** [comment]
It's the same issue as https://github.com/tallycash/extension/issues/2163 but thanks for documenting this problem better than I did in the prev task 👍
