### ISSUE TITLE
TypeError: Cannot convert null to a BigInt 

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#235]
Line 45 in chain/service.ts throws,
![bigint-error](https://user-images.githubusercontent.com/1918798/133169187-8e994c80-c9a5-4e54-ad28-ef922308aaa6.png)

Changing that line to,
```
difficulty: gethResult.difficulty && BigInt(gethResult.difficulty),
```
is an ok temporary fix I'm using locally.

**Comment by mhluongo** [comment]
Are we good to close this @henryboldi?
