### ISSUE TITLE
Textbug when user wants to delete an address 

### ISSUE THREAD

**Issue by morisschulzersson** [tallycash/extension#2355]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/944337346684391474/1025499802420650004

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

I wanted to delete one of my addresses which I imported a few weeks earlier using a recovery phrase.

### What did not work?

<img width="351" alt="Bildschirmfoto 2022-09-30 um 22 06 35" src="https://user-images.githubusercontent.com/84903235/193516293-5bb5471a-5631-4245-b265-3f21adf38f2f.png">

### Version

v0.16.3

**Comment by 0xDaedalus** [comment]
Closing because this no longer seems to be an issue :+1:
