### ISSUE TITLE
Network fees displayed as ~0 Gwei & gas cost prediction too high

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2373]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Change gas settings when making a swap on Sushi.

### What did not work?

- All gas is displayed as 0 Gwei
- The fees displayed are too high.

Using this build:https://github.com/tallycash/extension/pull/2288

<img width="378" alt="Screen Shot 2022-10-04 at 13 37 22" src="https://user-images.githubusercontent.com/71384922/193888712-03097e91-1c2b-4272-a96f-e5c8f393b497.png">

<img width="382" alt="Screen Shot 2022-10-04 at 13 37 16" src="https://user-images.githubusercontent.com/71384922/193888721-fc38f028-e392-4040-8780-8fb0a6860dbc.png">

### Version

v0.16.5

**Comment by jagodarybacka** [comment]
Related - https://github.com/tallycash/extension/issues/2428
