### ISSUE TITLE
Can't transfer an NFT from Trove

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2374]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

By an NFT from the 'Treasure Collections' on Trove, view it from within the wallet, and transfer it to another address.

### What did not work?

- Bought the NFT on trove
- It was bought, but not transferred to my address
- It was not yet showing up in the NFT tab in the wallet, and not on Arbiscan
- After trying to transfer the NFT to my own address, the same with which I bought the NFT , it does show up in the wallet as an NFT but without an image. It does not show up on Arbiscan
- The Arbiscan link from within the wallet links to: https://arbiscan.io/error.html?404

<img width="385" alt="Screen Shot 2022-10-04 at 17 00 09" src="https://user-images.githubusercontent.com/71384922/193927344-d4a72a51-5207-4169-b1c8-7eb56b11de73.png">

- After trying to send the NFT to a different address through Tally Ho, below error message comes up.

<img width="1166" alt="Screen Shot 2022-10-04 at 16 57 49" src="https://user-images.githubusercontent.com/71384922/193927427-59a6464c-e0c1-42de-9665-b1a4638c2cb2.png">

I've tried to transfer it through MetaMask, that works. It still isn't showing on Aribiscan though, and it's still showing in the wallet with 'no preview' and links to https://arbiscan.io/error.html?404

### Version

v0.16.5

**Comment by greg-nagy** [comment]
We have tested this and it worked
