### ISSUE TITLE
Achievements do not show up on Ethereum

### ISSUE THREAD

**Issue by chlolands** [tallycash/extension#2391]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was trying to view my achievements on the achievements tab when first opening up the wallet. I was on the Ethereum chain.

### What did not work?

My on-chain achievements are just on Optimism. So when on Ethereum, I was not able to view my achievements. I then switched over to Optimism, and I was since able to view all of my on-chain achievements regardless of what chain I was currently on. 

**note: running the achievement tab QA build.**

**Comment by jagodarybacka** [comment]
This is currently correct behaviour as we are not fetching data for any chains that were not used by a given user. So wallet starts to include Optimism assets and nfts in the Portfolio tab only if you previously switched to Optimism chain.

Closing it for now. Feel free to reopen if requirements will change.
