### ISSUE TITLE
Optimism/Arbitrum - Send Base Asset is not sending when connected to Ledger

### ISSUE THREAD

**Issue by SJQuality** [tallycash/extension#2400]
### **Build Info/PR/Commit:**
https://github.com/tallycash/extension/releases/tag/untagged-89ee43e9ce171430ea45

### **Reproduction Steps:**

1. Connect account via a Ledger (using imported works as expected)
2. Optimism OR Arbitrum network
3. send Optimism token
4. Go through signing via ledger

### **Expected Result:**
Transaction processes. 

### **Actual Result:**

The transaction DOES NOT process:

https://www.awesomescreenshot.com/video/11583071?key=d4f01fccc0bc96e3feb28050be2abb0e

From Matt
![image](https://user-images.githubusercontent.com/103908695/194638272-5a506d8a-0366-43b7-a9e8-fa59b5ce70ae.png)

**Comment by Shadowfiend** [comment]
Might be fixed by #2401.

**Comment by mhluongo** [comment]
Should be! Same log output

**Comment by greg-nagy** [comment]
It has been fixed by #2401
