### ISSUE TITLE
Implement Odyssey banners

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2417]
This spike is to determine LOE for the 'Odyssey banners' feature pitch: https://coda.io/d/Minimum-Viable-Launch_dznBnP8Wtkc/Odyssey-Banners_suzD5#_luhJv

... And also to determine if we can get everything we need from Galxe's API to help with this. Their API playground here: https://graphigo.prd.galaxy.eco/

All the Odyssey campaigns will take place within the Arbitrum space. Here are the week 2 examples:

- https://galxe.com/arbitrum/campaign/GCaigUt9HD
- https://galxe.com/arbitrum/campaign/GCsqgUtsTX

(fwiw the query below will give back all campaigns on Arbitrum... we can probably filter only for campaigns in the Arbitrum space and use the startTime field to figure out which campaigns are the most recent/current)

```
{
  campaigns(input: { chains: ARBITRUM }) {
    list {
      id
      name
      space { name }
      chain
      startTime
      numNFTMinted
    }
  }
}

```

**Comment by jagodarybacka** [comment]
**UI implementation**
Banner will be super similar to the one we have in the empty achievements tab so there is not much to be done here
![image](https://user-images.githubusercontent.com/20949277/195581202-09db69bd-bdd1-441c-99bc-6806e39ec250.png)
More time will be needed to implement dismissing and showing the user correct banners in the right time.

**Getting data**
This query will list all campaigns within [Arbitrum space](https://galxe.com/arbitrum). I think it will give us what we need - thumbnail, name, if the campaign is active or not, start and end dates
```
query ArbitrumCampaigns {
  space(alias: "arbitrum") {
    campaigns(input: {
      chains: [ARBITRUM]
    }) {
      list {
        id
        name
        status
        thumbnail
        startTime
        endTime
      }
    }
  }
}
```

**Comment by greg-nagy** [comment]
let's repurpose this for the actual work
