### ISSUE TITLE
Odyssey banners

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2426]
Placeholder ticket

Spike: https://github.com/tallycash/extension/issues/2417

**Comment by mr-michael** [comment]
@jagodarybacka I created this but if you want to just track in the spike ticket that's fine too and we can close this

**Comment by jagodarybacka** [comment]
Yeah I think we can reuse spike ticket as it already contain some useful info

**Comment by VladUXUI** [comment]
Adding a quick gif to accompany this ticket
And a [link to figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=13938%3A283167)
![CleanShot 2022-10-14 at 07 57 25](https://user-images.githubusercontent.com/80846886/195809516-84e8399a-0735-4377-86ac-1ada96d92ea3.gif)
