### ISSUE TITLE
Create PR in WalletConnect's repo to add Tally as a desktop wallet

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#2436]
-

**Comment by VladUXUI** [comment]
--

**Comment by greg-nagy** [comment]
For this to work the wallet should support wallet connect first. We will have a spike for figuring out the LOE for that 

- they have a wallet registry https://medium.com/walletconnect/introducing-walletconnect-cloud-registry-c17ac580f33
- they are in the middle of a migration from v1 to v2 (wallets should support both)
- demo
  - test web wallet: https://test.walletconnect.org/
  - test dapp: https://example.walletconnect.org/
