### ISSUE TITLE
Can't swap on GMX

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2450]
### Discord Discussion Link

na

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap on GMX

### What did not work?

Swapping USDC to ETH. The approve tx was succesfull, the actual swap gives a 'user rejected the request'. Could be similar to #2434 

Logs:
[logs_v0_17_1__2022-10-18T09_53_01+02_00.txt](https://github.com/tallycash/extension/files/9807800/logs_v0_17_1__2022-10-18T09_53_01%2B02_00.txt)

<img width="1501" alt="Screen Shot 2022-10-18 at 09 51 47" src="https://user-images.githubusercontent.com/71384922/196370229-d00b6db8-73bc-47e5-9574-df07fc7c34bc.png">

### Version

v0.17.1

**Comment by hyphenized** [comment]
Could not reproduce

**Comment by Naxsun** [comment]
@hyphenized was there a PR to fix it? 

It's now working for me as well but was able to reproduce this consistently with earlier versions. Want to make sure it's not working now coincidentally but we fixed it.

It's an important dapp for our upcoming campaign.

**Comment by Naxsun** [comment]
Tried with an older build, there it's still failing -> there's a fix implemented. Sweet.
