### ISSUE TITLE
Show onboarding in dApp connection modal if the user hasn't been onboarded

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#2487]
Let's show the onboarding flow in the dApp modal if the user has tally installed, hasn't finished onboarding yet and the dapp triggers a connection. 

The initial thought for the fix — without deeper consideration and testing: 
- Redirect to `/onboarding/info-intro` [from here.](https://github.com/hyphenized/tally-cash/blob/8f7fc80a6c2c2ac5825fca46eabead893fc73772/ui/pages/DAppConnectRequest.tsx#L65)
- An informing screen might be needed
- need a method to redirect to the dapp connection window after finishing the onboarding

**Comment by mhluongo** [comment]
This won't work for tabbed onboarding. Instead, maybe just open the onboarding tab?

**Comment by greg-nagy** [comment]
Do you think the extension of #2545 could work until we release the tabbed onboarding?
