### ISSUE TITLE
Reduce the delay for signing button after inactivity

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2498]
### Discord Discussion Link

n/a

### What would you like to be able to do?

After a while of inactivity it takes 10 seconds or more for the sign button to become actionable / orange

https://user-images.githubusercontent.com/71384922/197733529-26859dfb-905b-4e80-90dc-2ae8efc88589.mov

**Comment by hyphenized** [comment]
Fixed with new signing UI @v0.18.0
