### ISSUE TITLE
Galxe Arbitrum NFT not shown (yet) in the wallet

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2499]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

View Arbitrum NFT's in the walet

### What did not work?

NFT's are not showing the image yet after 30 minutes

**NFTs mint tx's**
https://arbiscan.io/tx/0x4605892942b7fcb638a34818ce000d2dfe514c4600f67214be3df863b4129139
https://arbiscan.io/tx/0x3662fea5cbe69b59c356b43824df75efe078f8b25f983cf46d23df68c4ce3d2d

Wallet:
<img width="381" alt="Screen Shot 2022-10-25 at 11 25 27" src="https://user-images.githubusercontent.com/71384922/197737642-9fc601f1-ca7c-4fe2-9531-5c90c45d8747.png">

tofuNFT
<img width="535" alt="Screen Shot 2022-10-25 at 11 12 09" src="https://user-images.githubusercontent.com/71384922/197737699-ede8f227-7b7a-48f2-abc8-53e0a6649612.png">

### Version

v0.17.3

**Comment by jagodarybacka** [comment]
I see that the place we expect to include the image link is empty but `extra_metadata` already contains the image so we can use it as a backup

**Comment by Naxsun** [comment]
The 2nd NFT appeared after 1 day
