### ISSUE TITLE
No "max" option for swaps on Arbitrum

### ISSUE THREAD

**Issue by alsoknownaslj** [tallycash/extension#2553]
Max button is missing for in-wallet swaps on Arbitrum. 

Arbitrum:

<img width="405" alt="Screenshot 2022-11-03 at 2 41 36 PM" src="https://user-images.githubusercontent.com/104520552/199820468-b1f6b2b7-d3b9-4f2c-b3db-7946f4a4c933.png">

Mainnet: 

<img width="402" alt="Screenshot 2022-11-03 at 2 41 50 PM" src="https://user-images.githubusercontent.com/104520552/199820495-032633b6-054f-478a-97d3-b39f2b478b8a.png">

**Comment by jagodarybacka** [comment]
It's by design - you can't click "max" on the base asset on a given chain - so here for Arbitrum ETH is a base asset (asset that you pay for gas)

**Comment by jagodarybacka** [comment]
@attila-lendvai it means we decided to implement it like that 😉

**Comment by attila-lendvai** [comment]
> it means we decided to implement it like that

that's not very useful to help me guess what i can expect from future releases.

context: i tried to transfer all the funds between two of my accounts, but there's not max option, and the display of the current balance is limited to two decimals.

**Comment by jagodarybacka** [comment]
@attila-lendvai Ok so long explanation why we decided to remove this option: if you want to transfer all of the base asset for a given network (so ETH on Ethereum, MATIC on Polygon) then you still need to leave a little bit to pay for gas fees. We decided that making that calculation for every network we support will take too much time to implement and we deprioritized this feature to save time for more fun features 😃 

If you think it is a much needed thing then we can reopen this task but in the meantime you are still able to manually type how much of an asset you want to send leaving a little bit for gas payment. Wallet will notify you if you'll try to send more than you have (minus current gas price).

**Comment by attila-lendvai** [comment]
@jagodarybacka thank you! so, it's basically point 3: it's a headache to implement and it's not a priority for now, and i shouldn't expect it to land in the repo in the near future.

by now i understand that this is basically an ethereum design deficiency.

**Comment by jagodarybacka** [comment]
@attila-lendvai yup, we may reconsider it if we will see it is bothering more users
