### ISSUE TITLE
Add Native Binance Smart Chain Support to Tally Ho

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2569]
### Requirements
- [x] Send / Receive Assets
- [x] Swaps
- [ ] Gas Price Preview
- [x] Dapp connection / tx signing
- [x] Ledger Support
- [x] Coming Soon page for Gas Price Adjust
- [x] If #2547 or similar has been merged - preference for a generic rpc provider.
- [x] Assets showing up in Overview
- [x] ENS Name Resolution
- [x] Ensure support for popular dapps  (cc @mr-michael @alsoknownaslj @Naxsun  to provide list in a separate issue).

### Stretch Goals
- [ ] [Gas Price Adjust](https://github.com/tallycash/extension/issues/2571) (cc @VladUXUI do we have an updated design for a simple gas price + gas limit gas adjustment screen?  This is basically pre-EIP 1559 adjustment)
- [x] NFT Support (If we can find a free api)

### Useful References
- https://github.com/tallycash/extension/pull/2287/files
- https://github.com/tallycash/extension/pull/1347/files

### Notes
- Support for NFTs is not a hard requirement.
- I expect we'll want to open multiple PRs to ultimately close out this ticket - trying to tackle this in one PR might result in a large amount of code to review.
- PRs and issues open for avalanche-specific bugs encountered while implementing avalanche support should be added to the [`Binance Smart Chain Support`](https://github.com/tallycash/extension/milestone/15) milestone.

**Comment by kkosiorowska** [comment]
Ledger is working only for the ETH app for now. BSC support for Ledger should be added when this [PR](https://github.com/tallycash/extension/pull/2577) will be merged.
