### ISSUE TITLE
RSK: Change network logo

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#2574]
Hey hey, adding another version of the RSK logo for the network. Because we only have dark version atm, the current logo is hard to make out.
I tried to follow brand guidelines but i couldn't quite use the spacing that was suggested there, so hopefully this works.

here is a screenshot of how it would look
<img width="405" alt="image" src="https://user-images.githubusercontent.com/80846886/200512000-23125409-01ba-45dc-8e18-f2d962d7a5f1.png">

<img width="16" alt="RSK-square@2x" src="https://user-images.githubusercontent.com/80846886/200511786-30f701de-14c7-47fa-92d9-e4a59898aff8.png">

CC @ahsan-javaiid and @PabloCastellano you all good to use this logo?

**Comment by hyphenized** [comment]
Closed by #2620
