### ISSUE TITLE
Blinking tx screen

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#2591]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Set-up a transaction

### What did not work?

Some users are reporting a tx screen that keeps blinking and remains stuck on this screen. 

I'm able to reproduce this issue by significantly reducing my internet bandwidth. Below an example while I'm deliberately streaming to zoom, while I'm setting up the transaction. There's also a comparison with MetaMask in the video.

Overall the extension becomes a bit sluggish while doing this. Takes long to pop-up and to switch networks.

https://user-images.githubusercontent.com/71384922/201315829-b0cbd431-e90b-4a9c-b8ea-f0cef851424d.mp4

### Version

v0.17.9

**Comment by Naxsun** [comment]
Adding a note here: I'm only able to reproduce it with a 'low' internet speed. I don't know if this is the (only) thing that triggers it for users, needs to be investigated.

**Comment by mr-michael** [comment]
I'm seeing users report this on galxe, li.fi, and hop

Examples:

https://discord.com/channels/808358975287722045/888500174685614090/1041056240597467306
https://discord.com/channels/808358975287722045/888500174685614090/1041033810734743692
https://discord.com/channels/808358975287722045/888500174685614090/1041030904027545610
https://discord.com/channels/808358975287722045/888500174685614090/1040949786838319124
https://discord.com/channels/808358975287722045/888500174685614090/1040924060953100318
https://discord.com/channels/808358975287722045/888500174685614090/1040788085266452490
https://discord.com/channels/808358975287722045/888500174685614090/1040750641938710668

**Comment by 0xDaedalus** [comment]
Example logs from a user reporting this issue: 

[logs_v0_17_9__2022-11-16T01_42_2803_00.txt](https://github.com/tallycash/extension/files/10016674/logs_v0_17_9__2022-11-16T01_42_2803_00.txt)
