### ISSUE TITLE
Swap: Add loading state

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#2629]
Right now we don't have an indicator that prices are being loaded.
I think this is a good time to have a bit of fun :)

The size of the actual gif in design is 54x54 px

![Loading state](https://user-images.githubusercontent.com/80846886/202120253-ded4940c-e553-40ed-a501-04048de710a2.gif)

![image](https://user-images.githubusercontent.com/80846886/202120582-798e8c94-6e88-4f17-b69f-b076fec5df8a.png)

**Comment by frankiefab100** [comment]
I would like to work on this

**Comment by hyphenized** [comment]
@frankiefab100 Sure! Feel free to reach out if there's anything we can help with! Also, if you're not already in the discord I would definitely recommend [joining](https://chat.tallyho.org/)!

**Comment by frankiefab100** [comment]
> @frankiefab100 Sure! Feel free to reach out if there's anything we can help with! Also, if you're not already in the discord I would definitely recommend [joining](https://chat.tallyho.org/)!

Alright.

**Comment by frankiefab100** [comment]
@hyphenized  please i can't seem to find the way out. Is it this [section](https://github.com/frankiefab100/extension/blob/main/ui/pages/Swap.tsx) ?

**Comment by VladUXUI** [comment]
@frankiefab100 It is not in the codebase yet. Need to download it from the ticket and will need to be placed in public/ui/images

**Comment by TheJarX** [comment]
@frankiefab100 u still working on this? 👀

**Comment by TheJarX** [comment]
@frankiefab100  Are you still working on this? 👀

**Comment by frankiefab100** [comment]
> @frankiefab100 Are you still working on this? 👀

Not yet. You can go ahead

**Comment by TheJarX** [comment]
I'll take this then
