### ISSUE TITLE
Swapping temporarily clears out erc-20 token balances

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#2652]
### Notes
- Token balances eventually return to normal (probably once the `getTokenBalances` alarm runs
- Probably related to https://github.com/tallycash/extension/pull/2607 - [this block](https://github.com/tallycash/extension/blob/main/background/redux-slices/accounts.ts#L278:L284) is probably a good place to start looking
- An idea here might be to revert some of the changes introduced in 2607 and instead adopt a solution similar to [this untested diff](https://github.com/tallycash/extension/compare/main...foo-11/15).

https://user-images.githubusercontent.com/94649004/202914556-d95a2fc0-ecda-4e77-a8e9-3fa9c64c8fe7.mov

**Comment by greg-nagy** [comment]
eh, not just swaps but send as well 


https://user-images.githubusercontent.com/7690112/202918016-5ded8652-07c6-4b09-acf1-316b7add7153.mp4
