### ISSUE TITLE
Should we initiate the dApp connection flow as soon as the QR code is shown?

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#2685]

**Comment by VladUXUI** [comment]
Discussed it with MH and we don't think this is a good idea.
We don't know if that is the intended flow of the user, so popping up Tally when they want to actually use the QR is not best UX.
We also don't want to change the mental model that Wallet Connect has created for their users.

So let's scrape this and have a button in Desktop page

**Comment by VladUXUI** [comment]
- [ ] Design button for Wallet Connect/Desktop page

**Comment by greg-nagy** [comment]
Thanks for the follow up and for the decision! This is perfect
