### ISSUE TITLE
Can't select certain addresses in ledger onboarding

### ISSUE THREAD

**Issue by hyphenized** [tallycash/extension#2781]
If I have selected some addresses on the other page there is no possibility to connect selected if there are none selected on current page. Also user can't connect accounts listed on different pages
![image](https://user-images.githubusercontent.com/20949277/207601503-0ed96327-e7fb-4c27-952a-a24561b74b8d.png)

_Originally posted by @jagodarybacka in https://github.com/tallycash/extension/pull/2510#pullrequestreview-1217420229_

**Comment by VladUXUI** [comment]
https://github.com/tallycash/extension/issues/1218 😅
