### ISSUE TITLE
If token metadata isn't found in a token list or via Alchemy, pull it from the token contract

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#308]
Inferred metadata should be added as a custom asset.

Follow on from #205

**Comment by Shadowfiend** [comment]
This should be as simple as introducing a version of [`getTokenMetadata`](https://github.com/tallycash/extension/blob/main/background/lib/alchemy.ts#L178-L213) that does direct calls to the underlying contract using Ethers.

The right place for that to live is a reimplementation of `getTokenMetadata` in `lib/erc20.ts`. The current implementation is used in the sign transaction approve view, but it needs to be ripped out of there (issue #). Once that's done, `lib/erc20.ts`'s `getTokenMetadata` can start taking an additional parameter that is the `provider`, and call `name`, `symbol`, and `decimals` to look the appropriate metadata up and return it all as a `SmartContractFungibleAsset`.

Then, that method can be called as a fallback in https://github.com/tallycash/extension/blob/main/background/services/indexing/index.ts#L378 .

**Comment by Shadowfiend** [comment]
To remove the dependency here, let's start by adding a `getERC20TokenMetadata` in `lib/erc20.ts` that takes the contract address + provider and does what I describe above. Then we can remove `getTokenMetadata` and rename after.

**Comment by Shadowfiend** [comment]
To remove the dependency here, let's start by adding a `getERC20TokenMetadata` in `lib/erc20.ts` that takes the contract address + provider and does what I describe above. Then we can remove `getTokenMetadata` and rename after.

**Comment by 0xDaedalus** [comment]
Closing because this has been completed ✅
