### ISSUE TITLE
Can't transfer 'discovered' assets

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#3183]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send assets that were not on the token list, but were discovered.

### What did not work?

Version was 0.28.1 but this is not an option in the version drop down.

Sending assets. After selecting the asset, quantity and receiver address and selecting 'continue', the tx sign screen does not come up.

https://user-images.githubusercontent.com/71384922/227476492-e85c9529-57a9-4b30-8c66-d0c688e6b2c0.mov

[logs_v0_28_1__2023-03-24T10_16_48+01_00.txt](https://github.com/tahowallet/extension/files/11060335/logs_v0_28_1__2023-03-24T10_16_48%2B01_00.txt)

### Version

v0.28.1

**Comment by VladUXUI** [comment]
This works as intended. Need to add trust ability before being able to transfer
