### ISSUE TITLE
Galxe pledge credential no longer updating after updating Admin accounts

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#3209]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Automatic update of the Web3 pledge credential

### What did not work?

After removing the account/address that was connected to the Pledge credential, as an admin address on Galxe, the pledge credential is no longer automatically updating with new pledge signer addresses.

This is possible related to the Access Token that is used no longer being valid.

The pledge credential had the last automatic update on March 26th.

### Version

v0.28.1

**Comment by Naxsun** [comment]
For the one eventually assigned to this, just reach out to me to align on the Access Token to be used. The new access token is available.

**Comment by VladUXUI** [comment]
Fixed
