### ISSUE TITLE
Activity loading pulser shows up on asset pages that don't have activity

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#335]
In this case, activity for the wallet has been loaded... but this particular asset doesn't include any. We need another empty state outside "loading"

![Screenshot from 2021-10-16 00-27-09](https://user-images.githubusercontent.com/427505/137573755-98ff9b2c-300e-4fd1-9887-0accfb5b1b8f.png)

**Comment by SJQuality** [comment]
@mhluongo Is this still a valid bug. I don't see a place where we can get activity on an asset that isn't in the user's wallet. Maybe I'm missing something?

**Comment by mhluongo** [comment]
No longer relevant!
