### ISSUE TITLE
Handle long account names on the activity cards

### ISSUE THREAD

**Issue by jagodarybacka** [tallycash/extension#3439]
Let's add an ellipsis to the account name instead of splitting token amount into two lines.

![image](https://github.com/tahowallet/extension/assets/20949277/a23dc5e4-55e4-480e-853f-7f2a4910f0f7)

**Comment by xpaczka** [comment]
This is actually already done

![Zrzut ekranu 2023-12-14 o 13 12 21](https://github.com/tahowallet/extension/assets/73061939/e234e4a8-197d-4939-ab2b-d60b602081ca)
