### ISSUE TITLE
Token balance support on non-Alchemy-supported networks

### ISSUE THREAD

**Issue by itsrachelfish** [tallycash/extension#360]
In order to implement swaps we're going to need to figure out some way to determine what tokens an account has without relying on `alchemy_getAssetTransfers`.

![asset-transfer-error](https://user-images.githubusercontent.com/1670549/139143505-d2db9954-f6de-4c86-bdcd-ea17c68d7ed3.png)

```alchemy_getAssetTransfers does not yet support kovan```

**Comment by 7alip** [comment]
I wonder how will you plan to track token balances in non-Alchemy-networks. 

`alchemy_getAssetTransfers`
`alchemy_getTokenBalances`
`alchemy_getTokenMetadata`

When user select the network which is not supported by Alchemy, are you assuming to get the same output as Alchemy? I'm planning to investigate for RSK network but I'm not sure how to achieve this in your codebase. Does it make sense to obtain the same output by fetching and mapping the data from an external API? It sounds to be heavy in the client side or you have something different in your mind.

**Comment by mhluongo** [comment]
The plan is to fall back to manual balance checking per-token. It is indeed to a heavy client lift.

**Comment by Shadowfiend** [comment]
Let's start this by:
- [ ] Implementing `getERC20TokenBalance` (singular!) using a normal Ethers provider and the ERC20 ABI at `lib/erc20.ts`.

Then we need a way to do some good batching in `ChainService` so we can do a fallback version of `getTokenBalances` even for larger numbers of tokens.

It's probably already not good that there's an Alchemy-specific implementation in `lib/erc20.ts`, tbh.

**Comment by mhluongo** [comment]
> Implementing getERC20TokenBalance (singular!)

We have this already ☺️

**Comment by Shadowfiend** [comment]
Ayyyy you right. `getBalance`!

There goes the easy part 😂

**Comment by 0xDaedalus** [comment]
Closed by https://github.com/tallycash/extension/pull/2423
