### ISSUE TITLE
Redux store refactor

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#363]

**Comment by henryboldi** [comment]
To be more specific, I think mainly the `accounts` slice could use some love. The other ones seem to be in decent shape

**Comment by Shadowfiend** [comment]
This ended up being a little general, but I think we said we felt good about the accounts slice now @henryboldi ? I'm thinking we close here and open more specific issues once we have more specific things we have opinions about.

**Comment by henryboldi** [comment]
Yes, agreed!
