### ISSUE TITLE
Swap

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#367]
High-level tracking issue for extension swap support. 

- [x] tallycash/tally-contracts#58
- [x] https://github.com/tallycash/tally-extension/issues/378
- [x] tallycash/tally-extension#379
- [x] #448 
- [ ] #392
- [x] #55
- [x] #380
- [x] #381

Useful info:
- [Figma prototype](https://www.figma.com/proto/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=1917%3A64152&scaling=scale-down&page-id=1917%3A64142&starting-point-node-id=1954%3A82781&show-proto-sidebar=1) for swap.
- [Swap contract order fill call](https://github.com/tallycash/tally-contracts/blob/main/contracts/swap/Swap.sol#L80).
- [Contract quickstart for ethers](https://docs.ethers.io/v5/getting-started/#getting-started--contracts).
- [0x API docs](https://0x.org/docs/api) ; Kovan endpoint is at https://kovan.api.0x.org . Relatively few tokens are supported there (https://kovan.api.0x.org/swap/v1/tokens).

**Comment by mhluongo** [comment]
Closed and shipped :muscle:
