### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#371]

**Comment by henryboldi** [comment]
How do we feel about option A or option B here?

<img width="1072" alt="settings" src="https://user-images.githubusercontent.com/1918798/144502298-2b65044d-05f3-4855-b889-41a7116fa442.png">

cc @mr-michael, @VladUXUI

**Comment by VladUXUI** [comment]
I vote option B to the sad and lonely option A. But could use some copy review IMO
