### ISSUE TITLE
`TallyWindowProvider` tracking issue

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#387]
The purpose of this issue is to track and collect every PR that relates to the window provider. - Greg

Window provider is responsible for providing the dApp with the window.ethereum / window.tally object with a standard EIP-1193 implemantation, so the dApps can communicate with our wallet through a standard way, hopefully without any changes necessary to their codebase.

**Comment by greg-nagy** [comment]
This became stale and probably is for the best not to keep this tracking issue open.
