### ISSUE TITLE
`ProviderBridgeService` tracking issue

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#389]
This issue is to track the `ProviderBridgeService` related PRs. 

The responsibility of this block is to 
- set up communication with the content script
- handle permissions (request, show page, pending, allow, not allowed etc)
- validate the passing through communication
- integrate with the redux store
- provide a persistant Db solution to support the above functionality

**Comment by greg-nagy** [comment]
This became stale and probably is for the best not to keep this tracking issue open.
