### ISSUE TITLE
Reverse-resolve all contract and send addresses via ENS to help avoid scams

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#413]
When a user is sending ETH or an ERC-20 to a recipient address, or interacting with a contract, the wallet should attempt to reverse-resolve that address, displaying any name and avatar info.

Expands on #411

**Comment by Shadowfiend** [comment]
This already happens?

**Comment by Shadowfiend** [comment]
Lord just saw I ended up here from other old tickets that were closed, but this one is also old 🙈 

Net net I think we can close this one also.

**Comment by mhluongo** [comment]
Excellent!
