### ISSUE TITLE
Update browser icon

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#447]
Per decision from Vlad + Michael G brain trust. cc @VladUXUI

**Comment by henryboldi** [comment]
Awaiting the decision on which icon to use by @Gluzman and @VladUXUI 🙏

The community is voting here: https://discord.com/channels/808358975287722045/877631587364261888/911349231908958358

**Comment by VladUXUI** [comment]
I'm good to defer to the community on this one. Although i sort of feel that chromatically it doesn't really represent Tally.
So i vote we go with d2 for now.

**Comment by henryboldi** [comment]
In practice it feels quite small,

<img width="327" alt="icons@2x" src="https://user-images.githubusercontent.com/1918798/143304964-a1ed0606-4eb4-48af-bbf5-a83013bcf1f7.png">
<img width="327" alt="icons-boxed-2@2x" src="https://user-images.githubusercontent.com/1918798/143304978-42d4ba81-eb39-49d8-b575-0cb2bf76501f.png">

**Comment by henryboldi** [comment]
@greg-nagy's idea of using an alternate symbol, like a paw print, could work well here. It seems difficult to make our current, relatively detailed icon feel native in the toolbar. Granted, to create and incorporate an alternate icon into the brand would be a significant undertaking. @VladUXUI, is there a direction you're leaning towards?

**Comment by VladUXUI** [comment]
A paw print isn't going to work unfortunately. We need to use our head for this (no pun intended)
I'll be back with updates

**Comment by mhluongo** [comment]
Is this still outstanding?

**Comment by henryboldi** [comment]
Yes, @mhluongo, I don't believe an icon has been chosen

**Comment by mr-michael** [comment]
Gang - feels like we've spent a lot of cycles discussing this.

Options that work:
- Existing dark square with just the floating dog head (instead of current design which has folder) (my vote)
- Orange circle with floating dog head

cc @VladUXUI @Gluzman

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/145544971-8c44f8e6-a5e4-42ae-aa89-c88b94c22305.png)
We landed on this one as being most recognisable.

**Comment by henryboldi** [comment]
Amazing, thank you @VladUXUI :)
