### ISSUE TITLE
Set up affiliateAddress

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#450]
From 0x ... they're asking us to use an affilateAddress - this can be any eth address ... it's used by 0x to attribute trades for tracking/analytics purposes; 'particularly important with RFQ b/c allows us to make sure your API key is not being abused' 

(I'm dropping them a note on TG rn for a bit more details)

**Comment by mhluongo** [comment]
Fixed this [with the community multi-sig](https://gnosis-safe.io/app/eth:0x99b36fDbC582D113aF36A21EBa06BFEAb7b9bE12)!
