### ISSUE TITLE
'Community Edition' onboarding flow

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#457]
https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=3589:170403#126898633 

Inclusive of:
- welcome cards / carousel ('tally is a dao' etc.)

This is blocked by a decision point re: whether we are doing 'read-only' onboarding flow or 2-path onboarding flow

**Comment by mhluongo** [comment]
Done in Figma, almost done in code.
