### ISSUE TITLE
Upgrade wallet flow

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#460]
via account screen; for users to upgrade read-only wallets —> full wallets by entering seed

**Comment by mr-michael** [comment]
cc @Shadowfiend I believe we can only do this for MM wallets correct? since we are only supporting MM seed import

**Comment by VladUXUI** [comment]
Upgrade wallet flow it's done really. Because it's the exact same flow as import.
But without derivation path, upgrade account is a gamble tbh. Because we have no way of importing that exact address unless it's the primary address of that wallet.
