### ISSUE TITLE
Submission  form spinner

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#526]
Antonio
>Most of our submissions are local and instant, but some aren’t. I noticed this in particular after cranking up our password derivation function difficulty, which makes the password creation step take >1s.

**Comment by henryboldi** [comment]
FWIW I added a `showLoadingOnClick` prop on the shared button component, but it's quite basic

**Comment by VladUXUI** [comment]
Basic is what we need for MVP :)
