### ISSUE TITLE
[Bug]: had to go through explore onboarding twice 

### ISSUE THREAD

**Issue by chlolands** [tallycash/extension#527]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/917871963077218324

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

trying to onboard into the wallet and transfer my assets

### What did not work?

the "explore tally" button on the last onboarding slide

### Version

OG Edition v0.0.7

**Comment by mhluongo** [comment]
Thanks for flagging this @chlolands! It's been bugging all of us heh

**Comment by henryboldi** [comment]
@Shadowfiend I think we should get this fixed before resubmitting. I'll open a PR with a fix soon
