### ISSUE TITLE
[Bug]: Import seed disabled

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#555]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Import a seed!

### What did not work?

<img width="355" alt="Screen Shot 2021-12-10 at 3 45 20 PM" src="https://user-images.githubusercontent.com/7005061/145639178-24804bac-9e0a-45e9-9c49-b57e7978cd40.png">

**Comment by mhluongo** [comment]
This was intentionally feature-flagged... but I'm down to unflag it now! @Shadowfiend do I have a +1?

**Comment by Shadowfiend** [comment]
Yesplz.
