### ISSUE TITLE
[Bug]: Dapp connection icon not centered

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#563]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

Should be centered, but is floating right

<img width="378" alt="Screen Shot 2021-12-10 at 3 53 45 PM" src="https://user-images.githubusercontent.com/7005061/145644449-70aee75e-19a9-4a44-a253-2050dae2653c.png">

**Comment by VladUXUI** [comment]
This is actually correct. We made a last minute decision to fix an issues with longer names.

**Comment by mhluongo** [comment]
Closing as won't fix
