### ISSUE TITLE
[Bug]: Dapp connections UI displaying dummy 'sushiswap' connection

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#564]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

-

<img width="371" alt="Screen Shot 2021-12-10 at 3 54 08 PM" src="https://user-images.githubusercontent.com/7005061/145644538-f575b76d-4b4c-458e-b664-b087f00240dd.png">

**Comment by henryboldi** [comment]
The bigger issue is that this is being displayed at all when not connected to a dApp. I'll disable it. As far as showing the correct info, @greg-nagy will have that covered 🙇
