### ISSUE TITLE
[Bug]: Overview missing # of accounts

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#566]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Design @ https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=3582:106138#126485553 includes # of accounts

### What did not work?

Current display missing display of # of accounts

<img width="295" alt="Screen Shot 2021-12-10 at 3 56 48 PM" src="https://user-images.githubusercontent.com/7005061/145644776-689760f9-27bb-4698-bb67-f39ce6b16c05.png">

**Comment by henryboldi** [comment]
I'd consider this low severity. Addresses and accounts basically the same thing here.

**Comment by mhluongo** [comment]
Appears to be fixed!
