### ISSUE TITLE
Inform user of keyboard shortcut to open extension

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#571]
Title quite explanatory, but basically a shift+ctr+T on mac would open the extension.
Removing the need to go in the toolbar and click on it.

**Comment by Shadowfiend** [comment]
This exists, it's just alt-shift-T (opt-shift-T on Mac) 🙊

**Comment by mhluongo** [comment]
"Explain the shortcut in the UI"

**Comment by VladUXUI** [comment]
Niiiiiice. * insert jew drop gif*

Will think about were to land it. 
Inner voice whispers oooonboaaaarding

**Comment by mhluongo** [comment]
> Inner voice whispers oooonboaaaarding

... and that's exactly what we did! Closed by #2088
