### ISSUE TITLE
Imported account showing as Read-only[Bug]: 

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#574]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I imported an account

### What did not work?

The imported account is showing as read-only on wallet page. But in accounts it shows up as Imported.

![image](https://user-images.githubusercontent.com/80846886/145686624-a4ec0d63-ec02-4de7-828f-323775493ff8.png)
![image](https://user-images.githubusercontent.com/80846886/145686634-4069cfe1-857e-4f16-9d0e-284a74a9795f.png)

### Relevant log output

```shell
Version 0.8.2
```

**Comment by henryboldi** [comment]
Pretty sure this has been fixed, but I don't recall off hand which PR fixed this

**Comment by mhluongo** [comment]
Confirmed as commit cfad68bca5c8189e25cb2c727182196943863d33 (actually closed much earlier)
