### ISSUE TITLE
Activity not updating with new stuff

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#575]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I sent myself Keep tokens. From Metamask to one of my read-only addresses

### What did not work?

Transaction showing up on etherscan but not in Tally. Asset has arrived in wallet

### Relevant log output

```shell
Version 0.8.2
```

**Comment by mhluongo** [comment]
@VladUXUI can you confirm this has been fixed?

**Comment by SJQuality** [comment]
@VladUXUI please try again when you get a chance.

**Comment by mhluongo** [comment]
Looks like this has been resolved!
