### ISSUE TITLE
[Bug]: Update pw entry copy - 'the decentralized web awaits'

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#577]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Create or re-enter pw

### What did not work?

On lock screen and pw creation screen, we display the MetaMask tagline 'the decentralized web awaits.' Can't do this!

Let's update (for now) to 'The community-owned Web3 wallet'

<img width="253" alt="Screen Shot 2021-12-11 at 4 53 50 PM" src="https://user-images.githubusercontent.com/7005061/145693306-9c68bfb2-a878-4218-8470-3cf9789eedeb.png">

<img width="318" alt="Screen Shot 2021-12-11 at 5 16 40 PM" src="https://user-images.githubusercontent.com/7005061/145693314-16975b37-06cb-4206-b848-7b389d5279e5.png">

**Comment by VladUXUI** [comment]
Bellow is a screenshot and content we agreed upon for this page.

![image](https://user-images.githubusercontent.com/80846886/145705547-ffc31bdc-2f0d-4efa-abf4-266b2aa19689.png)
H1 - First, let's secure your wallet
You will NOT be able to change thispassword for now.
