### ISSUE TITLE
[Bug]: No pw requirements beyond character limit

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#578]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Create password

### What did not work?

We're not enforcing any pw requirements currently beyond ensuring it's at least 8 chars long (e.g. no checks for cap and at least one special character). Not sure it's a 'must' for CE but would like to see where everyone's head is at here.

**Comment by mhluongo** [comment]
I'm in the camp of "password restrictions considered harmful". I'd rather see this turn into a password strength bar and let the user make their own informed decision

**Comment by itsrachelfish** [comment]
I strongly agree with @mhluongo on this one. Requiring specific characters can lead to users forgetting their password and often doesn't improve security as much as simply making the password longer. 

For example:
`ex4mpl3!` - only has 13 bits of entropy
`p4ssphrase!` - 22 bits of entropy
`my example passphrase is long` - 76 bits of entropy 

https://xkcd.com/936/

**Comment by mhluongo** [comment]
Closed aw `wontfix`
