### ISSUE TITLE
[Bug]: Dead link on seed import

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#579]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

On MM seed entry page, I click 'how do I find the seed' and expect to be taken to FAQ style info 

<img width="262" alt="Screen Shot 2021-12-11 at 4 55 11 PM" src="https://user-images.githubusercontent.com/7005061/145693435-46db8b8c-fe15-47b3-950b-2decea36654b.png">
### 

### What did not work?

Nothing is linked rn.

We should update to blog.tally.cash/how-to-migrate-to-tally (blog post isn't live but it will live here)

**Comment by henryboldi** [comment]
Fixed by https://github.com/tallycash/extension/commit/2302045cf4691e598b9ad6bc0841bee815590644
