### ISSUE TITLE
[Bug]: Accounts menu cleanup

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#582]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

-

### What did not work?

1 - "Read-only mode" => "Read-only"
2 - Are we missing an icon next to "imported"? Design @ https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=3584:151367#132443544 cc @VladUXUI 

<img width="381" alt="Screen Shot 2021-12-11 at 5 06 15 PM" src="https://user-images.githubusercontent.com/7005061/145693587-1d8c7fe3-99c3-46df-b5d7-edb88c3508a1.png">

**Comment by VladUXUI** [comment]
<img width="24" alt="import@2" src="https://user-images.githubusercontent.com/80846886/145706198-f68942ee-0fce-4258-b142-16b90006c0fa.png">


Icon import@2

**Comment by VladUXUI** [comment]
<img width="24" alt="import@2" src="https://user-images.githubusercontent.com/80846886/146197578-c499afc9-364d-41a9-924e-ac0db789a2a0.png">

@henryboldi adding a new image for import as background has changed
