### ISSUE TITLE
[Bug]: Txn details page - address character capitalization differs from etherscan

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#585]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Confirming send and receive address against etherscan

### What did not work?

Capitalization differed slightly, e.g. the "D" and "F" were capped in Tally but not on etherscan. nbd bt did make me second-guess if the address was correct or not

<img width="726" alt="Screen Shot 2021-12-11 at 5 48 32 PM" src="https://user-images.githubusercontent.com/7005061/145694156-07aae2dd-ff0f-4ab1-a644-67b4f1931541.png">

**Comment by Shadowfiend** [comment]
This is normal. We display a checksum address, etherscan does not. Open to the possibility we want to display a lowercases one, but that'll be a feature. 

Closing this for now.
