### ISSUE TITLE
Copy Address from top menu Name: 

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#593]
Add the ability to copy the current account address:

![Design for account address copying from a tooltip on the account avatar/name.](https://user-images.githubusercontent.com/80846886/145706686-ff1d3d8a-b230-45e9-9969-5b937f13a091.png)

The way this should work:
- If you hover over the name or the avatar, a tooltip appears after 1-2 seconds with the address and a copy icon
- The user can move their cursor down into the tooltip to copy the address by clicking. Clicking anywhere into the tooltip copies the address.
- If the user clicks on the name or avatar, even when the tooltip is open, the the account switcher menu still opens

**Comment by mr-michael** [comment]
Discussion @ https://www.flowdock.com/app/cardforcoin/tally/threads/6M3k8PXzvIYU4XgJIx6bPp87W3o

**Comment by Shadowfiend** [comment]
From that discussion, the way this is expected to work:

- If you hover over the name or the avatar, a tooltip appears after 1-2 seconds with the address and a copy icon
- The user can move their cursor down into the tooltip to copy the address by clicking. Clicking anywhere into the tooltip copies the address.
- If the user clicks on the name or avatar, even when the tooltip is open, the the account switcher menu still opens

**Comment by Naxsun** [comment]
Dropping this in here. Not sure if this is already part of the scope of this. The user suggested to also have a copy address option here.
https://discord.com/channels/808358975287722045/875438141610270740/951120858842275851

![image](https://user-images.githubusercontent.com/71384922/157640179-f6001024-c276-4362-a69a-499dcea32b6c.png)

**Comment by jagodarybacka** [comment]
Main part implemented and merged, linked issues are improvements.
