### ISSUE TITLE
Read-only accounts should show the "receive" button

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#601]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I entered an address for a read-only account. Later, I wanted to copy the address.

### What did not work?

I was unable to copy the address as there was no "receive" button or other account address affordance.

**Comment by henryboldi** [comment]
Given the existing design, it's tricky to simultaneously display our read-only wallet label and receive button. @VladUXUI, any ideas?

For now, could we just remove and read-only and display the button?

**Comment by mhluongo** [comment]
Of those two choices, I'd opt for leaving on the label for this release and skipping the button. We do need a solve here soon though @VladUXUI

**Comment by VladUXUI** [comment]
A fix for this would be to implement the copy address feature.
Since this is still a test environment and we don't know if people are going to use only their own addresses for read-only. I think it's safe to not have receive/copy yet, just o avoid people sending funds to wrong address.

**Comment by SJQuality** [comment]
The copy address feature is a thing now. closing. 
![image](https://user-images.githubusercontent.com/103908695/168388052-47ceb7c7-a5c9-424e-ad9f-71fe50fec1dc.png)
(This is a Read-only account)
