### ISSUE TITLE
Imported accounts are showing as read-only

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#602]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I imported an account via MetaMask 12-word recovery phrase.

### What did not work?

The account showed up as "Read-only" in the wallet page, and "Imported" in the account selector

![Screenshot from 2021-12-13 12-44-02](https://user-images.githubusercontent.com/427505/145862192-dc2055fd-22ff-459e-8527-2596ee2d99c0.png)

**Comment by mhluongo** [comment]
I found this building `fix-receive-page`, but I suspect it's also an issue in `main`?

**Comment by mhluongo** [comment]
More to reproduce:

I first added a read-only account to the wallet, then closed the wallet, came back, then imported a wallet via recovery phrase. Unsure whether this would happen if I'd gone the other way

**Comment by mhluongo** [comment]
Aha, looks like the `HIDE_SEND_BUTTON` feature flag is also hiding receive... and that read-only accounts don't have a way to receive assets, which is no bueno.

**Comment by mhluongo** [comment]
Closing as duplicate of #581

**Comment by henryboldi** [comment]
> and that read-only accounts don't have a way to receive assets, which is no bueno.

This part works as a new non-duplicate issue!

**Comment by mhluongo** [comment]
I think we've got it elsewhere, will confirm or re-open

**Comment by mhluongo** [comment]
Yep, I was circling the same issue heh. That one is tracked in #601
