### ISSUE TITLE
[Bug]: When I disconnect from a dapp, I need to refresh the page before my account disappears from dapp UI

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#608]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I wanted to disconnect from saddle and see that immediately reflected in the saddle UI ... 

### What did not work?

... after I disconnected (~20 secs at video), the saddle nav displayed that my wallet was still connected until I manually refreshed (~33 secs):

https://user-images.githubusercontent.com/7005061/145884597-9ceca3da-eacc-4d1f-95cf-b21aed7952a4.mov

**Comment by mr-michael** [comment]
Seen this on both saddle and yearn

**Comment by mr-michael** [comment]
Confirming still an issue as of latest build on yearn and curve and uniswap

**Comment by mhluongo** [comment]
Closed by #744
