### ISSUE TITLE
[Bug] Unable to log into onboard.js apps

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#625]
Build #1129

Tally no longer appears as a wallet option on yearn or curve (where it did previously!). In previous builds, curve displayed a Tally icon and yearn displayed a 'connected wallet' (or something) icon, which, when I clicked it, opened Tally.

yearn:
<img width="671" alt="Screen Shot 2021-12-14 at 5 53 23 PM" src="https://user-images.githubusercontent.com/7005061/146093498-4b1ba277-ecd1-4a0a-bb3c-193200cb93ba.png">

curve:
<img width="501" alt="Screen Shot 2021-12-14 at 5 53 18 PM" src="https://user-images.githubusercontent.com/7005061/146093520-4044013c-8d16-4069-874d-1f28b58c40c5.png">

This isn't a huge deal ... but since saddle doesn't open on Firefox, it effectively means we can't connect to any dapps. Also ... just tested Saddle on Chrome and when I click to log in with 'Tally', MetaMask and coinbase open but not Tally. 

<img width="889" alt="Screen Shot 2021-12-14 at 6 28 01 PM" src="https://user-images.githubusercontent.com/7005061/146095727-c1829274-38e0-4e63-846f-bf49f34a3801.png">

**Comment by creckhow** [comment]
Saddle opened on firefox for me, fwiw

**Comment by greg-nagy** [comment]
This happens because we turned of the `window.ethereum` overwrite 
Now only dApps that have explicityly added tally to their source code will be usable with tally. Which I assume is only saddle. 

That is until https://github.com/tallycash/extension/pull/620 lands.

**Comment by mr-michael** [comment]
On Brave (with no other wallets except installed), I'm unable to log into saddle:

https://user-images.githubusercontent.com/7005061/146225306-da2a02ea-bbb9-4270-a538-fa05b49ced4f.mov
