### ISSUE TITLE
[BUG] Users can still attempt to send tokens

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#626]
Build #1129

After clicking 'send' on main wallet tab, I am able to select a token from my dropdown and attempt to send it.

<img width="350" alt="Screen Shot 2021-12-14 at 6 10 18 PM" src="https://user-images.githubusercontent.com/7005061/146093902-32cadabf-a549-4eff-8ec6-e6933ca1b389.png">

<img width="387" alt="Screen Shot 2021-12-14 at 5 39 54 PM" src="https://user-images.githubusercontent.com/7005061/146093874-c7288b61-7758-4ccd-afe1-2152dab66c1a.png">

If I click on ETH from the main wallet tab and click 'Send' ... I can still use the dropdown menu to select a token

<img width="416" alt="Screen Shot 2021-12-14 at 6 11 30 PM" src="https://user-images.githubusercontent.com/7005061/146094080-012b70c4-bc4b-486d-bf11-7d65deac89c5.png">

<img width="433" alt="Screen Shot 2021-12-14 at 6 11 33 PM" src="https://user-images.githubusercontent.com/7005061/146094094-87c8f36e-fbbe-43f3-a6f9-f4eb7fd1d019.png">

**Comment by henryboldi** [comment]
Fixed in #614, but not merged yet

**Comment by mr-michael** [comment]
fwiw just tested on latest build ... I can send KEEP (now with gas!) but I just beachball on the final sign view

<img width="388" alt="Screen Shot 2021-12-14 at 9 50 12 PM" src="https://user-images.githubusercontent.com/7005061/146116454-123d56d8-c61c-442c-b54a-3f3bbdd4b7dc.png">

<img width="384" alt="Screen Shot 2021-12-14 at 9 50 38 PM" src="https://user-images.githubusercontent.com/7005061/146116455-d08af613-58a6-4e5c-9d2e-dd709c97cb16.png">

<img width="399" alt="Screen Shot 2021-12-14 at 9 51 04 PM" src="https://user-images.githubusercontent.com/7005061/146116458-cc15e6e5-18ee-4cc6-b505-09e72482875f.png">
