### ISSUE TITLE
[BUG] 'Paste' button on SEND doesn't work 

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#627]
Build #1129

I click paste with something in my clipboard and nothing appears in to field

<img width="141" alt="Screen Shot 2021-12-14 at 5 52 52 PM" src="https://user-images.githubusercontent.com/7005061/146094387-bc98a56f-00fe-4083-8772-36b981522252.png">

**Comment by henryboldi** [comment]
Fixed in #614
