### ISSUE TITLE
[BUG] Unable to send ETH b/c of gas selection issues

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#629]
Build #1129

I'm unable to send ETH b/c of gas selection issues:

1 - Gas initially defaults to zero

<img width="373" alt="Screen Shot 2021-12-14 at 6 19 51 PM" src="https://user-images.githubusercontent.com/7005061/146094882-23e19e99-051c-48fb-9ce5-dabb2fa03d91.png">

2 - I click gear icon to set gas ... gas limit is set to 21000 ... I click to increase it but 'save' button does not work. I need to click "x" to close pop-up.
 
<img width="399" alt="Screen Shot 2021-12-14 at 6 20 23 PM" src="https://user-images.githubusercontent.com/7005061/146094980-331fd1ea-079c-48e4-b93a-6b9dfbaac6e5.png">

3 - I am able to submit txn with no gas and txn is stuck in pending

<img width="360" alt="Screen Shot 2021-12-14 at 6 21 27 PM" src="https://user-images.githubusercontent.com/7005061/146095052-a9a8776e-4108-461f-8850-9a23622285f0.png">

<img width="375" alt="Screen Shot 2021-12-14 at 6 22 32 PM" src="https://user-images.githubusercontent.com/7005061/146095099-67aecaf4-e925-431d-86e1-29d420d032b3.png">

**Comment by henryboldi** [comment]
Likely fixed by #623

**Comment by creckhow** [comment]
I experienced all of this too, then tried clicking into the pending (0 gas) tx. The UI allows me to click into the tx, and even out to etherscan.
<img width="388" alt="Screen Shot 2021-12-14 at 6 43 26 PM" src="https://user-images.githubusercontent.com/74791142/146104431-2a58e25b-2428-4af2-8a6c-dc4ac881b676.png">

Here's the [etherscan link](https://etherscan.io/tx/0x6c2240cb1d61048f8bae58fd2f3e0198676c5b642c2297231207e9b169991574), granted I don't do as much fucking around on the blockchain as you guys do, but i've never seen a tx that's been submitted to the chain just *not* show up as a tx hash on etherscan, usually i'd see it there, pending forever
