### ISSUE TITLE
Copy buttons should give user feedback that they copied

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#630]
The only way to be sure the button actually did the thing is to paste elsewhere. Some affordance (eg button changing briefly from "Copy" to "Copied!") would go a long way.

**Comment by mhluongo** [comment]
This doesn't *seem* like a big deal, but I gave it a medium as the clipboard has security implications around phishing, sniffing, etc. In cryptolandia we want to help users know what's in their buffer

**Comment by VladUXUI** [comment]
100% agree. Would advice we use a snackbar for this with "address copied to clipboard" just to keep consistency with other similar actions
