### ISSUE TITLE
Typos/Capitalization

### ISSUE THREAD

**Issue by karlmoll** [tallycash/extension#634]
Metamask-> MetaMask on Explore/Import onboarding page

Contract interaction -> Contract Interaction on Activity Feed
<img width="391" alt="Screen Shot 2021-12-14 at 4 14 52 PM" src="https://user-images.githubusercontent.com/8355836/146110530-0c66d2da-7260-41e3-9970-527a241d8e26.png">

**Comment by karlmoll** [comment]
I did indeed :)

**Comment by mr-michael** [comment]
Got it ... Feels like we should probably do a global audit here post-CE.
