### ISSUE TITLE
"advanced" tab next to details when signing tx is blank

### ISSUE THREAD

**Issue by creckhow** [tallycash/extension#637]
On this transaction details page w/ estimated network fee, before signing: 
<img width="349" alt="Screen Shot 2021-12-14 at 9 32 24 PM" src="https://user-images.githubusercontent.com/74791142/146112563-f60a4662-8175-4796-bc9e-20bd19532825.png">

When you toggle over to "advanced" it shows nothing: 
<img width="362" alt="Screen Shot 2021-12-14 at 9 32 31 PM" src="https://user-images.githubusercontent.com/74791142/146112636-bd97f81a-2ad8-4301-86d9-3b680629aff8.png">

**Comment by henryboldi** [comment]
Fixed here https://github.com/tallycash/extension/commit/8895887e83251b2c23dc727ac133e32b09fd4141
