### ISSUE TITLE
Add 'default wallet' to onboarding + settings

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#638]
Onboarding - https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=4747:124256#133319556
Settings - https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=3589:170309#133319616

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/146179778-61258147-9b05-4b80-820e-4685635f3c32.png)
![image](https://user-images.githubusercontent.com/80846886/146179844-a247a3e0-b5e0-4739-80bf-75d55c636a44.png)

Adding screenshots as well
