### ISSUE TITLE
Disable 'Advanced' tab from sending

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#640]
Unless this will be populated for signing txns other than eth or erc20 sends?

<img width="378" alt="Screen Shot 2021-12-14 at 9 53 18 PM" src="https://user-images.githubusercontent.com/7005061/146116654-4d0062b3-2609-4c71-9dc8-c8980836f629.png">

<img width="387" alt="Screen Shot 2021-12-14 at 9 53 21 PM" src="https://user-images.githubusercontent.com/7005061/146116656-ea4cbb84-f949-4aa9-bc13-7f01943692cf.png">

**Comment by henryboldi** [comment]
Crap, this is a one line change. I'll fix this.
