### ISSUE TITLE
Extract address and number formatting to a shared package

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#647]
We don't want this stuff to just live in `background` or `ui`, as we don't want to suffer pulling in the whole package for common formatting. Instead, let's build up a `@tally-ho/shared` package or similar.

**Comment by Shadowfiend** [comment]
Feels like the package and refactor are separate concerns. We have a lot of package juggling to do to get things a little more streamlined. 

On the other hand we're slicing addresses and lowercasing them in a million places 😅

**Comment by mhluongo** [comment]
Agreed, these are almost orthogonal... accept the lack of an ordained place that has kept us from doing this better, IMO.

Down to split this up however as long as it happens :)

**Comment by wojciech-turek** [comment]
#653 implements formatting decimal number and addresses.
