### ISSUE TITLE
Transaction not sending/broadcasting

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#651]
Tried to send ETH twice, each transaction is blocked in pending.
I got a hash but no information on etherscan. Assuming it's not being broadcasted.

**Comment by wojciech-turek** [comment]
Did you have 0 gas on the send page or was it populated correctly?

**Comment by VladUXUI** [comment]
0 gas in send page.

**Comment by VladUXUI** [comment]
Using the last main that was pushed 2 hours ago

**Comment by wojciech-turek** [comment]
Do you have blocknative API key added in your env?

**Comment by Shadowfiend** [comment]
This is a build issue. Fix on the way.
