### ISSUE TITLE
Missing icon for imported accounts

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#654]
Design @ https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD?node-id=4100:129831#133567429

<img width="391" alt="Screen Shot 2021-12-15 at 10 53 39 AM" src="https://user-images.githubusercontent.com/7005061/146221461-766e9616-f533-418b-8ecf-cb39a0a2a1e1.png">

**Comment by Shadowfiend** [comment]
Duplicate of #582.
