### ISSUE TITLE
Not displaying USD or ETH amount users are paying for gas

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#656]
<img width="400" alt="Screen Shot 2021-12-15 at 11 10 40 AM" src="https://user-images.githubusercontent.com/7005061/146222990-5040d612-9964-4013-ae2e-73da76b83cb9.png">

<img width="398" alt="Screen Shot 2021-12-15 at 10 55 06 AM" src="https://user-images.githubusercontent.com/7005061/146223111-9b71fc51-43b2-42bd-bd1a-5341e31ddf6e.png">

<img width="397" alt="Screen Shot 2021-12-15 at 11 10 47 AM" src="https://user-images.githubusercontent.com/7005061/146222996-db7910f7-111c-4262-8059-12ad2a5cf431.png">

**Comment by SJQuality** [comment]
We show price now on Sign page. Closing. 

![image](https://user-images.githubusercontent.com/103908695/168387002-27de57ce-4277-4534-8ed7-9c5cd1440108.png)
