### ISSUE TITLE
Can't connect if toggle is off. MM installed

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#660]
If i disable default wallet it disconnects me and it is not seeing Tally or MM anymore.
Tested with uniswap and saddle

![image](https://user-images.githubusercontent.com/80846886/146235663-bd3fdc59-95bc-4533-a8e2-a7f493a79e16.png)

**Comment by greg-nagy** [comment]
@VladUXUI Please try this again after you restart the extension. I suspect this to be a performance issue with the redux store.

You can do that om `chrome://extensions` and hit reload icon on Tally.

**Comment by VladUXUI** [comment]
@greg-nagy I tried the refresh and still has same behaviour

**Comment by greg-nagy** [comment]
@VladUXUI 

This is how it works for me. What do I do differently from you? 

![CleanShot 2021-12-15 at 19 30 35](https://user-images.githubusercontent.com/7690112/146244668-0350c2ee-77af-4f69-b6fe-98015d63a6de.gif)

**Comment by greg-nagy** [comment]
The difference might be related to the local fix I have and forgot about and is not pushed yet ...:D 

Sorry :D

**Comment by greg-nagy** [comment]
This is fixed with: https://github.com/tallycash/extension/pull/620

Not closing so we can double check when the PR has landed.

**Comment by greg-nagy** [comment]
actually closing it. let's reopen if it is not working
