### ISSUE TITLE
Signing transactions causes extension to crash and not able to re-open

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#663]
On Firefox, I connect to balancer and attempt to swap ETH for DAI. I beachball forever on the send screen. After that I am unable to re-open Tally on any tab (a vertical line appears instead - see screens below). Shortly after that, Firefox freezes and crashes/closes. I open it again and it freezes so I force quit. I re-open and reinstall Firefox and it works fine.

<img width="329" alt="Screen Shot 2021-12-15 at 12 50 21 PM" src="https://user-images.githubusercontent.com/7005061/146241093-4a884458-9aca-4d10-ac83-b06e8cf9e068.png">
<img width="386" alt="Screen Shot 2021-12-15 at 12 50 08 PM" src="https://user-images.githubusercontent.com/7005061/146241096-2033f809-dea2-49da-91d0-a4c801153b4d.png">

On Chrome, I attempt a trade on Uniswap. I once again beachball. After this I am no longer able to open Tally. I remove the extension and attempt to load it again but it will not load. I exit Chrome and try loading it. That works and now I can open Tally.

**Comment by mhluongo** [comment]
Closed by #673
