### ISSUE TITLE
Dapp logos not appearing in Firefox

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#664]
They appear fine on Chrome

<img width="414" alt="Screen Shot 2021-12-15 at 12 44 29 PM" src="https://user-images.githubusercontent.com/7005061/146241467-37c24342-bb1a-4133-8779-1149a504fafb.png">
<img width="385" alt="Screen Shot 2021-12-15 at 12 44 57 PM" src="https://user-images.githubusercontent.com/7005061/146241470-4d330f4f-1482-4eb6-8830-5033d1af6872.png">
<img width="391" alt="Screen Shot 2021-12-15 at 12 45 18 PM" src="https://user-images.githubusercontent.com/7005061/146241471-0c26b3fa-c25a-42ad-a23f-109ed019b347.png">
<img width="385" alt="Screen Shot 2021-12-15 at 12 45 22 PM" src="https://user-images.githubusercontent.com/7005061/146241472-e15da23c-0c3f-41d8-ba3b-ca416bc19cc8.png">

**Comment by SJQuality** [comment]
This is old ticket. I see Yearn's logo. closing.
