### ISSUE TITLE
Update toggle button copy

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#667]
"Use Tally as default wallet" [radio button]

"Tally will open any time you connect to a dApp—even if you select MetaMask. For some dApps, enabling this feature is the only way you'll be able to try Tally!"

<img width="415" alt="Screen Shot 2021-12-15 at 1 00 10 PM" src="https://user-images.githubusercontent.com/7005061/146242294-3d2e05b2-9e6f-455d-84b2-8042b89a5ff1.png">

**Comment by greg-nagy** [comment]
done here, just there was no new zip.

https://github.com/tallycash/extension/pull/620/commits/3a31c817f547daf2c409fb9e5bfbecac44ea22ef

**Comment by VladUXUI** [comment]
@greg-nagy Was info icon + text added?

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/146265311-058f5327-3270-4fd5-b67a-a028d551337c.png)

We technically have a reusable component for this. So maybe not a big lift
