### ISSUE TITLE
Contract interactions are show under ETH activities (single-asset page)

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#676]
Opening this for discussion of this behavior... it seems like a bug to me, especially if the value of a transaction is 0 ETH.

Introduced in #675

**Comment by Shadowfiend** [comment]
It wasn't introduced in that PR, it's just that before it we also included all other transactions there 😅

**Comment by mhluongo** [comment]
Lol fair enough. Still a handy reference though. I'm going to snipe this.
