### ISSUE TITLE
Approval tx lacking details

### ISSUE THREAD

**Issue by krisjpi** [tallycash/extension#680]
I know it's an approval, but there are no details provided within the wallet with the transaction request. Would be nice to have more context to the tx.
![Uniswap Interface - Detail - Approve](https://user-images.githubusercontent.com/41163644/146326034-77efa70c-6b7b-4563-8069-de429027ce00.png)

**Comment by wojciech-turek** [comment]
In progress in #730

**Comment by mhluongo** [comment]
Is #730 related? I'm expecting this shows approval-specific tx details, not just the amount

**Comment by mhluongo** [comment]
I think this is a duplicate of

https://github.com/tallycash/extension/issues/727

**Comment by wojciech-turek** [comment]
Ah I see, yeah in #727 its more clear what the purpose and expected outcome is. I think this one is a duplicate as well.
