### ISSUE TITLE
Attempt to create new issue leads to a page with broken discord links :) 

### ISSUE THREAD

**Issue by ElderOrb** [tallycash/extension#683]
I was going to create an issue about windows build but found this:

![image](https://user-images.githubusercontent.com/23638/146337536-24b8e76a-f366-4db7-8ebe-d469608915ea.png)

Following any of the links results in this: 

![image](https://user-images.githubusercontent.com/23638/146337758-d15d0c30-03bd-4579-b9f2-6ce94f1dff0c.png)

**Comment by mhluongo** [comment]
Fixing this, thanks @ElderOrb
