### ISSUE TITLE
Wallet balances not updating after confirmed swap

### ISSUE THREAD

**Issue by krisjpi** [tallycash/extension#696]
Swapped a small amount of KEEP for ALCX on Uniswap. Waited for a while to give the wallet time to update ETH balance and pull ALCX, but it did not. Screenshot with Etherscan for balance reference. This was reflected in both Assets and total account balance areas. The KEEP that was swapped WAS reflected in the ERC20 balance.
![Tally Wallet Balance Updates redacted](https://user-images.githubusercontent.com/41163644/146446472-d40e6d0d-32dd-4a89-99be-4341f6cfbb7d.jpg)
![Total Balance](https://user-images.githubusercontent.com/41163644/146446475-e43b8459-5199-4fa5-8ba0-0023866498c7.png)

**Comment by mhluongo** [comment]
I can't tell if this is because of our balance checking or that ALCX isn't on a token list, or both. Regardless, proposed fix is multi-part.

- [ ] Custom token list → I've started one at https://github.com/tallycash/token-list
- [ ] Popular DEX transactions should force us to look up contract metadata in the resulting asset

**Comment by cairomassimo** [comment]
I just had a similar issue after wrapping ETH to WETH on Uniswap: the WETH would not show up in assets for a while, even after transaction confirmation

**Comment by mhluongo** [comment]
@Shadowfiend fixed most of this, with the exception that we also need to pull metadata from tokens we don't already have in a list. I made an issue for it

https://github.com/tallycash/extension/issues/1021

**Comment by andyjagoe** [comment]
Same here. I just sent DAI to my Tally wallet address and it still hasn't showed up in the wallet after 70 block confirmations. The address previously had no DAI.

I'm using Tally 0.11.2 on Brave 1.35.104 on MacOS 12.1.

**Comment by mhluongo** [comment]
This should be fixed, for swaps, wraps, and sends.
