### ISSUE TITLE
Arbitrum support

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#7]
- [x] Include Arbitrum in the default network selection dropdown
  - [x] Refactor `ChainService` to work with Alchemy + Arbitrum
  - [x] Refactor `IndexingService` to work with Alchemy + Arbitrum
  - [ ] Include Arbitrum on Kovan
- [x] Include Arbitrum-specific token lists
- [x] Recognize Arbitrum bridge transactions in wallet activities
- [x] Recognize Arbitrum bridge transactions when signing
- [x] Support 0x on Arbitrum mainnet and Kovan
- [ ] Include a "send to Arbitrum" on Ethereum mainnet and Kovan that uses [the Arbitrum bridge](https://developer.offchainlabs.com/docs/bridging_assets#bridging-erc20-tokens)

**Comment by puppycodes** [comment]
I'd like to do some work breakdown on this and perhaps convert into a milestone with these as issues. Seems too large for a single issue?

**Comment by greg-nagy** [comment]
The ones checked have been done in #2287 
Created an additional issue #2377 (We don't have a design nor we have planned to do this afaik)

Kovan is no longer relevant as I understand
https://docs.alchemy.com/reference/arbitrum-api-quickstart#what-testnet-should-i-use-for-arbitrum
https://www.alchemy.com/the-merge
https://docs.alchemy.com/changelog/future-deprecation-of-ropsten-kovan-and-rinkeby
