### ISSUE TITLE
Had to import my seed phrase 3 times

### ISSUE THREAD

**Issue by chlolands** [tallycash/extension#704]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I was trying to set up my account on the latest build. I imported my seed phrase 3x and it said it was invalid all three times...
finally, a fourth time I was able to import. 

### What did not work?

importing seed phrase

### Version

OG Edition v0.0.7

**Comment by henryboldi** [comment]
@chlolands, is it working on the latest build for you? I haven't encountered this one

**Comment by mhluongo** [comment]
Could there have been an extra space somewhere? I think we handle that now...?

**Comment by henryboldi** [comment]
>  I think we handle that now...?

Yes, and improved in https://github.com/tallycash/extension/pull/706/commits/ec2d114c54df0969e938e5fa07299ca9ca34c314 (included in 0.9.1).  Previously it didn't trim before checking if valid. After that commit, it does

**Comment by wojciech-turek** [comment]
@henryboldi can we close this issue?

**Comment by mhluongo** [comment]
Closing as unable to replicate. @chlolands if you see this again let us know!
