### ISSUE TITLE
Dapp connections - Forcing connection to single read-only account

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#705]
tl;dr I have an imported account (Atos) selected and click to connect to a dapp.

Dapp displays that I am connecting with my imported wallet on the confirmation pop-up, but then connects with my owocki.eth read-only account.

I continue to retry and am unable to connect with either my imported account or other read-only accts.

Tested on uniswap, balancer, yearn, sushi, and saddle.

https://user-images.githubusercontent.com/7005061/146465075-60c758ed-3e08-4569-a54a-4df8f4cc5808.mov

https://user-images.githubusercontent.com/7005061/146465057-36c0d3f5-4a40-44bb-bca1-f9acc740fe4c.mov

**Comment by mr-michael** [comment]
Noticed another related issue.

I'm logged in as alisha.eth (read-only). I log into Curve. But I am connected to Atos, my imported account (note ETH balance in Curve reflects what Atos has, not Alisha):

https://user-images.githubusercontent.com/7005061/146468872-53f85cf7-90c3-4eab-933c-11d0ac3a513f.mov

**Comment by henryboldi** [comment]
Also, the connected lighting bolt icon displays for every account, even if it's only connected to one

**Comment by Shadowfiend** [comment]
Things we need to do here:
- In the ProviderBridgeService, `eth_accounts` and `eth_requestAccounts` should both return the permission's address.
- In the same service, the sign requests should check the from address in the payload and reject if the address is not the one that is allowed in the permission; if from is not set, it should be set here to the address allowed in the permission. 
- The permission address field should be an array (migration? Depends what we want to do with the OGs, hopefully not), even though we populate with just one for now. 
- SharedCurrentAccountInformation needs to become SharedAccountInfromation and become parametrized, probably with an AccountTotal for simplicity. SignTransaction should look up the account for this header by the `from` address in the transaction details. 

This isn't all future proof to multiple accounts per dapp, but it gets us close. Going to hand it to @greg-nagy for when he gets started.
