### ISSUE TITLE
ENS avatars not always displaying

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#711]
Brantly yes, Alisha and Owocki no

<img width="383" alt="Screen Shot 2021-12-16 at 6 23 54 PM" src="https://user-images.githubusercontent.com/7005061/146469495-98a2c485-c036-4bda-8de6-006cb54cd8d0.png">

<img width="378" alt="Screen Shot 2021-12-16 at 6 35 41 PM" src="https://user-images.githubusercontent.com/7005061/146469496-3c0978f7-866f-4f74-ab5a-3f762ad90268.png">

**Comment by rootial** [comment]
there is no avatar setup for alisha's sub-domain as you can see there 
https://app.ens.domains/name/ens.alisha.eth/details

**Comment by mhluongo** [comment]
Indeed, this is the correct behavior @mr-michael.

There are some ENS names with avatars set that might not show, but I believe they're covered by #512
