### ISSUE TITLE
KEEP token gfx and balance take awhile to load

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#712]
~10 mins? Longer than (most) other tokens

<img width="367" alt="Screen Shot 2021-12-16 at 6 18 25 PM" src="https://user-images.githubusercontent.com/7005061/146469566-6d4a9b73-a422-4bed-8ba3-14ce82961b11.png">

<img width="360" alt="Screen Shot 2021-12-16 at 6 18 38 PM" src="https://user-images.githubusercontent.com/7005061/146469567-0c8bc16e-3b38-4d1b-a864-22dfe0fbe934.png">

**Comment by mhluongo** [comment]
The balance is already there — this is about the price I think?

**Comment by SJQuality** [comment]
@mr-michael is this still an issue for you?

**Comment by mhluongo** [comment]
We're no longer having price issues. Occasionally we have asset metadata issues — that image one is tracked in #1898
