### ISSUE TITLE
Should first/last chars of address replace dog name in nav?

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#714]
<img width="151" alt="Screen Shot 2021-12-16 at 7 40 03 PM" src="https://user-images.githubusercontent.com/7005061/146470256-c85fdcdb-985a-4668-b206-165c64fa029d.png">
<img width="141" alt="Screen Shot 2021-12-16 at 7 39 55 PM" src="https://user-images.githubusercontent.com/7005061/146470257-2e441cc4-2eac-4ca8-82c8-f708fc3785f6.png">

**Comment by VladUXUI** [comment]
I've also been feeling like i need to see the address.
If we would have rename function i don't think i would miss it as much.

I'm good on adding the address and test the name later after we have rename implemented.

@henryboldi Do you need anything from me here?

**Comment by VladUXUI** [comment]
Should users with ENS be shown address as well?

**Comment by mhluongo** [comment]
> Should users with ENS be shown address as well?

I don't think so. Mostly I can just copy/paste my ENS name around and it's more recognizable than the hex address.

**Comment by henryboldi** [comment]
> @henryboldi Do you need anything from me here?

Nope, all good!
