### ISSUE TITLE
Allows empty wallets to make payable contract calls

### ISSUE THREAD

**Issue by Battenfield** [tallycash/extension#718]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

version v0.9.0

I was trying out the signing process with an empty wallet. The wallet allowed me to make a `payable` contract call
<img width="375" alt="Screen Shot 2021-12-16 at 10 03 00 PM" src="https://user-images.githubusercontent.com/7051522/146497547-10072ea3-f8f2-4037-a3fa-b45735092b2f.png">
<img width="373" alt="Screen Shot 2021-12-16 at 10 02 14 PM" src="https://user-images.githubusercontent.com/7051522/146497549-e8c63ddc-414b-4494-9755-8e3716d121f9.png">

### What did not work?

When I sent a tx with an empty wallet, Tally gave back an etherscan link to a transaction for .77ETH + gas. 

It still shows the pending transaction in the Tally UI hours later. Etherscan shows the tx as unable to locate this TxnHash. I'm unsure if the tx was actually broadcast or if tally just errored out behind the scenes.

I didn't pick up the console and now it fails to repro, potentially due to the pending tx

### Version

OG Edition v0.0.7

**Comment by VladUXUI** [comment]
This seems to be related to this issue
https://github.com/tallycash/extension/issues/525#issue-1073637464

**Comment by VladUXUI** [comment]
Humm, maybe not afterall. 
@Battenfield was this a send transaction from Tally or from a DApp connection?
If it was from Tally, you should have gotten an error with insufficient balance.

**Comment by Battenfield** [comment]
I was connected to an nft dapp, and was able to "send" the transaction

**Comment by Shadowfiend** [comment]
Possible we broadcast but the node rejected the tx and that didn't bubble out correctly. We haven't yet implemented the note that a tx is expected to fail (though the plumbing is there), so probably that would have flagged it. 

Actually I think if the tx fails our gas estimation may fail, and we may submit the tx with 0 gas limit so we get an intrinsic gas too low error from the node. 

Will poke!

**Comment by mhluongo** [comment]
Closed by #1689
