### ISSUE TITLE
Properly display infinite token approvals

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#726]
Compliant "infinite" ERC-20 approvals use `type(uint256).max - 1` as a special value to denote an infinite approval. We should display "Infinite" in the approval signature and wallet activity pages instead of including that ridiculously long number :)

- [x] Display infinite approval in activity list.
- [x] Display properly-styled infinite approval in sign transaction page (see https://github.com/tallycash/extension/issues/726#issuecomment-999431175). Note: should branch off of https://github.com/tallycash/extension/pull/1053 if it is not yet merged.

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/146733472-dc7c8ead-36ed-4b46-96ea-11f287f3a24e.png)
Do we feel like infinite should be marked as an error? maybe a exclamation mark in front or written with red?

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/147071331-fc37976c-274f-4063-801b-983690ab3966.png)
Hopefully red is enough, adding an icon just messes things up.
![image](https://user-images.githubusercontent.com/80846886/147071369-0cabb1a1-fc29-45e8-8253-1f2d0091387e.png)
This tooltip could probably deserve a re-write

**Comment by VladUXUI** [comment]
I feel like i want to add an option to only approve the amount the current transaction is using.
This means that editing won't be done inline, but would open a modal/pop-up.

What do you think?

**Comment by mhluongo** [comment]
> I feel like i want to add an option to only approve the amount the current transaction is using.

This sounds great, but it'd be really, *really* hard to implement right now... dApps usually send each transaction separately, so while the wallet is signing the approval tx we don't know what the token amount will need to be. Also for some transactions, the only way to know the token amount needed is to run it.

For now, custom amounts inline is probably the best we can swing. For `permit()` and other signature-based approval schemes, though, we might be able to do better (eg Swap and Earn).

**Comment by Shadowfiend** [comment]
@VladUXUI also missing here is how these render in the activity list.

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/151924284-546292d5-900a-409b-b75e-f884bf1a2bad.png)
Let's spell it out for consistency sake

**Comment by Shadowfiend** [comment]
Actually I may have been too trigger-happy here. I believe there's a missing piece here, which is to highlight the spend amount in red in the sign page if this is an infinite approval.

I'll plan to tackle this next week to give the latest `SignTransaction` refactor a chance to settle.

**Comment by SJQuality** [comment]
I'm don't understand this one. I don't know how to initiate an "infinite approval". Also, I think the UI for this has since changed assuming I'm looking in the correct spot.
![image](https://user-images.githubusercontent.com/103908695/168383740-2a0094a4-77b6-461e-9fd3-d72a2162892c.png)

**Comment by 0xDaedalus** [comment]
In order to reach the `Approve Asset` screen you'll need to attempt to swap an asset that the wallet you're using has never approved before.  I think the test wallet has some STX in it right now which is most likely not approved on uniswap or on our internal swap feature.

**Comment by henryboldi** [comment]
Closed by https://github.com/tallycash/extension/pull/1133
