### ISSUE TITLE
CPU usage high on initial load

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#739]
### What browsers are you seeing the problem on?

Firefox, Chrome

### What were you trying to do?

Read this with Jony Ive's accent and inflection:

Enjoy Tally with _stunning_ performance.

### What did not work?

> Does anybody else expereince significant slow down in the extension start? Or is it just me?
– @greg-nagy 

> Wow, in Firefox whenever we do the initial sync after adding an account it makes my CPU spike and my laptop fans spin like crazy
![Screenshot from 2021-12-16 15-54-16](https://user-images.githubusercontent.com/1918798/146961058-1fa07503-10d5-4103-9279-07976ad520f7.png)
– @itsrachelfish 

### Version

OG Edition v0.0.7

**Comment by henryboldi** [comment]
This seems concerning...
<img width="744" alt="RAM" src="https://user-images.githubusercontent.com/1918798/151860175-3cf30ca6-3b9d-4cb7-8d93-d90b458472b6.png">

**Comment by SJQuality** [comment]
@henryboldi @greg-nagy I'm not seeing this issue. Can you try again?

**Comment by greg-nagy** [comment]
I think the most important parts are handled here. I still have a PR that somewhat relates to this, so I think it's safe to close.
