### ISSUE TITLE
Small(ish) UI improvements

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#742]
1. Add mouse over for name/address as well. Feels a bit strange to hover over the address but only the avatar has mouse over effect![image](https://user-images.githubusercontent.com/80846886/147073668-70e1cb12-eebd-427f-b035-c6d9e181c99a.png)

2. Truncate token approval. Use infinite if the amount is actually infinite
![image](https://user-images.githubusercontent.com/80846886/147074087-eec0d9b0-e5a8-41d6-8731-2e4329593b05.png)

3. Tx details should show what type of transaction it is.
![image](https://user-images.githubusercontent.com/80846886/147074228-91140359-2758-48cb-a194-51c44ca90d78.png)
![image](https://user-images.githubusercontent.com/80846886/147074418-c8eedda7-0cd1-47d3-9453-a547ad2c8e9c.png)

4. Tx details should show name or ENS were available (Image from above)
5. Tx details needs to use the 16px icon for external .
<img width="16" alt="external_16px" src="https://user-images.githubusercontent.com/80846886/147075934-9ab9a3a7-ae8d-451f-9e3a-82834e931a0c.png">

6. Main menu using old icons. Also, any chance we could add the label on hover/active?:D
[MainMenu-Icons.zip](https://github.com/tallycash/extension/files/7761906/MainMenu-Icons.zip)

7. Mouse over for gas selection seems to shrink the box and move the elements inside.
![image](https://user-images.githubusercontent.com/80846886/147077379-3d230398-42ac-401a-ad10-c722559af24e.png)

8. Let's add an overlay to all pop-overs (accounts/gas...) Green-120 at 80% alpha. 
For better content focus, and this way we also avoid people clicking on avatar when gas selector is open.
![image](https://user-images.githubusercontent.com/80846886/147077824-56b56b1a-1ef9-41b7-a9c4-ea7b42d30681.png)

**Comment by henryboldi** [comment]
Thank you for putting this together, @VladUXUI! ❤️

<hr/>

Quick question,

> Tx details should show what type of transaction it is.

Currently, I don't think there's enough room for longer transaction types like "Contract Interaction." In this case, do you have thoughts on what to do from a design perspective?

**Comment by VladUXUI** [comment]
riiiight, i don't have a decent fix for it yet.
![image](https://user-images.githubusercontent.com/80846886/147204014-9003969f-6eb6-458f-90b5-98ebc2edad5b.png)
I can squeez them in by changing icon size + font size, but it's not a good fix, nor would it work long term.
Need to separate the title from the link, or maybe showing just the new tab icon is enough.
I made myself a ticket to rethink the tx details page a bit, so let's leave it as is for now.

**Comment by henryboldi** [comment]
I believe this ticket has been superseded by more recent UX QA tickets
