### ISSUE TITLE
Once a dApp connection times out (Uniswap) its not possible to reconnect

### ISSUE THREAD

**Issue by wojciech-turek** [tallycash/extension#757]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

After connecting to a dApp, and leaving the connection running it will eventually timeout and you will need to connect wallet again.

### What did not work?

The issue is that if you click "Connect Wallet" after a timeout you get stuck on the loading screen below

![image](https://user-images.githubusercontent.com/61434499/147479992-c4f83bf6-35fa-4aa3-b81d-897ede98b99d.png)

The only solution I found so far is either reinstall the extension or completely shut down the browser.

**Comment by mhluongo** [comment]
Haven't seen this in quite some time. Please reopen it if you see it again!
