### ISSUE TITLE
Cannot add account from seed

### ISSUE THREAD

**Issue by MatthieuScarset** [tallycash/extension#769]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/925676162246647868

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Add an existing account from seed

### What did not work?

Simply does not work. 

Import button become a little bit more shadow and that's all.

Nothing happens.

### Version

Community Edition v0.9.1

**Comment by mhluongo** [comment]
Hey @MatthieuScarset, we haven't been able to reproduce this on our side... can you update to the latest extension (`v0.10.0`) and let us know if you're still seeing it?

Here's a [mnemonic we use in testing](https://github.com/tallycash/hd-keyring/blob/main/test/keyring.test.ts#L23)... maybe you can replicate with that and give us more details? Note that you should uninstall after replication, don't want any accidents using a compromised seed.

**Comment by MatthieuScarset** [comment]
Hi @mhluongo thank you for your answer. I've discussed the issue in Discord and it seems that Tally simply does not accept seeds phrase of more than 12 words. 

I am trying to use a wallet created from a Ledger - therefore with a 24 words seed.

I understand that it is possible to import an account only if it was created with Metamask. 

Feel free to close this ticket if you think it is not relevant to accept other seeds.

I would still like to suggest two things: 
- Indicate that the seed length is maximum 12 words 
- Display error messages to the end user when seed is not correct - viewing a frozen window is not really pleasant

**Comment by mhluongo** [comment]
Thanks, agreed! Just opened [an issue](https://github.com/tallycash/extension/issues/779) where we'll follow up.
