### ISSUE TITLE
Make it clear that we're expecting a 12-word recovery phrase imported from MetaMask

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#779]
In the onboarding, we should show...

- [ ] the 12-word requirement in the copy
- [ ] the 12-word requirement as a validation error
  - [ ] the page shouldn't [freeze up](https://github.com/tallycash/extension/issues/769) when other recovery phrases are added

**Comment by henryboldi** [comment]
Perhaps with a little love https://github.com/tallycash/extension/pull/723's feature flag can be turned on? @mhluongo

**Comment by mhluongo** [comment]
Good point. I wanted @VladUXUI to pull it into the design of the next version of the onboarding flow... we're ready to turn this feature on when you either give us a tweaked plan or give the go-ahead @VladUXUI. Would also like to get @mr-michael's eyes on it
