### ISSUE TITLE
any design or plan of this setting icon actions?

### ISSUE THREAD

**Issue by izayl** [tallycash/extension#787]
https://github.com/tallycash/extension/blob/7f0b7cae6245ac95599a4eac7490de729936fbe8/ui/components/Shared/SharedPanelAccountItem.tsx#L56

I'm willing to add a function to delete account in tally wallet list, and I found the code has a `setting icon` element, but not implement any features on it, did any plan or design about this

**Comment by henryboldi** [comment]
I bet @VladUXUI has some comments on this one :)

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/147965773-320cc346-3cb1-4a13-a29d-6a4cbddf162a.png)
This was the initial plan for it. But for now we will only have Remove address.

**Comment by VladUXUI** [comment]
But yeah, the remove address button should be shown only if user clicks on the menu/settings button. Otherwise we risk some frustrating/annoying miss-clicks

**Comment by izayl** [comment]
If no one is woking on this design code implement, I'm willing to implement the `remove` feature first

@henryboldi

**Comment by mhluongo** [comment]
All you @izayl!

**Comment by izayl** [comment]
It's there any figma link I can reference @mhluongo

**Comment by mhluongo** [comment]
Yes! @VladUXUI WDYT?

**Comment by mhluongo** [comment]
Here's a bigger screenshot in the meantime

![Screenshot from 2022-01-04 11-54-55](https://user-images.githubusercontent.com/427505/148095096-a999e167-fd58-4985-a40b-aa4047704b57.png)

**Comment by mhluongo** [comment]
As far as removing addresses, I'd start with just read-only accounts in the first PR @izayl. That would mean avoiding anything with the keyring service — then a follow-up can focus on removing derived addresses and maybe even entire wallets.

**Comment by izayl** [comment]
Yeah, that's what I thought

**Comment by VladUXUI** [comment]
[Link to Figma ](https://www.figma.com/file/EiXpBpNz2HcoeFJftgC5oc/?node-id=201%3A3380)
@izayl here is a Figma link with the assets.
I've also mocked up how a version without edit/favourite would look.

**Comment by henryboldi** [comment]
@izayl How's the remove feature going? :)

**Comment by izayl** [comment]
> @izayl How's the remove feature going? :)

Still working in progress, I'll create pr as soon as possible
