### ISSUE TITLE
ENS subdomains currently not supported.  Please 

### ISSUE THREAD

**Issue by EvanVanNessEth** [tallycash/extension#802]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/875438141610270740/928450413345271909

### What would you like to be able to do?

I'd like to be able to use my ENS subdomain.

I ran across this when watching my wallet upon starting Tally for first time

**Comment by mhluongo** [comment]
Ty ser, sniping this for funsies.

**Comment by mhluongo** [comment]
Woot, turns out this is supported as of #786! It'll land in the next release :)

**Comment by EvanVanNessEth** [comment]
best turnaround ever
