### ISSUE TITLE
Password fields - error message text overlap

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#811]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/929069908619300914

### What browsers are you seeing the problem on?

Chrome, Firefox

### What were you trying to do?

Test what happens if incorrect passwords are filled in. Too short and non matching passwords.

### What did not work?

When filling in a password and the 1st and 2nd password are too short or don't match, the green box around 'repeat password' slightly overlaps the text 'Must be at least 8 characters' / 'Passwords don't match'.

<img width="311" alt="Screenshot 2022-01-07 at 18 51 19" src="https://user-images.githubusercontent.com/71384922/148634580-d9d90e08-0f2d-41b8-ba00-e1cb77565d5f.png">

### Version

Community Edition v0.10.1

**Comment by Shadowfiend** [comment]
Added Firefox to the list as it's been observed there as well.
