### ISSUE TITLE
Sign with Ledger

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#815]
- [x] Unlock Ledger to sign:
 Flow here is you click sign first and then we tell you to unlock if it's locked.
This is a screen similar to the onboarding one reminding to plug, unlock and select app.

- [x] Screen explaining that Tally is waiting for a confirmation from Ledger

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/150163586-31b7789b-1abe-430d-babf-3f5a807fbb6a.png)
![image](https://user-images.githubusercontent.com/80846886/150163602-cc32e5c4-2d3c-42c5-81e8-f4cf2b2c083f.png)

Uncertain if "refresh" button is necessary or no

**Comment by mhluongo** [comment]
Implemented :)
