### ISSUE TITLE
Wallet $ Balance not updated

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#825]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/930855780498931744

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Same user as issue #824 installed 0.10.2

Trying to send ETH.

### What did not work?

transaction went well, eth balance updated, $ balance not updated, transaction info not found in activity

![image](https://user-images.githubusercontent.com/71384922/149237109-6c2e90fd-309e-412e-a781-ed61bf94d7ef.png)

(It would be nice to have a small button near $0 balance for refreshing)

### Version

Community Edition v0.10.2

**Comment by SJQuality** [comment]
This seems to be working. We also have that button now. Closing.
