### ISSUE TITLE
Wallet balance showing up in overview but not in wallet page

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#826]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Test version 0.10.2 with a read only wallet

### What did not work?

The overview page is showing correct token balances, prices and total $ balance.  The wallet page however is showing no assets and balance. 

<img width="354" alt="Screenshot 2022-01-13 at 00 08 30" src="https://user-images.githubusercontent.com/71384922/149237428-0f528df4-e49d-4c35-b904-dbd0841452bb.png">

<img width="351" alt="Screenshot 2022-01-13 at 00 08 37" src="https://user-images.githubusercontent.com/71384922/149237439-9ba73e08-32d3-4b4f-a37b-46296e71bbe9.png">

After installing an additional read-only address, the wallet page of both address is now showing correct information. So it seemed to require a 2nd address to be added for the 1st address wallet page to fill correctly.

### Version

Community Edition v0.10.2

**Comment by henryboldi** [comment]
📝 I see what's likely the same issue happening with specifically ETH at `0x208e94d5661a73360d9387d3ca169e5c130090cd`

**Comment by SJQuality** [comment]
I've not see this happen with latest builds. Closing, will keep an eye on it though.
