### ISSUE TITLE
Swap UI Tasks

### ISSUE THREAD

**Issue by itsrachelfish** [tallycash/extension#829]
There are a few UI tweaks that would help clean up the swap flow tremendously! 

## Insufficient balance warning always displayed when selecting swap assets
![insufficient-balance-swap](https://user-images.githubusercontent.com/1670549/149443880-302a96eb-15fd-4795-8df1-d9202486d15d.png)

## Search / filtering tokens
The filter doesn't actually change which assets are displayed.
![swap-search](https://user-images.githubusercontent.com/1670549/149445982-a3fd4e45-fb8c-4f7e-8bf3-678895a0e295.png)

## Icons should match exchange route
Right now the exchange route only has a single hardcoded Uniswap icon. Fortunately 99% of the time our swaps are going through uniswap!
![uniswap-icon](https://user-images.githubusercontent.com/1670549/149445902-a93e379b-c930-4036-af1d-f6cfdfcb0294.png)

## Loading indicator when waiting for quote
It takes a couple seconds to load the quote from the 0x API so it would be nice if the "Get final quote" button could display a loading state.
![get-final-quote](https://user-images.githubusercontent.com/1670549/149446690-f918d07f-1a55-400d-af91-14a8bc182ce4.png)

## Loading indicator for asset amounts
We need to refactor the swap redux slice to use the quote API for everything instead of the now deprecated prices API. However this will add a couple seconds of loading time whenever a user changes the amount they want to swap. It would be nice if we could display a loading indicator where the asset amount input field is.

**Comment by greg-nagy** [comment]
I think this issue is safe to close as a huge overhaul has happened in swap land.
