### ISSUE TITLE
Always show raw tx data in an advanced section 

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#832]
We have a number of transactions that we don't yet decode... and even when we do, nothing is perfect. The user should always be able to see the actual hex data making up a transactions.

Here's an example tx that we display incorrectly. As a user, I just want to make sure the thing I'm signing is right.

![Screenshot from 2022-01-14 08-58-07](https://user-images.githubusercontent.com/427505/149527440-77151d47-39b8-4a77-a06d-eed472a20a1f.png)

Apologies if we already have something for this in designs @VladUXUI. The closest I could find was this advanced tab, but haven't seen anything with raw hex

![Screenshot from 2022-01-14 09-03-45](https://user-images.githubusercontent.com/427505/149527905-bfe94cb9-dfb1-4c0a-ac03-fbf0a87e387a.png)

**Comment by VladUXUI** [comment]
We don't have raw tx details designs.
But i think having this page + a raw data toggle would be ideal.

Would this be a high priority or medium?

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/149895684-0af8d67c-e270-4eb5-9ff2-58f1ab6da21d.png)

Copy button should copy to clipboard.
Decode button is still a bit in the air until we find a good website to send them too
