### ISSUE TITLE
error message overlap with text while creating password

### ISSUE THREAD

**Issue by rootial** [tallycash/extension#835]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/932580140012175380

### What browsers are you seeing the problem on?

Firefox

### What were you trying to do?

1 try to "add wallet"
2 select "import metamask"
3 input a  password with length of 6
4 Click "Begin the hunt"

### What did not work?

![image](https://user-images.githubusercontent.com/3824034/149751998-05c4d00b-bf45-4664-8b30-3a1feaf530c3.png)

### Version

Community Edition v0.10.2

**Comment by Naxsun** [comment]
Same issue as reported in  https://github.com/tallycash/extension/issues/811 and closed in https://github.com/tallycash/extension/pull/831
