### ISSUE TITLE
Asset prices not loading, displayed as text 'US'

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#837]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/932683842362429460

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

A user loaded an account through a MM seed

### What did not work?

The asset prices and subsequently the wallet $ balance is not loaded. It's displayed as text, 'US'.

![image](https://user-images.githubusercontent.com/71384922/149820012-f9875a89-1b98-4450-b02d-92c1b0422552.png)

### Version

Community Edition v0.10.2

**Comment by mhluongo** [comment]
This is pretty rough. I've never seen it in testing, I wonder if it's a locale issue?

**Comment by mhluongo** [comment]
This has been closed since the last release!
