### ISSUE TITLE
Ledger UI setup and initial features

### ISSUE THREAD

**Issue by greg-nagy** [tallycash/extension#840]
Ledger connection UI can use the redux + webext-redux + async thunk data flow to communicate with the background. 
(No need for an extra port communication)

- [x] create signing redux slice
- [x] add new import wallet item for ledger
- [x] open new tab
~~- [ ] implement browser detection~~ - We will implement this when we get to firefox/webauthn implementation

**Comment by cairomassimo** [comment]
> implement browser detection

@greg-nagy why is this needed?

**Comment by greg-nagy** [comment]
@cairomassimo because the 2nd screen where the usb pop-up appears will not be present in the webauthn/firefox setup. 

But tbh it's enough to implement that when we get there.

**Comment by greg-nagy** [comment]
#893  included most of the tasks, and the rest will be handled at a later step
