### ISSUE TITLE
Update derivation path #723 to Vlad's design

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#843]
#723

On the Onboarding page in UI - Dark Figma
<img width="807" alt="Derivation path" src="https://user-images.githubusercontent.com/1918798/149979890-36d38a5e-cfab-4dfe-b605-641b1b6bf919.png">

**Comment by mhluongo** [comment]
@7alip if there's any chance you want to snipe this, I believe it's the last thing we need to unflag #723 now that #819 is merged! No worries if you don't have cycles, I just know it's going to take a bit otherwise

**Comment by 7alip** [comment]
Hey @mhluongo, It looks amazing! Of course I would like to do it with great pleasure.

**Comment by 7alip** [comment]
Is it possible to view the Figma design or maybe copy of the OnboardingPage?

**Comment by VladUXUI** [comment]
Hello @7alip , i added the derivation path screens in this figma.
Do let me know if you have any questions about it, or if you need any other screens.
https://www.figma.com/file/EiXpBpNz2HcoeFJftgC5oc/?node-id=332%3A3772

**Comment by mhluongo** [comment]
Closed by #884
