### ISSUE TITLE
Replace the dead :fox_face: 

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#845]
Our dead fox on the recovery phrase import page is cute, but I think we can do better. WDYT about a different illustration here @VladUXUI?

**Comment by VladUXUI** [comment]
Agreed it was cute, will work on something more general since we will be able to import more wallets

**Comment by VladUXUI** [comment]
<img width="191" alt="import_phrase_@2" src="https://user-images.githubusercontent.com/80846886/151173883-3f9f0d63-c95b-4f82-8267-edb1a184744a.png">

Adding a general import icon till we have a new set of illustrations
