### ISSUE TITLE
Use EnrichmentService to derive additional data about transaction requests

### ISSUE THREAD

**Issue by Shadowfiend** [tallycash/extension#848]
In #760, we special-case checking for token approval to determine whether to display a more specific signing page with limit adjustments. This special-casing misses a few more specific situations, like `approveAndCall`, and generally isn't a good path forward for any other custom signing pages (for example, richer support for swap signing on various DEXes).

Instead, a good path forward is to build on the already-budding [`EnrichmentService`](https://github.com/tallycash/extension/blob/main/background/services/enrichment/index.ts), which is designed to enrich pending and confirmed transactions with additional metadata derived from inspecting the transaction. Currently, this service [watches for `ChainService` `transaction` events](https://github.com/tallycash/extension/blob/84778351bf1936e68aa6923e87e9bf23cc25f80a/background/services/enrichment/index.ts#L130-L135), [attempts to derive additional metadata about the transaction](https://github.com/tallycash/extension/blob/84778351bf1936e68aa6923e87e9bf23cc25f80a/background/services/enrichment/index.ts#L138-L246), and [emits `enrichedEVMTransaction` with an additional `annotation` field that carries any additional derived metadata](https://github.com/tallycash/extension/blob/84778351bf1936e68aa6923e87e9bf23cc25f80a/background/services/enrichment/index.ts#L252-L260).

To scalably look up the kind of signing metadata token approvals currently use, the `EnrichmentService` should start watching the `InternalEthereumProvider`'s emitter for `transactionSignatureRequest`, attempt to derive an annotation in the same way that transactions do[^1], and emit an `enrichedEVMTransactionSignatureRequest` event. In turn, `Main` should rewire its [`transactionSignatureRequest`](https://github.com/tallycash/extension/blob/main/background/main.ts#L637-L671) event handler to instead trigger on `enrichedEVMTransactionSignatureRequest` from the `EnrichmentService`. Finally, the `Sign` page can use the `annotation` data to tailor the rendered page as relevant.

One additional feature that the sign page providers that isn't relevant to pending and confirmed transactions is the ability to customize the transaction's inputs. This issue doesn't cover refactoring that component; instead, the sign page should continue to manage this in a way custom to its particular implementation (for example, for the approval page, directly interacting with the ERC20 ABI to rewrite the approval transaction data based on edited form inputs).

[^1]: One notable difference is in the type of partial transaction requests vs full transactions. In particular, transactions can have `null`, `0x`, or data for their `input` field, while partial transaction requests can additional have an `undefined` `input` field.

**Comment by Shadowfiend** [comment]
If work here kicks off before #760 is merged, we should branch off of that (`update-approve-amount`) and go from there. That PR should be landing soon.

**Comment by mhluongo** [comment]
Closed by #861
