### ISSUE TITLE
Sending "max" ETH ... doesn't

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#858]
Attempting to send the "max" amount of ETH to myself exposed two problematic bugs

1. Choosing "max" doesn't subtract cost of gas from the total, making it impossible to ever clear out a wallet. Note that solving that completely is difficult with EIP-1559, but it'd be nice if we came close rather than discounting gas entirely.
2. A transaction that failed to broadcast didn't show up as "failed" in the UI. In addition to that, we increment the nonce, leading to another transaction that will inevitably fail.

![Screenshot from 2022-01-20 16-40-01](https://user-images.githubusercontent.com/427505/150427271-1593bdc3-a563-4a4d-b101-6f6fab16f5e4.png)
![Screenshot from 2022-01-20 16-41-40](https://user-images.githubusercontent.com/427505/150427284-e0720980-2c1d-42cc-adde-3fda5f68c88a.png)
![Screenshot from 2022-01-20 16-44-24](https://user-images.githubusercontent.com/427505/150427295-468011e4-4af6-4e36-a255-c57f75baafd7.png)
![Screenshot from 2022-01-20 16-51-25](https://user-images.githubusercontent.com/427505/150428028-c70da048-00da-49d2-9999-580759c6df6c.png)
![Screenshot from 2022-01-20 16-50-39](https://user-images.githubusercontent.com/427505/150427940-c6a0135a-cd59-43a7-80f2-2bfe18ade047.png)

**Comment by mhluongo** [comment]
Note that this issue leaves the wallet in an unusable state. The fact that we can't ask the wallet to "forget" a tx that's in limbo, that we don't have cancel tx's, and that it doesn't remove tx's that failed to broadcast are all part of the problem.

#611 is related, and would also do a lot to improve the situation here.

**Comment by Shadowfiend** [comment]
This is pretty solvable with #822 . We just need to release the nonce if broadcast fails. This can happen internally in `ChainService`.

**Comment by henryboldi** [comment]
>  Note that solving that completely is difficult with EIP-1559, but it'd be nice if we came close rather than discounting gas entirely.

https://github.com/tallycash/extension/pull/856 helps a bit too for implementing a solution to bug numero uno. If the selected asset is ETH, should we subtract the max gas fee?

**Comment by mhluongo** [comment]
> If the selected asset is ETH, should we subtract the max gas fee?

That's exactly what we should do 💯

**Comment by henryboldi** [comment]
Sweet, I'll get that sorted 🙂

**Comment by SJQuality** [comment]
Looks like 1. is still an issue. 2. looks like it's resolved.

https://www.awesomescreenshot.com/video/8895316?key=638af08d41859819760442e46b85a1d3

**Comment by jagodarybacka** [comment]
@puppycodes Blocked because of https://github.com/tallycash/extension/issues/1432#issuecomment-1161913579

**Comment by jagodarybacka** [comment]
No longer blocked, requirements in #1432
