### ISSUE TITLE
Can't approve token for swaps

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#860]
Just tried to swap some KEEP to renZEC. Results below

![Screenshot from 2022-01-20 18-08-06](https://user-images.githubusercontent.com/427505/150436938-11614183-b2e4-41d9-a780-ceb147454737.png)
![Screenshot from 2022-01-20 18-09-37](https://user-images.githubusercontent.com/427505/150436949-7a6f66cf-a1f3-430c-bd48-0b7b41e9735d.png)
![Screenshot from 2022-01-20 18-10-05](https://user-images.githubusercontent.com/427505/150436966-069a0d01-beef-48fb-ad48-4aa1cd2d0d00.png)

While I couldn't get a screenshot fast enough, it appears the "Swap assets" page flashes at the bottom before the extension blanks. There aren't any obviously relevant errors in the frontend or background console, which surprised me tbh

Tested against `swaps-qa-build` on Chromium 97.0.4692.71 / Ubuntu

**Comment by 0xDaedalus** [comment]
Interesting - uniswap v3 swaps seem to be fine - but uniswap v2 result in a blank screen

**Comment by 0xDaedalus** [comment]
Digging into ethers.js I see that https://github.com/ethers-io/ethers.js/blob/master/packages/providers/src.ts/json-rpc-provider.ts#L220 always throws an error - are we using the wrong function here?

**Comment by Shadowfiend** [comment]
Not the wrong function… But one that is unexpectedly not supported by default.
