### ISSUE TITLE
Swaps - Can't swap ETH for ERC20

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#862]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap ETH for any ERC20

### What did not work?

When I have ETH selected as my sell currency, the buy dropdown won't populate with tokens 

https://user-images.githubusercontent.com/7005061/150449021-5d569b51-327e-4df0-b890-31a3a1f66ccc.mov

**Comment by Shadowfiend** [comment]
This won't be supported in v1, just a heads up.
