### ISSUE TITLE
Swaps - "Slippage tolerance" button does nothing when clicks

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#863]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I clicked slippage tolerance, expecting to see a dropdown to change %

### What did not work?

Button changed color on hover... when I clicked it, it had no effect:

<img width="402" alt="Screen Shot 2022-01-20 at 8 16 12 PM" src="https://user-images.githubusercontent.com/7005061/150449188-107598e6-6b3e-4074-a7f5-baf06fa30bda.png">

<img width="279" alt="Screen Shot 2022-01-20 at 8 16 58 PM" src="https://user-images.githubusercontent.com/7005061/150449192-3bcecae7-d29f-4632-aec2-ba890df9ad60.png">

**Comment by VladUXUI** [comment]
Since this is a restriction that we don't have control over.
I propose we just change the dropdown to a text
