### ISSUE TITLE
Swaps - UX bug - we don't display quantity you current have

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#865]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

N/A

### What did not work?

Open to discussion or disagreement, but I believe we should absolutely display the current balance of the sell currency that a user has on the Swaps page.

We don't currently display this:

<img width="377" alt="Screen Shot 2022-01-20 at 8 35 46 PM" src="https://user-images.githubusercontent.com/7005061/150449675-69c69c57-2ade-4d04-8531-8c4a4397d3a9.png">

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/150483737-3f97e336-2144-45bf-a962-877f292cb39d.png)

No discussions or disagreements. This might be part of the UI fixes that @Henry was working on.
We should also show $ amount when asset amount is added.

**Comment by VladUXUI** [comment]
Will be fixed here 
https://github.com/tallycash/extension/issues/829

**Comment by greg-nagy** [comment]
@VladUXUI Can we close this? As the main PR for #829 has been merged. If so please close it.

**Comment by VladUXUI** [comment]
Partially fixed, moving this to https://github.com/tallycash/extension/issues/972 and closing

**Comment by VladUXUI** [comment]
https://github.com/tallycash/extension/issues/972
