### ISSUE TITLE
Swaps - no feedback if user enters amount of sell asset larger than current balance 

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#866]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I entered 10000+ KEEP but only have a balance of 470; I expect to get some warning that I don't have this much KEEP. Including either a notification I've put in more than I have and the 'get final quote' button being disabled.

### What did not work?

I get no feedback. I am allowed to attempt the transaction. It loads/spins forver.

https://user-images.githubusercontent.com/7005061/150449927-83bacff0-a53f-4836-8227-b9d21019b09a.mov

**Comment by mr-michael** [comment]
Related: I'm able to proceed and click 'get final quote' even if I have a zero amount for sell asset. Loader spins for infinity on main Swaps page.

https://user-images.githubusercontent.com/7005061/150452112-63f0be43-cce3-445d-bf42-be44939b1d6a.mov

**Comment by VladUXUI** [comment]
![image](https://user-images.githubusercontent.com/80846886/150483136-4b71b7e4-ad33-4932-ab05-69b84786e23c.png)
We have an error state design

**Comment by VladUXUI** [comment]
Will be resolved here
https://github.com/tallycash/extension/issues/829

**Comment by greg-nagy** [comment]
@VladUXUI Can we close this? As the main PR for #829 has been merged. If so please close it.
