### ISSUE TITLE
Swaps - middle 'flip' button does not work

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#869]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Flip the position of buy asset and sell asset

### What did not work?

Button does not appear to have any impact (this could be b/c there is no market for KEEP OXT?)

See 30 secs in video below (I have 27 OXT and a few hundred KEEP):

https://user-images.githubusercontent.com/7005061/150688466-f6036eae-7fed-484b-bef2-da74532bf454.mov

**Comment by Shadowfiend** [comment]
This… Was a question that I had a couple of times and never got to the point of bubbling up. Do we expect that icon to be a button that flips the trade?

**Comment by henryboldi** [comment]
> Do we expect that icon to be a button that flips the trade?

I also believe this has been an open question. Still, I could totally see how the majority of users will expect it to be a button

**Comment by Shadowfiend** [comment]
Yeah I more than once have been like "this could absolutely be clickable" while interacting lolol. 

Straightforward enough to implement I expect.

**Comment by VladUXUI** [comment]
Yes indeed, that button should swap the from and to assets
