### ISSUE TITLE
Swaps - misc. funkiness with token dropdown

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#870]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

n/a

### What did not work?

- icons not loading
- 
- there are 2 USDC?

<img width="370" alt="Screen Shot 2022-01-20 at 8 55 27 PM" src="https://user-images.githubusercontent.com/7005061/150451686-c59d78c2-f8dd-461f-9a1f-7b036480be30.png">

- search a bit off 'btc' (why usdc or snx?)

<img width="362" alt="Screen Shot 2022-01-20 at 8 56 21 PM" src="https://user-images.githubusercontent.com/7005061/150451779-2f493314-d40e-402f-87a4-b715b941d80b.png">

- & I don't have great videos or images but have noticed some caching issues w/list

**Comment by SJQuality** [comment]
This looks resolved. Closing. I'll keep an eye on it.
