### ISSUE TITLE
Swaps - Not able to get to approval page w/OXT

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#871]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap OXT

### What did not work?

I enter 25 OXT (I have 27) as my sell asset, but the buy asset amount remains zero

https://user-images.githubusercontent.com/7005061/150452579-ac255810-c398-49c2-8283-dc9275a2144a.mov

**Comment by Shadowfiend** [comment]
I think the issue here is probably the asset is unsupported and we're not reporting that correctly. Will dig.
