### ISSUE TITLE
Swap - trade fails on empty activity page

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#877]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap KEEP for BAL

### What did not work?

On Sign Transaction page, Amount is Zero. After I click Sign, I'm taken to an empty activity page. Trade does not execute.

https://user-images.githubusercontent.com/7005061/150688986-c5d589d9-cb6b-4b80-bba5-d892b5e9c3fc.mov

**Comment by Shadowfiend** [comment]
> On Sign Transaction page, Amount is Zero

This is "normal", in that we don't yet have a swap-specific approval page and the amount on the sign transaction page is the transaction “value”, i.e. the amount of ETH sent (which is 0 for token activity).

> Trade does not execute

Do you see a pending transaction on the main activity list? (If you click back to the wallet and then select Activity.)

**Comment by mr-michael** [comment]
Ah, actually yes. Feel like I did not see these initially but...

https://etherscan.io/tx/0x72d3b5705190fb936acde0e7a9a000c986909377ac73b2a4636869f0dab1c9eb
https://etherscan.io/tx/0xb88466e216ff1087368f4b4eed6e894b1c2a7d459a031c277853cc8003842018

<img width="376" alt="Screen Shot 2022-01-23 at 12 04 51 PM" src="https://user-images.githubusercontent.com/7005061/150689523-582d9327-2fe2-4651-9b10-7db2c58363bf.png">

**Comment by Shadowfiend** [comment]
Got it. Okay so the issue here is that navigating from the approval transaction's signature back to the swap page isn't happening (I think I remember the change that would have broken this), combined with the lack of approval-specific sign page. The approval-specific sign page is in main, so we'll get it when we merge everything; the navigation is where I'll have to dig.

**Comment by Shadowfiend** [comment]
This should be closed on `main`.

**Comment by Shadowfiend** [comment]
Scratch that, I think my refactor is what closes it and that hasn't landed yet 😅
