### ISSUE TITLE
Asset slice migration

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#887]
The asset slice should be cleared out and rehydrated from IndexedDB before Swaps go live.

> NB: there's no asset slice migration here, and I'm assuming that's going to happen later.

_Originally posted by @mhluongo in https://github.com/tallycash/extension/issues/878#issuecomment-1020591232_

**Comment by Shadowfiend** [comment]
Possibly want to include a migration that checks all pending transactions in the db and updates their status. Found an issue with updating pending transaction confirmation status while doing swaps.
