### ISSUE TITLE
Fix janky shared slide up menu

### ISSUE THREAD

**Issue by mhluongo** [tallycash/extension#888]
The `SharedAssetInput` component has a janky animation. @henryboldi proposed a fix in the original PR

> That solution sounds good to me, but using a ref for the timeout. The `Snackbar` does something similar, although remains a victim to the same problem:

```js
  const msTillDismiss = 2500

  const snackbarTimeout = useRef<ReturnType<typeof setTimeout>>()

  const clearSnackbarTimeout = () => {
    if (snackbarTimeout.current) {
      clearTimeout(snackbarTimeout.current)
    }
  }

  useEffect(() => {
    clearSnackbarTimeout()

    snackbarTimeout.current = setTimeout(() => {
      dispatch(clearSnackbarMessage())
    }, msTillDismiss)
  }, [snackbarTimeout, snackbarMessage, msTillDismiss, dispatch])

  useEffect(() => {
    window.onblur = () => {
      clearSnackbarTimeout()
      dispatch(clearSnackbarMessage())
    }
  }, [dispatch])
 ```

_Originally posted by @henryboldi in https://github.com/tallycash/extension/pull/875#discussion_r790995747_

**Comment by Shadowfiend** [comment]
Noting that this hits all slide up menus, not just the shared asset input.
