### ISSUE TITLE
Seed gen - Design hasn't been fully implemented

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#905]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

n/a

### What did not work?

See design here: https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=5474%3A154623

Specifically the 'reveal' design is missing. Not sure if we need or want that?

Also the presentation of the seed just doesn't seem up to our standards for visual fidelity. It doesn't copy and paste well either... we don't want people copying and pasting the seed, but some users may want to save in a text file offline

<img width="343" alt="Screen Shot 2022-01-27 at 6 00 24 PM" src="https://user-images.githubusercontent.com/7005061/151459227-f60ae9c7-d1a3-4be9-ad04-3dc9d18be4b1.png">

**Comment by SJQuality** [comment]
Since this, a "Copy to clipboard" feature has been added. I also think @jagodarybacka is working on this currently through https://github.com/tallycash/extension/issues/1338
