### ISSUE TITLE
Wallet activity for newly created wallet not loading

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#914]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/937276868997021696

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

The user was actually using Brave but this is not in the drop down.
Browser Brave v.1.34.81 on Mac, wallet version ben1d6e (2022-01-26)

The user created a new wallet and wanted to test out the wallet. 

### What did not work?

On below wallet overview page the spinning wheels were displayed for all wallets impermanently. This was a new wallet and there were no assets and transactions.

![image](https://user-images.githubusercontent.com/71384922/151712116-738c10a2-f189-4c1c-ab5d-a95075617a36.png)

An additional screen recording of the wallet activity: https://discord.com/channels/808358975287722045/888500174685614090/937327492937703445

### Version

Community Edition v0.11.0

**Comment by Shadowfiend** [comment]
After 2.5 minutes or so, this should expire even if no history was found. Is it lasting past that point?

We're working on better heuristics to figure out that we have as much data as we'll find, it's just more complicated to be sure with older accounts. Still, new ones should be straightforward to detect and something we can improve on easily.

**Comment by Naxsun** [comment]
Users response: Yes, the spin wheels have not disappeared, and one day has passed. As a further test, I tried restarting 

Brave, now it's been 15 minutes with the spin wheels still all active.

**Comment by Shadowfiend** [comment]
Perfect, thanks for the update. We'll dig in!

**Comment by SJQuality** [comment]
I'm not seeing this as a current issue. I'm also not on a Mac.

**Comment by Naxsun** [comment]
Haven't seen this the last months. I believe it was a single issue. Probably best to close.
