### ISSUE TITLE
Several minor UI/UX points

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#917]
### Discord Discussion Link

Not applicable

### What would you like to be able to do?

- The wallet address on the top right is not showing capital letters for addresses, the activity tab is. For me it would be cleaner to have it consistent with or without.

On the Add wallet page. 
- When a user is in the 'read-only address input page' or 'MM recovery phrase input page' and selects 'back' it jumps back to the wallet page and not the 'add wallet' page.
- Textual: "Let's set Tally up with a wallet. Select with what wallet you would like to continue." --> maybe more like "Let's add a wallet to Tally, choose from the options below'

For new recovery phrases:
- On the new recovery phrase page where the 24 words are displayed. Add notifications for secret, do not copy paste, no screenshot etc. On the next page for the word check it's called 'secret recovery phrase'. Maybe use that term also on the previous page.
- For the word check I would make the orange boxes all the same size with the text centered
- In the verify, when removing a word in the middle all the words after that jump up a position. I would just keep that specific spot open, and keep all the other words in their position. Maybe also add a 'clear all' button.
- With long words on the first column it looks like the number on the 2nd column is slightly moved. In below snapshot for # 21.
<img width="252" alt="Screen Shot 2022-01-30 at 20 01 48" src="https://user-images.githubusercontent.com/71384922/151713583-1a04bbc7-d0fd-44b2-8789-683cb6f7f949.png">

**Comment by henryboldi** [comment]
Thank you @Naxsun 🙇

**Comment by henryboldi** [comment]
I'd love to split this into separate GH issues. For example,

> When a user is in the 'read-only address input page' or 'MM recovery phrase input page' and selects 'back' it jumps back to the wallet page and not the 'add wallet' page.

Is a different can of worms vs.,
> With long words on the first column it looks like the number on the 2nd column is slightly moved. In below snapshot for # 21.

It'd be easier to keep track of and knock things off the list separated.

**Comment by Naxsun** [comment]
Yeah that makes sense. I'll go over 0.12.0 and verify which ones still apply and create separate issue.

**Comment by henryboldi** [comment]
Thank you for putting together this issue, @Naxsun!

<hr/>

- I believe the back button bug has been moved into its own series of issues https://github.com/tallycash/extension/issues/1323

<br/>

- > With long words on the first column it looks like the number on the 2nd column is slightly moved. In below snapshot for # 21.

It looks like it's aligned correctly? The numbers are aligned right. I'll double check.

<br/>
- As for the design feedback generally, I'll leave that to @VladUXUI
