### ISSUE TITLE
Sign with Ledger: implement "Awaiting hardware wallet signature" screen according to specs

### ISSUE THREAD

**Issue by cairomassimo** [tallycash/extension#921]
[Figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A153814)

Some work done in #910.

**Comment by greg-nagy** [comment]
[This refactor](https://github.com/tallycash/extension/pull/910#discussion_r794460019) probably should happen here.
