### ISSUE TITLE
Flash of extension popup missing height and width

### ISSUE THREAD

**Issue by henryboldi** [tallycash/extension#924]
I believe introduced in https://github.com/tallycash/extension/pull/893/, the extension popup flashes without a height and width. Demo GIF below,

<img width="330" alt="flash" src="https://user-images.githubusercontent.com/1918798/151870656-5dcd50f5-ccf6-48a7-bbac-e277320c2361.gif">

**Comment by cairomassimo** [comment]
We can add an hardcoded class `popup` to `<body>` in `popup.html`, restore the sizing in `main.css`, but scope it to `body.popup` instead of `body` so it won't affect `tab.html`. Assigning to me (not this week) but feel free to reassign.
