### ISSUE TITLE
Snackbar is covering clickable elements even when its not visible

### ISSUE THREAD

**Issue by wojciech-turek** [tallycash/extension#937]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Interact with a button.

### What did not work?

The hidden wrap is blocking user interaction in that area as it covers the button.

![image](https://user-images.githubusercontent.com/61434499/152332741-3632c450-0747-4396-8213-423450b41e17.png)

**Comment by Shadowfiend** [comment]
Whomp. My fault. Need to add pointer events to just the hidden class (it was on always, which made for weird behavior when the snack bar was *visible*).
