### ISSUE TITLE
Different keyrings mixed together

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#940]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

I added two keyrings to Tally

### What did not work?

![image](https://user-images.githubusercontent.com/80846886/152361407-70319bd2-c61f-4164-865b-ba162a5fc13b.png)

- The above two addresses are derived from 2 different keyrings, but they are bundled together.
- Clicking on Add address, it adds an address to the first Keyring.

This is tricky if users check out tally using a New recovery phrase and than decide to import

They should all have their own category, if we have more from same category, we should number them as Import 1, Import 2...:
New seed = Tally
Import phrase = Import
Ledger = Ledger 
Read-only = Read-only

**Comment by SJQuality** [comment]
Looks like this was resolved in https://github.com/tallycash/extension/pull/1001 closing
