### ISSUE TITLE
Swaps - Swap fails on Sign Transaction

### ISSUE THREAD

**Issue by mr-michael** [tallycash/extension#942]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap KEEP for OXT. Both of which I believe are unapproved.

### What did not work?

On 'Sign Transaction' I click 'Sign' and am bounced back to Swaps main screen.

https://user-images.githubusercontent.com/7005061/152435757-b30a7463-7ef3-46be-b455-8c9d8e82d79b.mov

Under activity I see a 'pending' txn but nothing sticks on etherscan.

https://etherscan.io/tx/0x9fdafc5eccbf6d7343388ac1acc1d5e51415b3f88e189c4abe00dc549bf95240

<img width="386" alt="Screen Shot 2022-02-03 at 4 57 24 PM" src="https://user-images.githubusercontent.com/7005061/152435990-6bda52f3-c4b0-4460-b563-9686bfca62ec.png">

Txn:

<img width="1440" alt="Screen Shot 2022-02-03 at 4 57 16 PM" src="https://user-images.githubusercontent.com/7005061/152435992-50ac658e-2fee-4d75-84e0-73f7b3754a04.png">

<img width="381" alt="Screen Shot 2022-02-03 at 4 57 20 PM" src="https://user-images.githubusercontent.com/7005061/152435993-573273a8-8093-4e36-860b-50923694c282.png">
 

### Relevant log output

```shell
Version: 24f8f9f (2022-02-03)
```

**Comment by mr-michael** [comment]
Actually strike that, going off the UI (and fact that there's no 'approve' button for keep or oxt) I suppose they are approved?

**Comment by Shadowfiend** [comment]
Yeah, you'll see something else if they're not approved.

**Comment by mr-michael** [comment]
Logs from a fresh install experiencing this issue with build 1863 (https://github.com/tallycash/extension/actions/runs/1807539772)

[mh logs.log](https://github.com/tallycash/extension/files/8017003/mh.logs.log)

**Comment by greg-nagy** [comment]
This has been fixed since then.
