### ISSUE TITLE
Transaction status and duplicate transactions

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#953]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/939896143154909225

### What browsers are you seeing the problem on?

Brave

### What were you trying to do?

The user was testing out the wallet, receive ETH and make a swap.

### What did not work?

The same incoming transaction appears to be shown twice. Once as completed and once as pending.

![image](https://user-images.githubusercontent.com/71384922/152847343-68615a3a-0904-4def-9bbd-4f5b91aefeb5.png)

The user also attempted a swap on 'clipper exchange'. The transaction wasn't created (does not show up in Etherscan) but does show up in Tally as pending.

I've asked the user if he's comfortable providing the address for this wallet to verify transactions.

### Version

Community Edition v0.11.0

**Comment by mhluongo** [comment]
I believe this will be closed by #950
