### ISSUE TITLE
Wallet doesn't connect to dapps - need to switch on/off

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#960]
### Discord Discussion Link

n/a

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Connect Tally to dapps

### What did not work?

I couldn't connect to dapps that I was able to connect to before. Tried Uniswap, Synthetix, Keep Dashboard & Convex. Switching Tally as default to off allowed me to connect with MetaMask.

After switching the Tally extension off and on again (settings --> extension --> toggle on/of) it allowed to to connect to the dapps again.

![image](https://user-images.githubusercontent.com/71384922/153069179-56a70eb5-dbc5-42c8-9585-62926423320b.png)

### Version

Community Edition v0.11.0

**Comment by SJQuality** [comment]
@Naxsun You still seeing this issue?

**Comment by Naxsun** [comment]
Nah let's close👍 overall connecting to dapps is very smooth for me. Let's create a new ticket in case there's any specific issue in the future.
