### ISSUE TITLE
Remove '.only' and fix tests in keyring-integration.test.ts

### ISSUE THREAD

**Issue by 0xDaedalus** [tallycash/extension#962]
We have two `.only` tests in `keyring-integration.test.ts` meaning the other tests in the file do not run on `yarn test`.  

https://github.com/tallycash/extension/blob/main/background/tests/keyring-integration.test.ts#L199
https://github.com/tallycash/extension/blob/main/background/tests/keyring-integration.test.ts#L337

When the `.only`'s are removed - 7 of the 8 other tests fail.  We should remove the `.only`'s and get the other tests into a passing state.

**Comment by mhluongo** [comment]
:facepalm:

**Comment by Shadowfiend** [comment]
This is confusing to me because the linter should have blocked this from being committed and from merging in the first place… Let's check in on that as well. It should be catching `.only`s.

**Comment by Shadowfiend** [comment]
Looks like I'm thinking of https://www.npmjs.com/package/eslint-plugin-no-only-tests and… It is not actually in use here or in Keep projects, so I must be taking crazy pills.

Anyway, we should add this plugin and enable it.

**Comment by 0xDaedalus** [comment]
Closed by #1006
