### ISSUE TITLE
Add 'back' button to Password set-up screen

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#964]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/893564740427743292/939849090425045054

### What would you like to be able to do?

User request:

Be able to go to the previous page when in the 'First, let's secure your wallet' view.

From
![image](https://user-images.githubusercontent.com/71384922/153208852-8cb9cbc5-27f7-4c31-a73e-8ebfcf43d4d7.png)

Be able to go back to 
![image](https://user-images.githubusercontent.com/71384922/153180694-0fa921e9-80ea-4f1a-9768-24ac9d0de2f2.png)

**Comment by dills122** [comment]
I put a PR together for this.

#1018

**Comment by dills122** [comment]
@Naxsun Should be good to close this out. #1018  resolved this issue.

**Comment by mhluongo** [comment]
Thanks for the contribution @dills122! ♥️

**Comment by Naxsun** [comment]
Thanks @dills122!
