### ISSUE TITLE
Please add a pop-up clarification to "add wallet" button

### ISSUE THREAD

**Issue by alterkahn** [tallycash/extension#975]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/893564740427743292/941724624998236221

### What would you like to be able to do?

<img width="381" alt="Снимок экрана 2022-02-11 в 18 37 21" src="https://user-images.githubusercontent.com/67752860/153631783-ac057a58-7050-48a1-9ca8-b1cc8317c865.png">
 
Please add a small clarification on the "add wallet" button to eliminate future misunderstandings. Clarify please that users will not be able to move their funds to another wallet by importing seed phrases created in Tally, in case they got funds onto additionally created public keys.

**Comment by mhluongo** [comment]
> Clarify please that users will not be able to move their funds to another wallet by importing seed phrases created in Tally

Hey @alterkahn, this isn't true? Any wallet that supports 24-word recovery phrases can import Tally's wallets. It uses the standard derivation, and should interoperate with Ledger, MyCrypto, etc. Can you explain what you're trying to accomplish a bit more here?
