### ISSUE TITLE
Swaps: Duplicate (or more) assets in swap to:

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#979]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Swap tokens and select the swap to: asset

### What did not work?

I couldn't decide what to swap to, multiple tokens are duplicated.

<img width="366" alt="image" src="https://user-images.githubusercontent.com/80846886/153705545-a97c7933-935a-417c-b0b0-adef9e039994.png">

### Relevant log output

```shell
Version: e2c0d12 (2022-02-11)
```

**Comment by Shadowfiend** [comment]
Unfortunately these aren't duplicates per se. They're different versions of the interest-bearing tokens for Aave, whose token list descriptions are incomplete :/ The token lists themselves have some extra metadata, but I expect we'll need to massage this stuff in the Tally token list.
