### ISSUE TITLE
Tx Details: Gas Price showing as max gas

### ISSUE THREAD

**Issue by VladUXUI** [tallycash/extension#982]
### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

check out tx details.

### What did not work?

In some instances, gas price is shown as Max Gas
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/80846886/153706926-98beabfd-6742-4487-aea0-919af9a97991.png">

**Comment by Shadowfiend** [comment]
Feels like a confusion in what we're pulling from gas price--the requested price vs the confirmed one. Possible we're not handling that properly.
