### ISSUE TITLE
Better UX when onboarding without connected Ledger

### ISSUE THREAD

**Issue by fernya** [tallycash/extension#984]
![Screenshot from 2022-02-09 14-22-27](https://user-images.githubusercontent.com/427505/153275835-594d32d9-3461-4f2a-b95b-c5d6ea70b38a.png)

This is what happens when I try to connect but haven't plugged any devices in. Would be nice for it to auto-refresh / use the same page to share the error.

_Originally posted by @mhluongo in https://github.com/tallycash/extension/issues/965#issuecomment-1034119188_

**Comment by VladUXUI** [comment]
Picking this up

**Comment by VladUXUI** [comment]
<img width="1404" alt="image" src="https://user-images.githubusercontent.com/80846886/154229918-9e348490-4689-4430-aff3-23b09cf1fc8a.png">

Device not connected after clicking on continue:
- Add error state with refresh button
- Continue button is disabled

If refresh is done and device is connected:
- remove the error 
- enable the button 

Auto refresh would also indeed be nice, so if user plugs in the device, the error is gone and button is enabled.

**Comment by VladUXUI** [comment]
[Link to Figma](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6862%3A171213)

The error component is one that might already be built, but i'm uncertain

**Comment by fernya** [comment]
Looks sweet, but let's have a recap based on the current flow:
- We're adding a Ledger to the wallet, the [a new tab pops up](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A150916)
- When we click on "Continue" we can't tell in advance if something went wrong.
- Only when ["Select the device"](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A150917) window is opened we have two options:
  - Click on a correct device then on "Connect" -> not interesting right now
  - Click on cancel or *anywhere else* on the page -> interesting here, we've got an error

The design you put here could be added only after the last action was done, so basically we'll go back to the starting page with additional bells and whistles shown.

I think that if the extension never had any paired Ledger devices then I think no automatism could be implemented here to disable/enable buttons and add/remove warning texts. We could label the button as "Retry connection" (as Massimo suggested) If it looks okay on your side, I'll do in that way.

**Comment by VladUXUI** [comment]
>Click on cancel or anywhere else on the page -> interesting here, we've got an error
If any of these happen, we should definitely take them back to the first page and show an error

>I think that if the extension never had any paired Ledger devices then I think no automatism could be implemented here to disable/enable buttons and add/remove warning texts. We could label the button as "Retry connection" (as Massimo suggested) If it looks okay on your side, I'll do in that way.

Got it, that sounds good. It's ideal to rename the button to Retry connection, but If it's easier we can just leave the button as is (with Continue)
