### ISSUE TITLE
Let to restart recovery phrase generation

### ISSUE THREAD

**Issue by pdyraga** [tallycash/extension#996]
### Discord Discussion Link

https://discordapp.com/channels/808358975287722045/875438141610270740/943093088270811217

### What would you like to be able to do?

When I made a mistake when writing down my recovery phrase and verification failed, I would like to have a button that would let me go back and generate another recovery phrase and verify it. 

Right now, I am left in a sort of a dangling state with no option to restart the process. The only way is to close the extension.

![image](https://user-images.githubusercontent.com/4712360/154062384-0ead6c3b-d5e6-472c-9079-3180cc4f83bd.png)

**Comment by VladUXUI** [comment]
This should be fixed when new seed design will be added. Henry mentioned he might get to it this week.
<img width="331" alt="image" src="https://user-images.githubusercontent.com/80846886/154215762-70d6bc43-b0b4-4374-bf7b-923112e20b03.png">
