### ISSUE TITLE
Dropped transactions and transaction order

### ISSUE THREAD

**Issue by Naxsun** [tallycash/extension#998]
### Discord Discussion Link

https://discord.com/channels/808358975287722045/888500174685614090/943073452284342302

### What browsers are you seeing the problem on?

Chrome

### What were you trying to do?

Send ETH, verify activity history

### What did not work?

The wallet had a balance of 0.1 ETH. I was trying to send this balance to another wallet. 

- Selecting 'Max' leads to the full ETH balance being selected for send, without a reserve for fees. Submitting this leads to a dropped transaction. 
- Reduced the amount to 0.05ETH --> ETH was successfully send, transaction status in Tally initially remained pending. Actual transaction fee 0.001 ETH.
- Remaining balance of 0.049 ETH, send another 0.0045 successfully. Transaction status in Tally for this transaction as well as the previous transaction was updated to completed.

The order of the transactions in Activity is not chronological. 
- Incoming transaction of 0.1 ETH (Feb 12)
- Dropped transaction of 0.0486 ETH (Feb 15)
- Successful transaction of 0.045 ETH (Feb 15)
- Dropped transaction of 0.0994 ETH (Feb 15)
- Successful transaction of 0.05 ETH (Feb 15)

The actual transaction order was, new/top to old/bottom
- Successful transaction of 0.045 ETH
- Dropped transaction of 0.0486 ETH
- Successful transaction of 0.05 ETH
- Dropped transaction of 0.0994 ETH
- Incoming transaction of 0.1 ETH

<img width="366" alt="Screen Shot 2022-02-15 at 14 22 02" src="https://user-images.githubusercontent.com/71384922/154071670-4bfccd72-4c7f-4590-808a-eece38508868.png">

<img width="366" alt="Screen Shot 2022-02-15 at 14 22 09" src="https://user-images.githubusercontent.com/71384922/154071691-9906c3f0-fbf8-4370-b453-0c86ad720f51.png">

### Version

Community Edition v0.11.2

**Comment by SJQuality** [comment]
I'm wondering if the issue has something to do with what we are using to order the transactions and what is expected? Are they being ordered in the order that the user initiated them, or the order they were actually completed?

**Comment by Naxsun** [comment]
This is improved, but not fully fixed I think. So I expect the sorting is based on nonce, so usually order of initiation and order of completion should be the same.

However, in case of dropped transactions the nonce is the same. Just did a quick check and below top 3 transactions all 'have' nonce 31. 

<img width="374" alt="Screen Shot 2022-05-11 at 10 20 47" src="https://user-images.githubusercontent.com/71384922/167803395-8daeaba9-fa75-4343-a67b-84243745b1d3.png">

The two dropped ones were initiated before the successful one (otherwise the 2 dropped once would have had nonce 32).

I believe if we'd want to get this sorted better the sorting should be based on nonce + and then based on time of _creation in the extension._

It's already better than it was before though.

**Comment by Shadowfiend** [comment]
We don't currently track creation time or failure time (also reasonable for dropped txes), but I tend to agree with the sort you're proposing. We should definitely sort same nonce + included in a block over same nonce + dropped, and I thought I had already done that 🤔

**Comment by Naxsun** [comment]
To be sure. Above is already sorted on nonce, it's just that the dropped ones - created earlier, are above the successful one - created later. All have the same nonce.

This is version 0.13.3. 

I noticed the dropped ones don't have a date code on the top right, successful ones do. Don't know if that has anything to do with it, just an observation. Could be based on completion date, which we don't have ofc with the dropped ones.
